### ISSUE TITLE
Using containsAll

### ISSUE THREAD

**Issue by orarnon** [hashicorp/consul-template#1045]
Hi guys,

I was trying to get containsAll to work with CT 0.19.4 and was not successful.
Referring to https://github.com/hashicorp/consul-template#containsall

I wanted to get the following effect using the above function:

```
{{range service "myservice"}}{{if and (.Tags | contains "production") (.Tags | contains "eu-west-1a")}}server          {{.Node}} {{.Node}}:{{.Port}} maxconn 400 weight 100 check inter 2s fall 2{{end}}{{end}}
```

It was not clear to me, without an example, how to create and use and iterable object for containsAll.

**Comment by sethvargo** [comment]
Hi @orarnon 

The first argument is the list of tags, the second is the tag to search. There's no way in Go's templating language to create a native slice, so you'd either need to keep what you have or use scratch:

```liquid
{{ scratch.MapSetX "tags" "1" "eu-west-1a" }}
{{ scratch.MapSetX "tags" "1" "production" }}
{{ if .Tags "tags" | containsAll scratch.MapValues }} {{ end }}
```

**Comment by piavka** [comment]
afaiu u can also use a few tricks like 
```
{{ $requiredTags := parseJSON "[\"production\",\"eu-west-1a\"]" }}
{{range service "myservice"}}{{if .Tags | containsAll $requiredTags)}}server          {{.Node}} {{.Node}}:{{.Port}} maxconn 400 weight 100 check inter 2s fall 2{{end}}{{end}}
```
or
```
{{ $requiredTags := split "production eu-west-1a" | split " "}}
{{range service "myservice"}}{{if .Tags | containsAll $requiredTags)}}server          {{.Node}} {{.Node}}:{{.Port}} maxconn 400 weight 100 check inter 2s fall 2{{end}}{{end}}
```

**Comment by djenriquez** [comment]
@sethvarg

Very important note, according to the docs this is executed via an "iterable" element, but it does not work with a `string[]`. Consul-template returns: 
```
wrong type for value; expected []interface {}; got []string
```

So, doing a `split` against a string doesn't work. 

Also I tried your example above and that returns:
```
executing "" at <containsAll>: wrong number of args for containsAll: want 2 got 1
```

The only thing I got to work was using parseJSON as you're using in the [tests](https://github.com/hashicorp/consul-template/pull/817/files#diff-06ab79688609b98eb28ddf3ab5207e1bR590). This is fine since we can store our value in Consul as a JSON and have it pulled and parsed, but the documentation seems to be lacking on clarity here unless I'm doing something wrong.

**Comment by djenriquez** [comment]
@sethvargo 

Very important note, according to the docs this is executed via an "iterable" element, but it does not work with a `string[]`. Consul-template returns: 
```
wrong type for value; expected []interface {}; got []string
```

So, doing a `split` against a string doesn't work. 

Also I tried your example above and that returns:
```
executing "" at <containsAll>: wrong number of args for containsAll: want 2 got 1
```

The only thing I got to work was using parseJSON as you're using in the [tests](https://github.com/hashicorp/consul-template/pull/817/files#diff-06ab79688609b98eb28ddf3ab5207e1bR590). This is fine since we can store our value in Consul as a JSON and have it pulled and parsed, but the documentation seems to be lacking on clarity here unless I'm doing something wrong.
