### ISSUE TITLE
configuration parameter "error_on_missing_key" not available via cli

### ISSUE THREAD

**Issue by romonopoly** [hashicorp/consul-template#1047]
Would it be possible to allow "error_on_missing_key" to be configured for a template via command line call?

**Comment by sethvargo** [comment]
Hi @romonopoly 

Thank you for opening an issue. That option is template specific. The only template options we permit on the command line are the source file, destination file, and command. All other arguments must be in the `template` stanza in a configuration file.

**Comment by romonopoly** [comment]
Hi @sethvargo,

Thank you for a quick response.

I'm using the once mode as follows:
`consul-template -once -template "$configFile.ctmpl:$configFile"`
where the variable $configFile changes.

Is there a way to use "error_on_missing_key" with my use case, without generating a new config file for every invocation of consul-template?

**Comment by romonopoly** [comment]
Hi @sethvargo,

Is it possible to reopen this issue based on my comment above?

**Comment by sethvargo** [comment]
HI @romonopoly 

No, this is not possible.

**Comment by romonopoly** [comment]
Hi @sethvargo, could you provide a more professional response?

Something along the lines of: "using -once is not a fully supported feature and is intended only for testing"
Or: "I'm very busy and don't have time to examine this at the moment"
Or: "Please create a PR if you'd like this functionality"
Etc.

**Comment by sethvargo** [comment]
Hi @romonopoly 

I apologize if you think my response was unprofessional. I have answered your question multiple times, and I'm not sure how I can make it more clear. 

The `error_on_missing_key` key is a template-specific option and therefore must be in the template-specific configuration stanza in a configuration file. The CLI is a one-dimension (key=value). Since it's possible to specify multiple templates to one Consul Template process, there's no way to represent these template-specific options without a configuration file.

For example, let's say I have two templates - how would I specify the first should be error_on_missing_key, but they second should not? There are also many other template-specific options like the delimiter to use, file permissions for the destination template, whether to create destination directories, etc. None of those values can be specified on the command line because they are template-specific. 

It's not mathematically possible to map a multi-dimensional array into a single string. This is what I mean when I say "this is not possible". It's not possible. There is no pull request to open. There is no limiting time factor. The limiting factor is mathematics.

**Comment by romonopoly** [comment]
Hi @sethvargo,

I apologize for my misunderstanding of your previous comments, thank you for the clarification.

**Comment by aclowkey** [comment]
+1
I'm using `consul-template -once` to generate configuration. If there are missing keys, it will just be invalid configuration. It would be great if the command could fail in such case.

**Comment by jsok** [comment]
Could the `-template` option be extended to support template-specific options?

e.g. the current usage is `-template in:out:cmd`, so potentially becomes `-template in:out:[opts:]cmd`

This can be kept backwards compatible too with some parsing logic.

## Examples

Dangling `:` after options to indicate it's an option not a command:

```
consul-template -template "in.tpl:out.txt:error_on_missing_key=true:"
```

Supplying both options and command:

```
consul-template -template "/tmp/nginx.ctmpl:/var/nginx/nginx.conf:error_on_missing_key=true,perms=0600:nginx -s reload"
```
