### ISSUE TITLE
CT exec mode and SIGHUP

### ISSUE THREAD

**Issue by daohoangson** [hashicorp/consul-template#1058]
### Consul Template version
consul-template v0.19.4 (68b1da2)

### Configuration

```hcl
log_level="debug"

consul {
  retry {
    enabled = true
    attempts = 0
    backoff = "250ms"
    max_backoff = "1m"
  }
}

exec {
  reload_signal = "SIGHUP"
}

wait {
  min = "5s"
  max = "10s"
}
```

```liquid
# irrelevant
```

### Command

```shell
consul-template -config /path/to/consul-template.hcl -consul-addr host:port -exec command -template /path/to/template.ctmpl:/path/to/output
```

When I try sending `SIGHUP` to CT, it seems to kill the `exec` process instead of forwarding the signal. Is this the expected behavior? According to the doc, CT will reload its configuration etc. but it doesn't say anything specifically about child processes. It makes sense to kill the process but I want to be sure. Some confirmation from the dev would be great.

Thank you.

**Comment by pearkes** [comment]
It should forward the signal to the exec process, as detailed in the [exec mode docs](https://github.com/hashicorp/consul-template#exec-mode).

I'd wager to say that the process receiving the signal may be killing the process on `SIGHUP`. Please refer to those docs and feel free to comment back and we can re-open if you're not seeing the expected behavior still, as it may be a bug.
