### ISSUE TITLE
Default prefix for keys and secrets in templates

### ISSUE THREAD

**Issue by j-vizcaino** [hashicorp/consul-template#1063]
Is there anything that allows keys/secrets keynames to be automatically prefixed?

Use case is storing multiple versions of config values in consul, scoped in different subdirs. Version is determined beforehand, and in order to avoid tight coupling between template version and parameter version, I would like to add the prefix externally.

### Example

In the config:

```
key_prefix = "/v1/myapp/"
```

In the template:

```
{{ key "foo" }} # pulls /v1/myapp/foo
```

**Comment by slackpad** [comment]
Hi @j-vizcaino we don't have something like this for now, but you can use something like this to specify the version in one spot:

```
{{ $version := "v1" }}
{{ key (printf "%s/my-key" $version) }}
```

It's not super elegant (you could define a helper fn or pull the version from an environment variable via something like `(env "VERSION_PREFIX")`), but it's flexible for any use case. We talked about this internally a bit and figured people would want more complex functionality than a single prefix for all keys, so this seems like the best approach since Go templates can basically support any type of use case.

**Comment by j-vizcaino** [comment]
Hi @slackpad, thanks for the pointer. Someone at work actually pointed me towards the same solution but I find it quite cumbersome since all the keys need to be rescoped manually. This implies the template writer has to be aware of this version scoping.
I had a quick look at the code and it did not seem that complicated to implement: add a prefix in the Template struct and adapt the keyFuncs helpers. Is this something you guys are totally against or could a PR considered reasonable?

**Comment by slackpad** [comment]
We talked it over internally and thought that since consul-template can pull from Consul and Vault (does the prefix apply there too?), and that people would potentially want to use some top-level keys and some versioned keys in the same template, that it probably wasn't worth adding as a first-class feature at this time.

**Comment by j-vizcaino** [comment]
Ok, thank you for the explanation.
Regarding prefix, I was thinking into different prefixes for consul and vault (each defaulting to an empty string).
Usage of toplevel keys vs. prefixed could be solved using a simple convention: keys with leading `/` (absolute path) do not inherit from prefix, others would. This change would be reasonable since, defaulting to an empty prefix, `foo/bar` would target the same key as `/foo/bar`.
