### ISSUE TITLE
Integrate OpenCensus for tags, stats, and tracing

### ISSUE THREAD

**Issue by guidoiaquinti** [hashicorp/consul-template#1078]
Would you be interested in a PR to integrate [OpenCensus](https://github.com/census-instrumentation/opencensus-go) in `consul-template`?

My goal is to increase visibility around application performance and behavior monitoring data.

I have a first (draft) implementation to natively expose some simple stats:
```
➜  ~ curl -s localhost:9999/metrics | grep build_info
# HELP consul_template_build_info A metric with a constant '1' value labeled by revision and version from which consul-template was built.
# TYPE consul_template_build_info gauge
consul_template_build_info{gitcommit="",version="0.19.5.dev"} 1
```

**Comment by findkim** [comment]
Hi @guidoiaquinti, I wanted to let you know that we have targeted monitoring for the [0.26.0](https://github.com/hashicorp/consul-template/milestone/18) release 🎉. Thank you for everyone who had 👍 this enhancement and for your patience.

OpenCensus would be a good solution for metrics and monitoring and a late thank you for the offer to submit a PR! However with such a gap from when this issue was first opened to now, I can go ahead and start working on this instead of requesting you to dig 1 year in history for your draft.

With the time that has passed, the future of OpenCensus has moved to [OpenTelemetry](https://github.com/open-telemetry/opentelemetry-go) and it is now in beta. There are several other tickets requesting for monitoring, namely statsd/dogstatsd https://github.com/hashicorp/consul-template/issues/826 and prometheus https://github.com/hashicorp/consul-template/issues/1338, which OpenTelemetry at its current state supports. My plan is to first add support for metrics to Consul Template, and then tracing can be added at another time.

We will try to keep the version of OpenTelemetry up to date as GA is released. Please do let flag if there are any particular feature that you need specifically from OpenCensus that is not supported by OpenTelemetry or is targeted for its GA release.

**Comment by guidoiaquinti** [comment]
Awesome news, thank you @findkim ! 🎉
