### ISSUE TITLE
[FEATURE] Vault Transit support

### ISSUE THREAD

**Issue by danlsgiga** [hashicorp/consul-template#1166]
It would be really nice to have support for `Vault Transit` encryption so we can manage secrets directly in git and consul-template would only decrypt it using the Transit endpoint at runtime.

It would also provide a performance boost on the Vault servers for static secrets since consul-template won't need to watch for changes.

IMO, it would be a game changing feature!

**Comment by thevilledev** [comment]
Echoing what was stated in #1871 since this is quite an old issue. consul-template nowadays has a built-in [secret template function](https://github.com/hashicorp/consul-template/blob/main/docs/templating-language.md#secret) which enables a generic read/write interface to any Vault backend. This includes the `transit` backend, so any GET/POST call towards the backend can already be done with consul-template.

@danlsgiga does this match what you were looking for?

**Comment by danlsgiga** [comment]
Yeah, since this is a really old issue I'm considering my use case at the time and it does solve it.
closing!
