### ISSUE TITLE
error reading deleted vault KVv2 secrets

### ISSUE THREAD

**Issue by dbresson** [hashicorp/consul-template#1198]
The following commit changed "secret" to error out on a missing key instead of returning an empty value. This broke the behavior of "with secret" but the README.md was never updated.

https://github.com/hashicorp/consul-template/commit/085f0cf98b838e7d885a935a59654bafb883a03c

**Comment by eikenb** [comment]
Hey @dbresson, thanks for reporting this issue.

**Comment by eikenb** [comment]
Also relevant: Absent Vault fields render as "<no value>" #972

**Comment by eikenb** [comment]
The interesting thing about #972 is that it comes after https://github.com/hashicorp/consul-template/commit/085f0cf98b838e7d885a935a59654bafb883a03c .. so the change you reference come before the feature was added to have the secret keys return errors instead of "<no value>".

Maybe https://github.com/hashicorp/consul-template/commit/085f0cf98b838e7d885a935a59654bafb883a03c just makes it error when the secret itself doesn't exist, where the feature added in #972 was for the case of keys on that secret?

I think I'll have to run a quick test to be sure.

**Comment by eikenb** [comment]
@dbresson Could you describe better the situation where you saw the problem? I'm testing this and the documentation seems to match the behavior.

So with a secret set in vaule...
```
vault kv put secret/foo pass=bar
```
With this template...
```
$ cat template.tmpl
{{ with secret "secret/foo" }}{{ .Data.data.wrong }}{{ end }}
````
And this config...
```
$ cat config.hcl
template {
    source = "template.tmpl"
    error_on_missing_key = true
}
```
If I just render the template, I get the "<no value>" entry...
```
$ consul-template -template template.tmpl -once -dry
> 
<no value>
```
If I use the config with error_on_missing_key set I get an error...
```
$ consul-template -config config.hcl -once -dry
2019/08/13 20:54:06.501016 [ERR] (cli) template.tmpl: execute: template: :1:38: executing "" at <.Data.data.wrong>: map has no entry for key "wrong"
```

The the `<no value>` wasn't quoted correctly for the markdown and is hidden, so the README just has `""`. But that is all I can seem to find wrong. I'll push a fix for that in a second.

**Comment by dbresson** [comment]
Now delete secret/foo and try again.

**Comment by eikenb** [comment]
After deleting the key I get the same (error) result for both.

```
$ consul-template -template template.tmpl -once -dry
2019/08/13 22:30:48.592159 [ERR] (cli) template.tmpl: execute: template: :1:38: executing "" at <.Data.data.wrong>: nil pointer evaluating interface {}.wrong
$ consul-template -config config.hcl -once -dry
2019/08/13 22:30:57.403744 [ERR] (cli) template.tmpl: execute: template: :1:38: executing "" at <.Data.data.wrong>: nil pointer evaluating interface {}.wrong
```

Note that this only happens if you create then delete the key. If you just never create the key you just get retries while it waits/retries to read the key. You bet this in both cases if they key never existed.

Before the change you call out did it returned `<no value>` or "" (empty string) when it found a deleted key like this?

Do you think the solution is to update the docs to call out that after deleting a key you will get an error for it if you try to access it as a 'deleted' version of it still exists (or some such)?

Thanks.

**Comment by eikenb** [comment]
Is that the error you saw? It is not the error in the from the commit (the "no secret exists.." one) and it kills the consul-template process.

This smells more like a bug than a documentation issue. It shouldn't spit out an error like this, it should retry like it does when there is no value.

**Comment by eikenb** [comment]
@dbresson I'm going to assume that was the same error as you directed me to how to get it. I'm going to put together a PR that fixes that issue today. Thanks.

**Comment by eikenb** [comment]
Ok.. not today. Decided I wanted to talk to the Vault people to sanity check my solution and I think I missed them for today.

**Comment by eikenb** [comment]
@dbresson The PR up and (after a few reworks) is ready. I'll merge it once reviewed.

https://github.com/hashicorp/consul-template/pull/1260
