### ISSUE TITLE
[Question][Feature] Execute command after service disappear from services in consul

### ISSUE THREAD

**Issue by apolegoshko** [hashicorp/consul-template#1212]
Is it any workaround of calling plugin one more time when service disappear from consul ?

I have such setup.
When service appears in consul, consul-template render template (range over all services, execute some command in plugin - works as expected).

I want to ask if it is possible to execute command in plugin just with other flag, when service disappear from consul ?

For example, i have external service, which responsible for range of ip addresses, when service appear in consul plugin goes to external service, receiving the ip and rendering template. When service disappear from consul i want to send command with the same plugin but with other flags to external service that now this ip is free.

Thanks

**Comment by sodabrew** [comment]
When the rendered template changes you can execute a command. This is typically used to tell a program to reload a generated config file.

Your program can use the new config and figure out what changed since the last config was loaded and take appropriate actions.

There is not difference between something-added and something-removed -- all consul-template knows is that the consul index was updated, which triggers template rendering, and if the resulting template output changed, which triggers the external command execution.

**Comment by apolegoshko** [comment]
Hi @sodabrew The idea is to send different command, when content added, and content removed. If there is no any ideas, we can simple close this issue. Thanks!

**Comment by sodabrew** [comment]
There isn’t a way to do this in consul-template directly, but you can use the template output to drive your own code that diffs the before-and-after templates to generate such commands.

**Comment by eikenb** [comment]
Thanks for the question @apolegoshko and thanks for stepping in and helping out @sodabrew.

As @sodabrew pointed out what you want is possible, even if not super straight forward and it seemed to (mostly) satisfy you. As the question aspect of this issue seemed more prominent, I'm going to classify it that way and call it done.

@apolegoshko .. if you'd like to request the feature, please re-submit. Also please note that for questions we do have more dedicated resources for help with the community support resources.

Community portal: https://discuss.hashicorp.com/c/consul
Other resources: https://www.consul.io/community.html

Thanks.
