### ISSUE TITLE
All PKI certs are regenerated on reload signal

### ISSUE THREAD

**Issue by cagriy** [hashicorp/consul-template#1259]
consul-template re-requests all vault PKI backend based certificates upon receiving reload signal.

**How to recreate:**
1 - Bring up a vault server (v1.2.1 used) instance using -dev option
2 - Create a test PKI backend as described in vault documentation (https://www.vaultproject.io/docs/secrets/pki/index.html) add generate_lease=true while creating PKI role
3 - Create following template file
```
{{ with secret "pki/issue/example-dot-com" "common_name=foo.example.com" }}
{{ .Data.certificate }}{{ end }}
```
4 - Run consul-template (v1.20.0 used for testing) using
```
consul-template -template "./temp.ctmpl:/tmp/cert.crt"
```
5 - Note md5sum of /tmp/cert.crt and consul-template PID number
6 - Execute kill -HUP consul_template_PID
7 - Re-check md5sum of /tmp/cert.crt

**Background:**
This behaviour becomes an issue while using short lived consul tokens created by vault consul backend. If consul token is renewed frequently, this results in consul_template reloading itself frequently. In turn certs keep getting renewed and applications using these certs (such as nginx) will also require reloading.

**Comment by eikenb** [comment]
Hey @cagriy, thanks for the report.

I've been digging into PKI a bit due to a regression and remembered this issue (which I put off as I hadn't learned about vault's PKI backend yet).

In your description of how to reproduce it you send a HUP to consul template. Sending a HUP reloads all configuration and templates by design. It is in the documentation under [Running and Process Lifecycle](https://github.com/hashicorp/consul-template#running-and-process-lifecycle). So this seems to be the correct behavior in this case.

However in your background section you describe it differently, saying... "If consul token is renewed frequently, this results in consul_template reloading itself frequently." Is there another way to reproduce this that would more closely mimic this?

**Comment by cagriy** [comment]
Hi @eikenb , thanks for your answer.

In our setup, there is a requirement to have short living consul and vault tokens. Hence a process renews them every hour and reloads consul-template to start using these new tokens. 

I understand a reload naturally results in reloading all configuration.

Our challenge is that, upon config reload, consul-template asks for vault PKI backend for new certs, although existing certs have sufficient lease on them and valid certificates are already stored on the disk at the specified destinations.

Expectation here is for consul-template to only request certificates if they are due to expire (or at half-life etc) upon a reload rather than renewing them on every reload. Unlike other configuration and secrets that stay static upon a reload, renewal of certs further trigger other consul-template events (such as reload of nginx server) which is undesirable. In the end, although we have perfectly valid certificates and no other configuration changes we keep restarting whole set of services purely because consul-template is reloaded.

**Comment by lneva-fastly** [comment]
@cagriy We just solved a very similar challenge using [vault-agent](https://www.vaultproject.io/docs/agent/).  Vault-agent takes care of authenticating with Vault and retrieving a token.  It renews the token until it expires and then re-authenticates to get a new one.

Point consul-template at vault-agent and give consul-template _no_ vault token.  vault-agent will proxy requests to Vault, adding the vault-token it has acquired.  consul-template never knows when a new token has been acquired and never cares.  No need to reload templates and re-issue certs.

Newer versions of vault-agent and consul-template support unix domain sockets, so you can lock things down so that only consul-template has access to this token-free proxy to Vault.

Prior to this, we had a shell script doing Vault approle authentication and feeding the token to consul-template.  Definitely not optimal!

I feel like vault-agent + consul-template is an unsung power-combo that should be better documented.  It makes perfect sense to me now that consul-template does not itself support various Vault authentication mechanisms, since vault-agent is built for that purpose.  I only figured this out after reading a comment in an issue here that mentioned it in passing.  Hashicorp folks, perhaps vault-agent should be mentioned in the consul-template README?

**Comment by teeuwes** [comment]
Any news on this issue?  I'm facing a similar problem, in that any time consul-template is reloaded or restarted, it generates new pki certificates, regardless of ttl/validity of the existing certs.  Is this by design?

**Comment by eikenb** [comment]
@cagriy @teeuwes 

The request/goal is to get the PKI certificates to persist over reload if they don't need to be renewed yet.

The reason it currently doesn't work that way is that on reload CT stops all the watching code, reloads the config, then (re)starts all the watches. Watches have 1 way they are started, as if they were started from scratch. No state is preserved for anything and everything must re-check/fetch their data (or certs in this case). You can see it in the main loop where it does the signal handling (the runner is what watches things)...

https://github.com/hashicorp/consul-template/blob/aaef8436535f162f696b066f32dc33caa5c0ea0e/cli.go#L131-L133

To prevent this would require state to be preserved over the reload as they can't request it from the servers without triggering a new PKI. This comes down to either saving/restoring the state somehow or not stopping the runner in the first place (and how to merge in config changes in this case). I'm not 100% on how feasible either of these options are at the moment.

**Comment by imriz** [comment]
There's another option, to provide a command in the template config which will return the TTL (or better yet, a UTC timestamp) the first time a template is considered.

**Comment by eikenb** [comment]
Hey @imriz, 

Do you mean a command that will check to see if the destination file exists and, if so, load it and return the TTL of the cert contained?

**Comment by imriz** [comment]
I say leave the implementation details to the user, and just define the API, but yes, this is a plausible use case

**Comment by jsmilani** [comment]
I would find it unexpected to change the current behavior. We find it very useful to use the HUP signal to regenerate all templates. Our solution (which won't work for everyone) was to skip using the token entirely and run consul-client on every machine but only listen on 127.0.0.1 and let the default consul token have read access to all the required resources consul-template needs.

I do see a missing feature for when you need to use a consul token you still need to solve refreshing the consul token without reloading configs. The same problem was solved for vault tokens using the `vault_agent_token_file: Template will periodically stat the file and update the token if it has changed.` Consul tokens could have a similar `consul_token_file` argument that loads the new token without regenerating templates. It would make sense to have feature parity with the vault configs.

**Comment by eikenb** [comment]
Just FYI, I'm going to review this and try to come up with a solution for 0.28.0. Please comment if you have any other thoughts on how to best approach it. I plan on working on 0.28.0 next (probably starting next week).

**Comment by eikenb** [comment]
Related vault issue: https://github.com/hashicorp/vault/issues/11030

**Comment by eikenb** [comment]
FYI, had to release 0.28.0 early due to a customer ask. So this is now marked for 0.29.0. Note that I'm working on addressing this via a new template function that will have certain restrictions but will use the certificate in the rendered template as a local cache for the cert info to check validity/expiration.

**Comment by eikenb** [comment]
I just merged a new template-fuction 'pkiCert' that only returns a PKI certificate (PEM encoded string) and uses the rendered template file as a sort of cache for it, checking for template destination for a file on startup/reload and, if it finds one, loads the cert from there. If that certificate is still good it will use it, if it is expired or not there it will fetch a new one from  Vault.

It is intended to skip anything other than the certificate. It will skip CAs and chain certificates if present along with any other text. It will return the first parse-able PKI certificate it finds in that file.

Please file a new issue if there is some use case this will miss. Thanks!
