### ISSUE TITLE
Float value truncated in rendered output

### ISSUE THREAD

**Issue by ppai-plivo** [hashicorp/consul-template#1391]
### Consul Template version

```sh
./consul-template -v
 v0.25.0 ()
```
Tested with commit c831cdcce03bfdcaf509590326eb2b465ebff1bf (master at the time of filing this issue)

### Steps to reproduce

```sh
$ cat in.tpl
{{ "1.0" | parseFloat }}
{{ "1.1" | parseFloat }}

$ ./consul-template -template "in.tpl:out.txt" -once

$ cat out.txt
1
1.1
```

### Expected output

```
1.0
1.1
```

### Actual output

```
1
1.1
```

### fmt

I understand that `fmt.*` family of functions exhibit similar behaviour. 

```go
func main() {
	f := 1.1
	fmt.Println(f)  // prints 1.1
	f = 1.0
	fmt.Println(f). // prints 1
}
```

### Usecase

I'm using consul-template to render a config file (in TOML format).

```toml
[SomeConfig]
transaction_sampling = {{ key "transaction_sampling" || parseFloat }}
```

is rendered into

```toml
transaction_sampling = 1
```

when value of key in consul is `1.0`

A go program then loads the rendered config file and unmarshals the config into following struct:

```go
type Config struct {
    TransactionSampling float64 `toml:"transaction_sampling"`
}
```

I'm using https://github.com/pelletier/go-toml for unmarshaling toml into a struct. And since the value is rendered as `1` and not `1.0`, the unmarshaling into `float64` [fails](https://github.com/pelletier/go-toml/pull/390). It is not unreasonable for `go-toml` library to fail this implicit conversion.

**Comment by eikenb** [comment]
Hey @ppai-plivo, thanks for reporting.

The issue here seems to be the templating library itself. The parseFloat function returns a floating point value, but the template engine renders it out without the float part. I suspect that the template library uses fmt when rendering the value out as text.

There is a workaround. If you pipe it to another function it is passed as a floating point, so with the built-in printf you can format it as you like. Eg.

```sh
$ cat > in.tmpl << EOF
{{ "1.0" | parseFloat | printf "%.1f" }}
{{ "1.1" | parseFloat | printf "%.1f" }}
EOF

$ consul-template -template "in.tmpl:out" -exec "cat out" -once
1.0       
1.1
```

I can't do anything about the default template output, but this should work for your case. Do you think a mention of using printf like this would be a good addition to the parseFloat documentation?

**Comment by ppai-plivo** [comment]
Thank you for the quick reply 👍 

> There is a workaround. If you pipe it to another function it is passed as a floating point, so with the built-in printf you can format it as you like

Why didn't I think of that! Thank you. That works for me.

> Do you think a mention of using printf like this would be a good addition to the parseFloat documentation?

Sure does. I sent a PR here: https://github.com/hashicorp/consul-template/pull/1392
