### ISSUE TITLE
select service nodes by multiple tags

### ISSUE THREAD

**Issue by piavlo** [hashicorp/consul-template#144]
currently it's only possible to select nodes from a service by one tag only
using multiple tags would be very helpful

**Comment by sethvargo** [comment]
Hi @piavlo,

If I understand correctly (and please correct me if I'm mis-understanding this request), you would like to do something like the following:

```liquid
{{range "release.production.webapp@east-aws"}}
```

where this would search for the tags "release" and "production" for the "webapp" service. 

I'm :-1: on this for a few reasons, so please let me explain why.

The first reason is compounding. Does "release.production.webapp" mean "release" **AND** "production" or "release" **OR** "production". No matter which way we choose to define the rule, there will always be a use case for the opposite... I think this will be really confusing to users, and the API is not immediately apparent.

Secondly, I think it is a bit cleaner to just duplicate config blocks as needed:

```liquid
{{range "release.webapp"}}
{{.Name}}
{{end}}
{{range "production.webapp"}}
{{.Name}}
{{end}}
```

For complex config blocks, you can use [nested template configurations](http://golang.org/pkg/text/template/) to share them among all the queries.

Lastly, to the best of my knowledge and looking through the docs, Consul's API does not permit us to filter by multiple tags (probably for the same reason I listed above about compound operators). As such, we would need to watch all services and filter on the client side in order to poll Consul for changes and filter by tag... That is already possible via the `byTag` interface. In other words, you can accomplish a multi-tag listing like this:

```liquid
{{range $tag, $services := service "webapp" | byTag}}
{{if $tag eq "release" or $tag eq "production"}}
{{range $services}}{{.Name}}{{end}}
{{end}}
{{end}}
```

In this example, you have one config block that is guarded against running if the tag is not a particular value or set of values.
