### ISSUE TITLE
Basic auth and other consul api options

### ISSUE THREAD

**Issue by re5et** [hashicorp/consul-template#147]
We would like to use basic auth.  It seems like currently only certain options are allowed to be passed to the consul api, and this is the second time I have come acrossed one we wanted to use.

**Comment by sethvargo** [comment]
Hey @re5et,

Thank you for opening an issue. Because Go is a statically-typed language, we need to mirror the options we feel are most important in the Consul Template configuration. To keep the original scope of the problem smaller, we chose to pick the configuration options that satisfied the most number of users. Since most users run Consul behind a VPN and not on the public Internet, they usually do not have basic auth/SSL enabled on their installations.

We will definitely get this fixed for the next release, but it probably won't be as fast as we added SSL support :smile:. Would you like to take a try at a Pull Request for this functionality? I would be more than happy to review it!

**Comment by re5et** [comment]
Thanks.  We will get a pr together.  Thanks again for the prompt https fix!

**Comment by rotatingJazz** [comment]
You can also use `nginx` as a reverse proxy and enable `basic auth` there (and ssl).

**Comment by sethvargo** [comment]
@re5et someone already beat you to it: https://github.com/hashicorp/consul-template/pull/148 :smile:

**Comment by sethvargo** [comment]
Added in 9e819cc

**Comment by re5et** [comment]
@sethvargo a minion ;) @bion
