### ISSUE TITLE
ignore runtime premeption signals, SIGURG  (was: receiving signal "urgent I/O condition")

### ISSUE THREAD

**Issue by MikeVL** [hashicorp/consul-template#1486]
### Consul Template version

v0.26.0

### Configuration

```hcl
consul {
  address = "consul.service.consul:8500"
}

log_level = "info"

vault {
  address = "http://active.vault.service.consul:8200"
}

exec {
  command = "consul/uwsgi.sh"
  splay = "30s"

  env {
    custom = [
      "DJANGO_CONF=consul/django.conf.py",
    ]
  }

  reload_signal = "SIGHUP"
  kill_signal = "SIGTERM"
}

template {
  source = "consul/django.conf.ctmpl"
  destination = "consul/django.conf.py"
  error_on_missing_key = true
  backup = true

  wait {
    min = "5s"
  }
}
```

### Command

```shell
# consul/uwsgi.sh

if [[ -f "${DJANGO_CONF}.bak" ]]; then
    diff --color=always ${DJANGO_CONF}.bak ${DJANGO_CONF} > /dev/stdout
fi

exec uwsgi --ini uwsgi.ini ${UWSGI_EXTRA_ARGS}
```

### Nomad console log

<img width="522" alt="Снимок экрана 2021-06-17 в 17 15 52" src="https://user-images.githubusercontent.com/118285/122414341-bcd0b700-cf8f-11eb-8ea6-cdc9e5f32d72.png">

**Comment by eikenb** [comment]
Hey @MikeVL, thanks for taking the time to file an issue.

I'm pretty sure you are seeing this due to changes in the Go runtime. I'm going to convert this to a feature request to have consul-template handle the SIGURG signals and ignore them.

Some context on the Go runtime change.

The proposal and ticket for the change.
- https://github.com/golang/go/issues/24543
- https://go.googlesource.com/proposal/+/master/design/24543-non-cooperative-preemption.md

A ticket to have the runtime mask the SIGURG signals from the rutime.
- https://github.com/golang/go/issues/37942
