### ISSUE TITLE
[Req] Simple encryption support

### ISSUE THREAD

**Issue by rotatingJazz** [hashicorp/consul-template#151]
> On the `template` section, add 2 new options: `decryption_key`, `decryption_method`. Example `beefefbeaede`, `xor`. On the template add a modifier `| decrypt` so that specific keys can be decrypted using the above settings.

Benefit:
All the settings under one tree with a single read key for all the clients.

(Btw, I'm not offering PRs not because of disrespect, but because I don't know Golang yet  :small_orange_diamond: )

**Comment by sethvargo** [comment]
Hi @rotatingJazz,

If I understand the use case correctly, you want to store encrypted keys in Consul and they decrypt them when reading from the template? 

I apologize, but I think this is a bit outside the scope of what Consul Template should be doing for the user. Additionally, I think storing encrypted keys in Consul is not a recommended pathway at this time. 

Might I recommend securing your Consul instance and then using access tokens to read the data? You can read more about the ACL model [here](http://www.consul.io/docs/internals/acl.html). For more information on Consul security, please see [here](http://www.consul.io/docs/internals/security.html) and for encryption, see [here](http://www.consul.io/docs/agent/encryption.html). Lastly, you will want to serve the API over HTTPs (which Consul Template 1.0.0 will support).

I feel bad because I rejected two feature requests from you today, but I really do think this is outside the scope of what Consul Template should be doing :frowning:.

**Comment by sean-** [comment]
@rotatingJazz Have you looked at crypt yet?  It doesn't hook in to consul-template directly, but it's one way of handling the storage of sensitive data in consul.

https://xordataexchange.github.io/crypt/

**Comment by rotatingJazz** [comment]
@sethvargo @sean- 

Thank you for your replies!

The use case I'm thinking that template-side value decryption could simplify the ACL setup is in multi-tenancy, or not-fully-trusted servers of some agents.

One global read key for everyone and the sensitive information can get decrypted on the "client" side for each client. Suppose I'm distributing 100 sensitive config files to 100 clients. Instead of making 100 ACL, I only make one global read. Even if a client's server gets hacked, there is no information leakage.

I have seen `crypt`, I think it's very nice, but tbh, I like `consul-template`'s workflow :+1:

**Comment by sean-** [comment]
Got it.  Well, in that case use your template's post-render exec call to call a wrapper shell script that rewrites the template one more time to do a decrypt, then execute your watch program.  Not seamless, but probably the workaround you need.

**Comment by rotatingJazz** [comment]
@sean- Nice workaround, thanks! :beers:
