### ISSUE TITLE
pkiCert: CA chain field missing

### ISSUE THREAD

**Issue by iul1an** [hashicorp/consul-template#1602]
https://github.com/hashicorp/consul-template/pull/1591 allows us to get `Cert`, `Key` and `CA` but there's no `ca_chain` key in the `.Data` object.
Could you please add it?

The template that I'm using:
```
{{- with pkiCert "pki/issue/foo" "common_name=bar.tld" "alt_names=localhost" "ip_sans=127.0.0.1" "ttl=720h"}}
{{.Data.Cert }}
{{.Data.ca_chain }}
{{.Data.Key }}
{{ end }}
```
The error that I'm getting:
```
[ERROR] template.server: template server error: error="/root/test.pem.tpl: execute: template: :16:8: executing \"\" at <.Data.ca_chain>: can't evaluate field ca_chain in type dependency.PemEncoded"

```

I'm using the latest version of Consul Template / Vault Agent.

**Comment by eikenb** [comment]
Hey @iul1an, thanks for taking the time to file this!

The chain isn't included as it didn't have an obvious way to differentiate the chain certs from CA. They are all marked as CAs, which is how it differentiates between the Cert and the CA when reading in the file. We need to be able to tell which Cert is which based on the info contained in the Certificate alone (as we are reading them unlabeled from a file).

I didn't know of a good way to differentiate and didn't have time to research it more when adding the CA and private key. Also, unlike the private key, you can query for the CA and Chain separately, without generating a new PKI Cert. 
I think [this is the API](https://www.vaultproject.io/api-docs/secret/pki#read-default-issuer-certificate-chain) for that and it should work with the normal `secret` template function. Though they'd need to be in a separate file so as not to confuse the pkiCert's file scan for the CA.

So my suggestion is to read the CA/Chain out separately if you can. Otherwise if you know of a good method to differentiate between the CA and the chain certs please let me know. Thanks.

**Comment by iul1an** [comment]
Hi @eikenb,

Thank you for your work on this project and for the quick reply :)
I need all the certs and the private key in the same file and I was able to use this template as a workaround:
```
{{- with pkiCert "pki/issue/foo" "common_name=bar.tld" "alt_names=localhost" "ip_sans=127.0.0.1" "ttl=720h"}}
{{ .Data.Key -}}
{{ .Data.Cert -}}
{{- end -}}
{{- with secret "pki/cert/ca_chain" -}}
{{ .Data.ca_chain }}
{{- end }}
```
I ran the Vault agent multiple times and It didn't prematurely renew the cert.

**Comment by eikenb** [comment]
Oh yeah.. that would totally work. Great idea @iul1an!

It works because you were using the CA in the ca_chain it didn't matter if it confused the CA setting being read back from the file.  I'm going to add this to the documentation as the recommended way to deal with this. Thank you for the question and solution, I'm sure this will come up again.
