### ISSUE TITLE
consul template when servers of upstream not exist getting error for nginx

### ISSUE THREAD

**Issue by Zgrrl** [hashicorp/consul-template#1648]
Hi,
I'm using nginx and consul template for a while and working fine. When I delete records of the one service from consul config, nginx getting error like "no servers are inside upstream in" and nginx doesn't work until restart. Probably I need to add "service exist condition" to upstream part , but I could'nt find how to do.

thanks your support,

### Configuration

```hcl
services {
  id = "svc1"
  name = "service1"
  address = "1.1.1.1"
  port = 8080
}

services {
  id = "svc2"
  name = "service1"
  address = "1.1.1.2"
  port = 8081
  check = {
    http = "http://1.1.1.1/Service1.asmx"
    method = "GET"
    interval = "10s"
    timeout = "1s"
  }
}
```
I'm using this consul template from [https://stackoverflow.com/questions/71486612/how-can-i-set-automaticly-registered-services-on-nginx-config-using-consul-templ]

```consul template
{{- /*

  Upstream template

  This template is used to the upstream configuration for the service.
  It takes an array of service health objects as input and returns the template
  as a string.

*/ -}}
{{- define "upstream-template" -}}
### Upstream configuration for {{ . }}
upstream {{ . }} {
  zone upstream_{{ . }} 128k;
  {{ range service . "any" }}
  # Instance: {{ printf "%s-%s" .ID .Name }}

  {{- /* Mark the backend as down if the health status is critical */ -}}
  {{- $is_down := sprig_ternary " down" "" (eq .Status "critical") }}
  server {{ printf "%s:%d%s" .Address .Port $is_down -}};
  {{ end }}
}
{{ end -}}

{{- /* Obtain list of services from the catalog */ -}}
{{- $servicesList := services -}}

{{- /* Generate upstream configurations for each logical service */ -}}
{{- range $servicesList -}}
  {{- if and (ne .Name "consul") (.Name | contains "sidecar" | not) -}}
    {{- executeTemplate "upstream-template" .Name -}}
  {{- end -}}
{{- end -}}

server {
  listen                443 ssl;
  server_name           domainname.com.tr;
  proxy_set_header      X-Forwarded-Port 443;
  ssl_certificate       /etc/nginx/tls/..crt;
  ssl_certificate_key   /etc/nginx/tls/..key;

  access_log /etc/nginx/log/gw/https/access.log;
  error_log /etc/nginx/log/gw/https/error.log;

  location / {
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-Server $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $http_host;
    proxy_pass https://domainanother;
  }

  {{- /*
    Generate the location blocks for each logical service.
    Ignore the 'consul' service itself, and any sidecar services.
  */ -}}
  {{ range $servicesList -}}
  {{- if and (ne .Name "consul") (.Name | contains "sidecar" | not) }}
  location ^~ /{{ .Name | sprig_title }}.asmx {
    proxy_pass http://{{ .Name }};
    proxy_redirect off;
  }
  {{ end -}}
  {{- end }}
}
'''

**Comment by eikenb** [comment]
Hey @Zgrrl, sorry for the delay getting back to you. Got busy.



Reviewing the original post along with your new information (a big help) I'm going to take a stab at what I think might work.

You are on the right track with that stack overflow question and only need to put the test in the right place. I *think* that place is in the main template, doing the check before exec'ing the upstream-template.

In this bit from your original post (below) you already have a couple checks on the .Name, but they'd both pass on an empty value. Maybe try adding another test to that if-and line. I'd first try `(ne .Name "")` or `(ne . nil)` to see if those eliminate the issue. 

```go
{{- range $servicesList -}}
  {{- if and (ne .Name "consul") (.Name | contains "sidecar" | not) -}}
    {{- executeTemplate "upstream-template" .Name -}}
  {{- end -}}
{{- end -}}
```

If this doesn't help (and you haven't figured it out otherwise) I'll probably need to do more to reproduce it which I don't have time for right now.

Good luck and let me know. Thanks.

**Comment by Zgrrl** [comment]
Hi @eikenb ,
I focused to wrong part :)It's work. 
Thanks a lot.
Have a nice day
