### ISSUE TITLE
Support for Hiera based config data

### ISSUE THREAD

**Issue by wwalker** [hashicorp/consul-template#165]
Support for Hiera based config data.

In our environment, we currently use Hiera ( https://docs.puppetlabs.com/hiera/1/ ) with puppet to build configs.  For a couple of reasons, we want to replace that.  consul-template works great except that it only looks at one key for a given template key.

In our environment, we actually have many lookups for a single key...  Each user would vary.  I envision two config files, a file with hiera control config variable values (facter_data.conf for this doc), and hiera lookup order listing (hierarchy.conf in this doc):

hierarchy.conf:
```
    - "env-application/%{env}-%{application}"
    - "instance/%{instance}"
    - "application/%{application}"
    - "env/%{env}"
    - common
```

facter_data.conf:
```
env=qa
instance=B
application=proxyserver
```

In this scenario, for each call to key() in the template, we would perform up to 5 calls to consul (client.KV.Get()), stopping at the first successful fetch.  For example we would check the following keys until one returned a value:
 
```
env-application/qa-proxyserver/nginx_listen_port
instance/B/nginx_listen_port
application/proxyserver/nginx_listen_port
env/qa/nginx_listen_port
common/nginx_listen_port
```

Obviously this adds complexity and impacts performance, so it would be an optional feature.  I've just begun using Go and have looked into the consul-template code.  It appears to have been designed with enough abstraction to plug this in relatively simply, however I'm unsure where to wedge it in.  Should there be another directory that is a
sibling to dependency?

**Comment by sethvargo** [comment]
Hi @wwalker,

If I understand your request correctly (and please do let me know if I'm misinterpreting it), you would like a way to "fallback" to another key when a parent key does not return data?

This is already possible in. For example:

```liquid
{{ $env_app := key "env-application/qa-proxyserver/nginx_listen_port" }}
{{ $instance := key "instance/B/nginx_listen_port" }}
{{ $app := key "application/proxyserver/nginx_listen_port" }}
{{ $env := key "env/qa/nginx_listen_port" }}
{{ $common := key "common/nginx_listen_port" }}
{{ or $env_app (or $instance (or $app (or $env $common))) }}
```

As you've said there are definitely performance implications here, since you are creating 5 view polls for each key you want to lookup.

Since this is already possible, I am going to close out this issue. If I misunderstood what you were asking, please let me know and I can re-open it.

**Comment by wwalker** [comment]
in our setup, there are 23 of these in each case, the templates would be the size of an encyclopaedia...

I will be doing this anyway, even if it won't go back in the primary product.  If it was going to go into the product, how would you do it (least invasive method would make keeping up with your changes and fixes easier).

I see I will need to do it two places, once that gets called by keyFunc() and another that gets called by in wait.go.

**Comment by sethvargo** [comment]
Hi @wwalker 

I would recommend making another top-level func in the keymap that just delegates to n `key` calls and aggregates the results appropriately. Then add that top-level func to the keymap.

**Comment by sethvargo** [comment]
Hi @wwalker 

I just wanted to follow up and make sure you understand how Consul Template works internally and the ramifications of the approach you are taking.

Each time you create a dependency (like `service`, `key`, `ls`, `datacenter`, etc.), Consul Template creates a "view" under the hood and long-polls the Consul server for changes. Consul itself implements edge triggering using blocking HTTP requests. So, in effect, Consul Template queries Consul in the background and waits for a response. Consul holds that request internally until data changes or some event fires, at which point it returns the data to the view, which populates the watcher, which ultimately reaches the runner. The runner then intelligently decides which templates need to be updated/re-rendered.

This is important to understand, because you could effectively DDoS yourself rather easily. Even with just 23 services, you are making 5 queries per key, resulting in 115 **individual HTTP requests** hitting Consul _per Consul Template instance_. Obviously Consul performs well at scale, but having just 10 machines will request Consul to serve and block 1,150 HTTP requests. As your infrastructure grows, I do not think your current implementation will scale.

I would like to recommend an alternative approach - keep Consul's KV structure flat (i.e. a single key), and write an external service that "merges" the hiera data and puts it into Consul's KV store. This is what other users in similar situations have been successful with.
