### ISSUE TITLE
`consul-template` appears to do O(n^2) work to render N services

### ISSUE THREAD

**Issue by nelhage** [hashicorp/consul-template#168]
I have a consul-template instance watching many (~70) services in a single template. There is no nesting of loops, just a huge number of  `{{range service [foo]}}{{end}}` loops.

At startup, I see the template get rendered many, many times, with the number of missing dependencies counting down by one each time:

```
root@intfe1:~# grep 'missing' /pay/tmp/consul-template.out
2015/01/26 23:48:32 [INFO] (runner) was missing 68 dependencies
2015/01/26 23:48:33 [INFO] (runner) was missing 67 dependencies
2015/01/26 23:48:35 [INFO] (runner) was missing 66 dependencies
2015/01/26 23:48:35 [INFO] (runner) was missing 65 dependencies
2015/01/26 23:48:35 [INFO] (runner) was missing 64 dependencies
2015/01/26 23:48:35 [INFO] (runner) was missing 63 dependencies
2015/01/26 23:48:35 [INFO] (runner) was missing 62 dependencies
2015/01/26 23:48:36 [INFO] (runner) was missing 61 dependencies
2015/01/26 23:48:36 [INFO] (runner) was missing 60 dependencies
2015/01/26 23:48:36 [INFO] (runner) was missing 59 dependencies
2015/01/26 23:48:36 [INFO] (runner) was missing 58 dependencies
2015/01/26 23:48:36 [INFO] (runner) was missing 57 dependencies
2015/01/26 23:48:36 [INFO] (runner) was missing 56 dependencies
2015/01/26 23:48:36 [INFO] (runner) was missing 55 dependencies
2015/01/26 23:48:36 [INFO] (runner) was missing 54 dependencies
2015/01/26 23:48:36 [INFO] (runner) was missing 53 dependencies
2015/01/26 23:48:36 [INFO] (runner) was missing 52 dependencies
…
```

In between each "missing" line, I see log lines for each missing service, resulting in a total of O(n^2) log lines.

The problem seems to be that, when we attach missing dependencies, we immediately loop and retry, without waiting for the data to actually arrive. Due to whatever quirk of the go scheduler or runtime or my environment, we get exactly one new record showing up each loop, resulting in this n^2 behavior.

**Comment by sethvargo** [comment]
@nelhage can you please share your entire Consul Template configuration file and the output of the command with `CONSUL_TEMPALTE_LOG=debug` set please?

**Comment by nelhage** [comment]
I'd rather not share the entire configuration file publicly if we can avoid it, since it contains a lot of information about my internal network, but it's a haproxy config file containing many stanzas almost-identical to


```
frontend graphite
        bind 127.0.0.1:10023
        # cookie  SERVERID rewrite
        default_backend graphite

backend graphite
        balance roundrobin
{{range service "graphite-web" }}
        server {{.Node }} {{.Address}}:{{.Port}} {{/*
*/}} check inter 10000 rise 4 fall 2{{else}}
        # WARNING: found no servers for service graphite
{{end}}

        # Backup servers, which apply if everything appears down. We're trying
        # to prevent fat fingers bringing all the servers soft-down by accident{{/*
*/}}{{range service "graphite-web" "any" }}
        server {{.Node }}-backup {{.Address}}:{{.Port}} backup{{/*
*/}}{{end}}

        option httpchk GET /healthcheck
        http-check disable-on-404
        http-check send-state
```
I've placed a redacted log file here: https://nelhage.com/paste/2015-01-26f_4wMIKw-consul-template.redact

Note that `consul-template` seems to have hung at some point – it's still running as a I type this, but not producing output.

**Comment by nelhage** [comment]
Oh, the log file is 1.5M, just as a heads-up.

**Comment by nelhage** [comment]
Ah, I was reading the code wrong. I think https://github.com/hashicorp/consul-template/blob/9a58c1fd61f9a10e8b49b9899df3a04658c1abea/runner.go#L132-L157 is the problem – we're only consuming one new piece of data at a time before retrying. Wrapping that `select` in a loop that drains all available channels would resolve the issue, I suspect…

**Comment by sethvargo** [comment]
@nelhage I'm not sure that will work with the new n-pass evaluation. It's also [already in a loop](https://github.com/hashicorp/consul-template/blob/9a58c1fd61f9a10e8b49b9899df3a04658c1abea/runner.go#L112) unless I'm misunderstanding what you're saying.

**Comment by nelhage** [comment]
Yeah, sorry, I was misreading the code. My current theory is that the [runner event loop](https://github.com/hashicorp/consul-template/blob/9a58c1fd61f9a10e8b49b9899df3a04658c1abea/runner.go#L132-L157) needs some kind of batching – we should drain all available events (or up to `t` milliseconds of events), before we re-run the runner.

**Comment by sethvargo** [comment]
@nelhage so I can better prioritize this work - what's the memory usage and CPU usage during startup? Is Consul Template usable for you in this current state?

Since you aren't using the n-pass evaluation, you can also try 0.5.1 which used a different way that may be more performant for you (until we can fix this).

**Comment by nelhage** [comment]
So, I noticed this issue while trying to debug the fact that running `consul-template` reliably destabilizes our consul cluster. So it's not usable for us right now, but I'm not actually sure if this bug is the culprit or not. I'll give 0.5.1 a try.

Also, as a strawman, I threw together https://github.com/hashicorp/consul-template/issues/168#issuecomment-71570889, which fixes this bug. It's probably not suitable for merge as-is, but I wanted to make sure I understood the issue properly.

**Comment by sethvargo** [comment]
Hrm. I'm not sure waiting an arbitrary amount of time is the best solution for this. I think in [this block](https://github.com/hashicorp/consul-template/blob/9a58c1fd61f9a10e8b49b9899df3a04658c1abea/runner.go#L237-L245) we need to wait for data to come back or timeout somehow.

I think you uncovered an interesting bug in the sense that, if you reference a non-existent key or service, I believe none of your templates will ever render and will go into this massive cycle. I think we are going to need to diff the missing dependencies with the watched dependencies and iff that is non-zero to loop back. I have a solution in my head that looks like https://github.com/hashicorp/consul-template/pull/169, but I have not had a chance to test it further. There's also [this block](https://github.com/hashicorp/consul-template/blob/9a58c1fd61f9a10e8b49b9899df3a04658c1abea/runner.go#L247-L252), which is going to cause the same problem, just different log output. If you could compile and run the code in that PR and grab me your debug log again, that would be helpful.

**Comment by nelhage** [comment]
https://nelhage.com/paste/2015-01-27RcvNqHse-consul-template.mine.redact.out is the logs from mine.

Waiting for data in that block would definitely solve the problem, although you'd potentially starve out other templates that already had data. In practice I think this should mostly only happen at startup, and also fetching data is fast, so it's likely fine.

I don't love the arbitrary timeout in mine, but it does have the advantage of making explicit the tradeoff between updating too aggressively (which the current code does), and the danger of livelock – if you always waited until there's no new data, you risk never making progress as long as *any* service is changing.

**Comment by sethvargo** [comment]
@nelhage true, but that's what the quiescence timers are for

**Comment by gdhbashton** [comment]
Just popping in to say 'me too' from #171 - many of the data points in my tests did NOT yet have data (I haven't written the data import script yet).

**Comment by sethvargo** [comment]
I talked with @ryanuber and we are fairly certain that, even if we can fix the "high-CPU and rendering templates all the time" component, you are still going to destabilize your Consul cluster at that load. @gdhbashton yours will be even worst at 31 config files + 1200 keys. The upcoming changes to the Consul API will help improve performance, but you are effectively DDoSing yourself during Consul Template runs, and unfortunately there is not much Consul Template can do on that front until Consul has more efficient watcher APIs in place.

@nelhage I do not think the batching solution is going to work because it opens too many edge cases and also breaks the per-template quiescence (since that requires the invocation of Run() and the attempted rendering of the template).

I don't know the best way to do this, but we basically need to read and receive _all_ data from the watcher's DataCh and then call Run. So if two views both return data, we need to read until it blocks, but I don't know the best way to read an entire channel in go.

Pinging @armon and @mitchellh to see if they have any better ideas.

**Comment by nelhage** [comment]
``` go
outer: for {
  select {
    case evt := <- ch:
      // do a thing
    default:
      break outer
  }
}
```

is probably the best way to drain a channel. Just sticking that inside the `		case data := <-r.watcher.DataCh:` might help a lot, although I haven't tested it right now.

**Comment by mitchellh** [comment]
Given I don't have the full context of this issue (my disclaimer): I agree with @ryanuber and @sethvargo in that the main limitation here appears to be that there isn't an efficient way to watch that many keys in one go. We have plans to fix this in Consul itself, but not in the short term.

We're not saying this issue is invalid, its just that we're not equipped with the tools in the short term to fix this in a meaningful way. I think the best solution will probably be to keep this open and tag it against another issue in Consul to watch for a fix there (probably months away, at least) and come back to it so we don't forget it.

**Comment by nelhage** [comment]
So, there are two bugs I'm hitting, and I think they should be considered separately.

This issue is specifically about the fact that `consul-template` does O(n^2) work to generate a template with `n` `{service}` function calls. That applies even with `consul-template -once` and has nothing to do with consul watches. My patch is a proof-of-concept fix for that issue, even if it may introduce others.

There's a separate issue, which is that consul's watches can't scale to my desired use case. I've talked to @armon separately about that issue, and we're all in agreement that there are no short-term fixes planned for that one. However, I think we should track that as a separate issue (potentially by opening an issue on consul itself), and I'd recommend we keep this thread for the discussion of the n^2 behavior, which is purely in `consul-template` and could be fixed today.

**Comment by mitchellh** [comment]
@nelhage Ah, got it. I just reread through a lot of this and I agree that point 1 is an issue. I think given our current architecture it may be hard to quickly fix (though your PoC certainly helps). I'll take a deeper look and talk to @sethvargo and see if we can come up with something.

**Comment by gdhbashton** [comment]
I've restructured our usage of Consul so that each of the source JSON config files is being stored as a binary object in a single key. It's disappointing that I can no longer easily access any single knob or switch in the app config in a single simple `curl` however I'm happy that we can continue to use Consul Template.

I look forward to seeing any future re-architecture which could address this use case.
