### ISSUE TITLE
Consider adding a 'prefix' option

### ISSUE THREAD

**Issue by gozer** [hashicorp/consul-template#174]
I've been using confd for a while now, and as much as I'd like to use consul-template as well, or as a replacement, there is one missing feature I'd really like to see in consul-template.

confd lets me write very generic templates that don't need to fully qualify consul keys, and instead, rely on a startup --prefix option to root key lookups into a specific consul subtree (i.e. /production, /staging, /dev, etc)

This is a very elegant solution, allowing me to have a single place to specify what environment my application is running.

I believe this would be a simple, yet powereful new feature for consul-template.

**Comment by sethvargo** [comment]
Hi @gozer 

This is already possible using the `env` key. Unlike confd, you are not restricted to a command line flag and the template is much more explicit to the reader. You can read the `{{env "PREFIX"}}` key and concatenate that onto any keys you wish. You can choose whichever environment variable you want and you can even use more than one. So instead of `PREFIX`, you could use `ENVIRONMENT` or something more semantic.

```bash
ENVIRONMENT=staging consul-template -template "..."
```

**Comment by jonathanmorley** [comment]
Can we get the -prefix option semantics from envconsul, such that we can specify multiple and the namespaces get merged.

**Comment by arabkin** [comment]
If this is still interesting for someone, I've implemented **-prefix** option in consul-templates the following way:
```{{ key ( print (env "KV_PREFIX") "/runtime/jvm-args")}}```
where KV_PREFIX is environment variable with some prefix and then generic "path"
So this way, if KV_PREFIX="/staging/app-name" the key will be "/staging/app-name/runtime/jvm-args".
