### ISSUE TITLE
Support getting a single random item from an array

### ISSUE THREAD

**Issue by blakeblackshear** [hashicorp/consul-template#179]
I am using consul-template to set the database in the config for my app servers. I just need to get one of the healthy nodes with the rethinkdb service.  Right now I have come up with this:
```go
  {{ range  $i, $e := service "rethinkdb" }}
    {{ if eq $i 0 }}
    "db": {
      "host": "{{$e.Address}}",
      "port": "{{$e.Port}}"
    }
    {{ end }}
  {{ end }}
```

However, this sets up app the app servers to connect to the same database instance. It would be nice if I could randomly select a node within a template. Something similar to this:

```go
  {{ random  service "rethinkdb" }}
    "db": {
      "host": "{{.Address}}",
      "port": "{{.Port}}"
    }
  {{ end }}
```

Is there a better way to handle this use case?

**Comment by sethvargo** [comment]
Hi @blakeblackshear 

Thank you for opening an issue. I believe you are looking for the `index` function:

```text
index
	Returns the result of indexing its first argument by the
	following arguments. Thus "index x 1 2 3" is, in Go syntax,
	x[1][2][3]. Each indexed item must be a map, slice, or array.
```

Untested, but I'm pretty sure you want to do something like:

```go
{{with index (service "rethinkdb") 0}}
  "db": {
    "host": "{{.Address}}",
    "port": "{{.Port}}"
  }
{{end}}
```

I think "randomly" selecting a node would cause a world of hurt and confusion. For more information on the template functions from Go, please see [the documentation](http://golang.org/pkg/text/template/).

**Comment by bryanlarsen** [comment]
Random is a simple common form of load balancing.   Consul's DNS API uses it.  I would love to have a random function in consul-template.

**Comment by sethvargo** [comment]
@bryanlarsen it's not feasible to use "random" data in Consul Template - you would be re-rendering the template each time data changes, causing other commands to fire. Do you really want your application to restart every few seconds because the "random" database server changed? There would be a ton of false-positive re-renders simply because the random function returned a different service.

Given a template like:

```liquid
{{with service "db" | random}}
[db]
  address={{.Address}}
  port={{.Port}}
{{end}}
```

The first time CT might choose the third service in the list. But on the second pass, it may choose the second template in the list, which would re-render the template and re-run any associated commands with the template. It would become exponentially more complex if you wanted to use nested queries within a random block:

```liquid
{{with service "db" | random}}
[db]
  address={{key .Address}}
{{end}}
```

Consul Template would be unable to provide a reasonable graph and you would effectively be looping indefinitely waiting for Consul to return consistent data, but it never will because of the element of randomness introduced.

Unless you are running in `-once` mode, a `random` function would introduce significantly higher CPU usage and many, many template re-renders and command executions.

I am sorry, but this is not something I plan to support in Consul Template. The existing template functions provide ways to access individual elements in a services list.

**Comment by blakeblackshear** [comment]
Makes sense. I thought this would be a challenge to support. Thanks for
pointing me to the index function.
