### ISSUE TITLE
Service regexp overly strict?

### ISSUE THREAD

**Issue by ebroder** [hashicorp/consul-template#187]
It looks like someone registered services in our consul cluster whose names contain colons. consul seems to be completely fine with this, but consul-template rejects lookups for these services with "invalid health service dependency format" (since it seems to expect service names to match `/((?P<name>[[:word:]\-/_]+))/`

I'm pretty sure service names with colons are a mistake, and we'll probably change our config, but it seems like consul-template shouldn't be less flexible than consul itself?

**Comment by ryanuber** [comment]
@ebroder I think this is definitely a mistake on Consul's side. Consul has a DNS interface, where colons will certainly not work for service lookups. We should definitely not support registering service names with colons. I've opened a new issue on Consul to track this at hashicorp/consul#683. Let's track the upstream issue there.

Thanks for reporting this!

**Comment by ryanuber** [comment]
After a discussion with @mitchellh, we decided to continue allowing special characters in service names and tags, and emit warnings into the log rather than outright rejecting the config. We went down this route to preserve backwards compatibility with existing clusters. I still think allowing these kinds of service names is a bad idea, so maybe we relax the regexp if/when there is demand for it. @sethvargo any thoughts? @ebroder let us know if you were able to change your config to use proper names.

**Comment by sethvargo** [comment]
@ryanuber I would be in favor of making the error message more friendly with an explanation of _why_ that's not a valid service tag (basically your comment from last night in fewer words). We cannot expand the regex because we use the colon to mean special things in CT land.

**Comment by ebroder** [comment]
I've fixed the service names on my end so this is not currently a pressing problem for my use case

**Comment by ebroder** [comment]
FYI, this came up again today (someone mistakenly forgot to run a service name through printf, and it ended up getting registered with a  `%v`). As long as consul allows users to register these services, it's really unfortunate that consul-template completely barfs on them
