### ISSUE TITLE
`consul-template -once` will hang forever if the rendered template has not changed

### ISSUE THREAD

**Issue by nelhage** [hashicorp/consul-template#188]
Simple reproducer:

```console
$ echo HELLO > file.template && rm -f file
$ CONSUL_TEMPLATE_LOG=debug consul-template -template file.template:file -once
2015/02/10 03:30:30 [INFO] (runner) creating new runner (dry: false, once: true)
2015/02/10 03:30:30 [INFO] (runner) creating consul/api client
2015/02/10 03:30:30 [INFO] (runner) creating Watcher
2015/02/10 03:30:30 [INFO] (runner) starting
2015/02/10 03:30:30 [DEBUG] (runner) running initial templates
2015/02/10 03:30:30 [INFO] (runner) running
2015/02/10 03:30:30 [DEBUG] (runner) checking template file.template
2015/02/10 03:30:30 [DEBUG] (runner) checking ctemplate &{Source:file.template Destination:file Command:}
2015/02/10 03:30:30 [DEBUG] (runner) rendered: true
2015/02/10 03:30:30 [INFO] (runner) updating dependencies
2015/02/10 03:30:30 [INFO] (runner) once mode and all templates rendered
2015/02/10 03:30:30 [INFO] (runner) stopping
2015/02/10 03:30:30 [INFO] (watcher) stopping all views
$ CONSUL_TEMPLATE_LOG=debug consul-template -template file.template:file -once
2015/02/10 03:30:31 [INFO] (runner) creating new runner (dry: false, once: true)
2015/02/10 03:30:31 [INFO] (runner) creating consul/api client
2015/02/10 03:30:31 [INFO] (runner) creating Watcher
2015/02/10 03:30:31 [INFO] (runner) starting
2015/02/10 03:30:31 [DEBUG] (runner) running initial templates
2015/02/10 03:30:31 [INFO] (runner) running
2015/02/10 03:30:31 [DEBUG] (runner) checking template file.template
2015/02/10 03:30:31 [DEBUG] (runner) checking ctemplate &{Source:file.template Destination:file Command:}
2015/02/10 03:30:31 [DEBUG] (runner) rendered: false
2015/02/10 03:30:31 [INFO] (runner) updating dependencies
[HANG]
```

The problem seems to be that `r.render` returns `false` because there is nothing to do, and so we don't populate `r.renderedTemplates`, and so `allTemplatesRendered` returns false. So we hang forever waiting for new data, which will never arrive, because we didn't actually take out any watches.

**Comment by sethvargo** [comment]
@nelhage hrm... this is the expected behavior, but I can also see how it is confusing.

The API promise for `-once` (in English) is:

```
Each dependency will receive data from Consul exactly one time and the template will be rendered exactly one time.
```

Given that promise, it seems appropriate that CT would hang given the second clause is not satisfied (the template was not rendered once). However... all of the watchers are stopped at that point (because they have all received data exactly one time in order for the render to even occur), so things are effectively deadlocked at this point.

I am not sure what the desired UX is here. I think we need to change the API promise for `-once` to be:

```
Each dependency will receive data from Consul exactly one time
```

and remove the clause around the template being rendered.

On a similar note, if you give CT a dependency that does not exist in Consul, `-once` will hang until Consul returns data for that dependency. We have found that this is the desired behavior, because users want to watch services/keys that do not yet exist in Consul. I'm just not sure if the same UX should apply here.

What would you expect CT to do:

- Just not render the template and exist
- Start new watchers until the template is rendered once

**Comment by nelhage** [comment]
I would expect CT to not update the template on disk and exit. In my mind, it *did* render the template (into an in-memory buffer), and then just short-circuited actually writing it out and running the commands, which is why I expected it to have satisfied

> Each dependency will receive data from Consul exactly one time and the template will be rendered exactly one time

I'm using `consul-template -once` out of a cron job to work around the fact that consul's watches can't handle my workload (as discussed elsewhere). So the `render the template in-memory, observe nothing needs to be done, and exit` is exactly the semantics I want – taking out watches would make it unusable for me.
