### ISSUE TITLE
0.37.3 did not get marked as latest release

### ISSUE THREAD

**Issue by chenrui333** [hashicorp/consul-template#1900]
👋 it looks like 0.37.3 did not get marked as latest release, raise this issue for some awareness. Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/166830

cc @divyaac

**Comment by thevilledev** [comment]
A new tag was added, but both release and release branch are missing. No changelog entries either.

**Comment by tgross** [comment]
Thanks for the heads up folks, I can see this pulled in https://github.com/hashicorp/consul-template/commit/453869d2d1aa8f7f2f44031c5fdece141285d2f3 which I was planning on getting out for a release shortly anyways. I'll circle back with folks internally and get that release officially done.

**Comment by tgross** [comment]
Because we didn't do the release officially and the tag can't be mutated without some unfortunate side-effects for Nomad and Vault, which use consul-template as a Go module, we're going to release everything in the 0.37.3 tag as 0.37.4 instead. I've got the pre-release work running over in https://github.com/hashicorp/consul-template/pull/1903 and that'll likely ship out tomorrow. Sorry for the confusion, folks.

**Comment by tgross** [comment]
Done! https://github.com/hashicorp/consul-template/releases/tag/v0.37.4 Thanks folks for bringing this to our attention!

**Comment by chenrui333** [comment]
Thanks @tgross!
