### ISSUE TITLE
write initial template if no consul cluster found

### ISSUE THREAD

**Issue by JeanMertz** [hashicorp/consul-template#208]
I have an nginx config that I'm writing out using consul-template.

On initial startup, there is no consul cluster available, but I still want the template to be written as soon as possible. I have several if/else statements, so if no data is found on consul, the else block will be parsed.

Is it possible to have Consul write the template on startup, even if no cluster is found (yet)?

**Comment by ryanuber** [comment]
Hi @JeanMertz, thanks for opening an issue for this.

Template rendering is currently not possible before consul is available. I think trying to force-render a template any earlier will be problematic. Let me explain:

* Rendering templates and starting services early with empty configuration sounds likely to be a problem more often than desired functionality in most cases. Currently consul-template returns an error when consul is unavailable, and since consul is our source of truth for consul-template, I think the right thing to do is to stop with an error when we can't reach it.

* When consul-template successfully renders a template, it then places a new watch on the required "dependencies" using consul's API to watch for changes. Since the initial template render contained no data (because consul was unavailable at the time), no watches could possibly be created, leaving the template in a sort of dead-locked state where it can never be updated. To work around this issue would likely be more complex than it is worth to implement, and would be rather costly during the time period where Consul was unavailable (due to repeated template re-renders).

I think a more viable approach would be to install a static configuration file outside of consul-template if you are expecting a situation where consul may be unavailable for some time, and simply replace it when consul-template starts. Although it could introduce a trivial amount of duplication, the initial state of the config would be much more obvious and easy to reason about in your codebase.

**Comment by sethvargo** [comment]
Hi @JeanMertz,

As @ryanuber said, this is not something that is currently possible and somewhat goes against the purpose of Consul Template. Similar to what Ryan recommended, here is my recommendation:

1. Have Chef write out a default nginx configuration (`/etc/nginx/nginx.conf`)
2. Have Chef also write out a consul templated nginx configuration (`/etc/consul-templates/nginx.conf.ctmpl`)
3. Run Consul Template like this:

    ```shell
    consul-template -consul 1.2.3.4 -template "/etc/consul-templates/nginx.conf.ctmpl:/tmp/nginx.conf:test_and_replace_nginx_conf()"
    ```

  where `test_and_replace_nginx_conf` is a function like:

    ```shell
    if [[/etc/nginx/sbin/nginx -t -c /tmp/nginx.conf]]; then
      mv /tmp/nginx.conf /etc/nginx/nginx.conf
      service nginx reload
    fi
    ```

  So, the general idea is to render the nginx configuration out of band, and then use the command argument to test the new config and then move it into place if the config check passes.

I'm making the assumption you're still using Chef, but I think you get the general idea :smile:.

**Comment by JeanMertz** [comment]
@ryanuber, @sethvargo thank you very much for your explanations. I thought as much that it wouldn't fit the model for consul template (and this kind of service-based template parsing in general).

Thank you for the example Seth. That looks very interesting. So instead of writing the config directly, you check its validity first. Interesting idea. Not sure yet if it makes sense in our situation, given that the non-rendered nginx config isn't that useful anyway (it renders a maintenance page).

The goal was indeed to remove some duplication, but by extracting the template-based part of the config to separate files, and including them in the main config, I've managed to keep the duplication to a minimum.

Thanks for the help!

*Also, you've assumed wrong :stuck_out_tongue_winking_eye:. With awesome tools from Hashicorp (Consul, Packer, Vagrant, and maybe in the near future Terraform), Docker and CoreOS, I've had less and less use for a full provisioning tool like Chef. Sad to see it go, but removing the overhead has been a net positive :+1:*
