### ISSUE TITLE
Add helper function to implement for loop like range operations

### ISSUE THREAD

**Issue by discordianfish** [hashicorp/consul-template#221]
Correct me if I'm wrong, but there is no way to some template fragment n times. To fix that, I propose to introduce some helper function to work with 'range' like this:

```
{{ range to(23) }}
- Number {{ . }}
{{ end }}
```

`to` could return an channel and start a gorouting sending the next number to that channel.

**Comment by sethvargo** [comment]
Hi @discordianfish 

Thank you for opening an issue. I am curious to hear your use case here. I wrote up a naive implementation of this, but I do not think Go's template language will be flexible enough to provide much usefulness here. For example, the following will work:

```liquid
{{range loop 3}}
{{.}}{{end}}
```

which will result in:

```text
0
1
2
```

However, this will not work:

```liquid
{{range loop 3}}
{{. + 1}}{{end}}
```

or any other mathematical operation or aggregation for that matter. What exactly are you trying to duplicate N times?

Looping N times is easy until the user wants to manipulate the resulting index, since Go's template language does not make that easy (or really even possible at this time). I am a bit hesitant to add this functionality because I think it will only satisfy a very tiny use case and could introduce confusion to users who want to manipulate the index. Does that make sense? I'm not saying "no", but I would like a little more information about your use case.

/cc @ryanuber @armon

**Comment by discordianfish** [comment]
@sethvargo Just out of curiosity, why don't the operators work?
My usecase is simple: I like to render a haproxy configuration with 12 stats endpoint (one per core to get stats for all processes, a haproxy limitation) like this:

```
{{range loop 12}}
listen stats0{{ . }} :80{{ . | printf "%02d" }}
  stats uri /
  stats auth admin:foobar23
  bind-process {{ . }}
  stats enable
{{end}
```

I think it's not uncommon to have sections that are repeated like this. But I'm open to alternatives :)

**Comment by sethvargo** [comment]
@discordianfish it's just one of the limits of Go's templating language unfortunately :frowning:
