### ISSUE TITLE
Disable the service before executing the "command"

### ISSUE THREAD

**Issue by sebest** [hashicorp/consul-template#223]
It would be useful that to ask consul template to disable the service before executing the command if the command is restarting the service in a non graceful way, and use the "check" feature to re-enable it when it is "up" again.

**Comment by ryanuber** [comment]
Hey @sebest, thanks for the suggestion! You can probably already get this functionality if the agent is running locally by using the `consul maint` command to enter service maintenance mode before restarting, and re-enable afterwards. There might be some way we can make this more integrated, so I'll tag this as an enhancement. Thanks!

**Comment by sethvargo** [comment]
Hi @sebest 

Thank you for opening an issue. Do you have any ideas on what that might look like? This would put a lot of decision-making responsibility in Consul Template's hands and I might prefer to leave these decisions to the user. For complex restarts or conditions, I usually recommend users deploy a shell script to invoke instead of calling the command directly inline. Does that make sense?

There's no guarantee that the service CT is restarting is managed/monitored by Consul either. This is why I think it would be best to defer this type of decision-making to a script.

**Comment by sebest** [comment]
Hello @sethvargo and @ryanuber, 

I think that the common use case for services that don't reload gracefully is:
1/ get a lock to make sure we upgrade one (or more) at a time
2/ remove the service from production to get no new request on it
3/ upgrade/restart the service
4/ put the service back in production
5/ release the lock

1 and 5 are handled by consul lock
2 and 4 are consul maint
3 is the command

I could do a wrapper to do this but i think that this pattern is generic and common enough to be built in consul-template.

One optional improvement on step 4 would be to wait for a successfull check to re-enable the service instead of re-enabling it right after the command.

**Comment by sielaq** [comment]
I don't get why you need this pattern in consul-template
 and how consul-template supposed to work with it,
but 
About this last part - step 4 improvement. I'm not sure if I understand it correctly. The thing you try to achieve is having a service which is healthy, before maintenance is really over (not just mark as over) ?
If yes then this supposed to be done from consul site.

**Comment by sebest** [comment]
@sielaq , for example if you have an HTTP app that has no "reload" feature but only start/stop , you want to make sure that the load balancer in front of it removes this server from its backend before stopping the HTTP app.

**Comment by sebest** [comment]
BTW, i know that i could do a wrapper script to do all of this, but i wanted to discuss if this pattern is common and generic enough to be built in or not.
The end goal is to have smooth rolling update with no downtime and lost connections.

About 4, i don't know the default behaviour of consul when a check is defined in the service: does it check that the check is ok before marking the server as healthy or does it mark it healthy by default and then check.

**Comment by sielaq** [comment]
@sebest about 4 - good question for consul guys, I suspect that default is "non-passing" thats why 
https://github.com/hashicorp/consul/issues/706  FR was created, to start checks with "passing" state.

regarding the rest of the stuff, 
>you want to make sure that the load balancer in front of it removes this server from its backend before stopping the HTTP app.

And how consul-template would know that you want to remove/stop  backend ? since consul-template is at the end of the chain of knowing it.
user <-> backend <-> consul <-> consul-template

We are using docker & registrator for that.
user <-> backend_on_docker <-> registrator <-> consul <-> consul-template
registartor register and de-register it for you

But what we are doing then - to have smoothly deregistering from consul, before it is killed - is a wrapper that TRAP SIGTERM / SIGINT signals inside container and put backend into maintenance mode in consul. You can also put this logic into your application. 

Might be that we are doing something wrong here :)

**Comment by sebest** [comment]
there are 2 consul-template:
- one on the loadbalancer (eg: haproxy) doing a "range ls myappp" to generate its backend file
- one on my app server, generating its config and restarting it when config is modified

So i put my app in maintenance before restarting it so the lb can drain the traffic to other app servers.
Sometimes you can't modify the code of the app, that's why i m doing a wrapper.

IMHO it should not be done inside the docker, but outside of it as a sidekick.

**Comment by sielaq** [comment]
ok got it, we use `envconsul` for that job (12factor app methodology).

the easiest way is to execute together with "service reload part of your consul-template":

```curl -X PUT "http://${consul}:8500/v1/agent/service/maintenance/${service_id}?enable=true"```
if you have UDP service: 
```curl -X PUT "http://${consul}:8500/v1/agent/service/maintenance/${service_id}:udp?enable=true"```
and put it back after reload is finish:
```curl -X PUT "http://${consul}:8500/v1/agent/service/maintenance/${service_id}?enable=false"```
if you have UDP service: 
```curl -X PUT "http://${consul}:8500/v1/agent/service/maintenance/${service_id}:udp?enable=false"```

You just need to know ServiceID which was used for registering - sometimes it might be tricky if you use docker and registrator - it could be tricky for consul-template to get it automatically as well.

But this could be possible - it might work. Lets wait for @sethvargo what he gonna say :)

**Comment by sethvargo** [comment]
Hi @sebest @sielaq,

I have spent a good amount of time thinking about this today, and I think the correct pathway is to document and encourage the use of [`consul maint`](https://consul.io/docs/commands/maint.html) for this particular use cases. In this way, the user will have the ultimate flexibility over the execution of the command without the need to add additional overheard, configuration options, or compatibility promises into Consul Template.

For example, consider a CT run for nginx like this:

```shell
$ consul-template -template "/tmp/nginx.ctmpl:/etc/nginx/nginx.conf:service nginx reload"
```

This would become:

```shell
$ consul-template -template "/tmp/nginx.ctmpl:/etc/nginx/nginx.conf:/scripts/consul/reload-nginx.sh"
```

And `/scripts/consul/reload-nginx.sh` could contain something like:

```shell
#!/bin/sh
set -e

consul maint -enable -reason "Consul Template changed" -service backend
service nginx reload
consul maint -disable -service backend
```

Due to the amount of customization the user will want to have over this "flow", I think this is the best path moving forward. For example, all of the following scripts are acceptable alternative approaches that could be required by a user:

```shell
// Sleep in between commands while the system is processing
consul maint -enable -reason "Consul Template changed" -service backend
sleep 5
service nginx reload
sleep 30
consul maint -disable -service backend
```

```shell
// Timeout the command after a certain number of seconds
// (unrealistic for this scenario, but possible for other types of
// services
consul maint -enable -reason "Consul Template changed" -service backend
service nginx reload & sleep 30; kill $!
consul maint -disable -service backend
```

```shell
// Put multiple systems into maintenance mode, changing the delay when they restart
consul maint -enable -reason "Consul Template changed" -service backend
consul maint -enable -reason "Consul Template changed" -service frontend
service nginx reload
consul maint -disable -service backend
sleep 10
consul maint -disable -service frontend
```

As you can see, there are quite a number of edge cases, and those are the ones I thought of off the top of my head. I'm sure users in the real world will come up with additional edge cases I haven't thought of. In short, it would be incredibly difficult to support all those edge cases as configuration options. The power of Consul Template comes from the ability to execute arbitrary commands and I think we should leverage that here.

Does that make sense?

**Comment by sielaq** [comment]
fair enough to me.

Small questions, you "encourage" to use consul binary instead of consul rest API,
is there any reason for that ? Do I need to install consul in every container now or both ways gonna be fully supported.

**Comment by sebest** [comment]
Make sense to me, as @sielaq is mentioning, i would be really interesting in a guide (or a chapter) in the documentation about your (hashicorp) recommended way to integrate all the consul tools in a docker environment. There are already a lot of blogs about this topic, but the having the opinion of hashicorp on that matter would be really interesting!
thanx.

**Comment by sethvargo** [comment]
Hey @sielaq 

I encouraged the use of `consul maint` and `consul lock` simply because it's easier for new users. As a power user, you have a deeper understanding of the Consul internals and the API, so you are welcome to utilize those HTTP calls directly. However, the "average" user may not have as much experience and therefore I would recommend the "easier" path. Make sense?

@sebest I will look into getting something like that published, but HashiCorp generally tries to remain tool agnostic as much as possible.

**Comment by sethvargo** [comment]
Hey @sebest 

As I said on the previous issue, I've updated the README in https://github.com/hashicorp/consul-template/commit/662e7d108f76abe643628ad2feb0c07a677b7830 to include more information and updated Consul's API client to read more of those environment variables.

I am going to look into getting a blog post put together, but in the meantime I found the following things which you might find interesting:

- https://tech.bellycard.com/blog/load-balancing-docker-containers-with-nginx-and-consul-template/
- https://github.com/foostan/consul-with-docker

The first is a blog post, and the second is a GitHub repo that demonstrates using Consul with Docker + CT.

I am willing to re-visit this in the future, but I am going to close this out for now :smile:.
