### ISSUE TITLE
About consul-template restart haproxy issue

### ISSUE THREAD

**Issue by lindane** [hashicorp/consul-template#236]
consul-template version 0.7.0、consul version 0.5.0、haproxy version 1.5.2

1.The first consul-template configuration with haproxy and start haproxy，Command is as follows：
consul-template -consul 192.168.2.71:8500 -template “/tmp/haproxy.ctmpl：/etc/haproxy/haproxy.cfg：service haproxy restart”

haproxy successful start
2.Stop haproxy，Command is as follows：
service haproxy stop
3.Does not change the configuration，Restart consul-template，Command is as follows：
consul-template -consul 192.168.2.71:8500 -template “/tmp/haproxy.ctmpl：/etc/haproxy/haproxy.cfg：service haproxy restart”

Haproxy Start unsuccessful，service haproxy restart Command does not take effect.Only modification consul-template template file /tmp/haproxy.ctmpl，To start haproxy.
4.Modify /tmp/haproxy.ctmpl file，Command is as follows：
vim /tmp/haproxy.ctmpl

Add or delete a row
5.Restart consul-template，Command is as follows：
consul-template -consul 192.168.2.71:8500 -template “/tmp/haproxy.ctmpl：/etc/haproxy/haproxy.cfg：service haproxy restart”

haproxy successful start

issue：The first consul-template using the template file can successfully start haproxy，Next stop haproxy and consul-template，consul-template Template file does not change，Restart the consul-template，This time service haproxy restart does not take effect.Must modify the consul-template template file，Add or delete a row，Haproxy restart to take effect.It is a bug or misconfigure?

**Comment by sethvargo** [comment]
Hi @lindane,

Thank you for opening an issue. Consul Template will only execute the given command if there are changes to the underlying template. This is the expected behavior. The command will only execute if the template was rendered, and the template only renders if there are changes. Does that make sense?

The reason adding/deleting a row from the haproxy config and restarting is that it _changes_ the template, which means a render takes place, which causes the command to fire.

Consul Template is _not_ a service manager like upstart or init.d. In this example, you should not use Consul Template to manage the entire lifecycle of your service. Instead, start your service with something like upstart, and then have Consul Template issue the `service haproxy reload` command when a template changes.

**Comment by lindane** [comment]
Thank you，I agree，haproxy start and stop should not be used to control the consul-template.
