### ISSUE TITLE
Documentation for use with Docker

### ISSUE THREAD

**Issue by HelloGrayson** [hashicorp/consul-template#25]
How would I go about running consul-template inside a container along side my python app, for example.

Use supervisor, or?

Thanks

**Comment by t5unamie** [comment]
This seems silly. Why can't supervisor run consul-template? Why do you need to enter the shell in order to beable to start this?

I have been playing with this for a few hours now and it works fine on my local. However the second I put it in a container it does not run as a deamon. It seems to only run once on start up.

**Comment by sebest** [comment]
@t5unamie running it with supervisor is what @mitchellh describes as "multi-process container".
BTW using supervisor should work.

A 3rd solution would be a solution similar to what does env-consul do: consul-template could act as a basic process supervisor.
