### ISSUE TITLE
RPM / DEB packages 

### ISSUE THREAD

**Issue by alex-leonhardt** [hashicorp/consul-template#256]
Hi,

It'd be great if it could be packaged as a RPM and/or DEB package as those are used by all major linux distros.

Alex

**Comment by sethvargo** [comment]
Hi @alex-leonhardt 

Thank you for opening an issue. As I said on https://github.com/hashicorp/consul/issues/871, this is not currently a top priority for us. Since these are static binaries (just a single file), the current installation process is very simple and scalable. If the requirements change in the future, this is definitely something we are willing to reconsider. Please let me know if you have any questions.

**Comment by strarsis** [comment]
Until then you can build it yourself:
https://github.com/llinder/deb-consul-template

**Comment by vyas-n** [comment]
Now that consul has official RPM & DEB packages, would this be reconsidered?

**Comment by eikenb** [comment]
Hey @vyas-n,

It seems possible. We are working to standardize our build processes and that might lead to supporting packaging for more than our core products. If you (or others) would like this looked into please open a new ticket. Thanks.

**Comment by vyas-n** [comment]
@eikenb,

That's great thanks!

By the way are the existing RPM & DEB package files located in a separate repository? I was looking at creating a PR for some changes to the stock SystemD config files, but couldn't find it in the consul repo: https://github.com/hashicorp/consul

**Comment by eikenb** [comment]
@vyas-n  .. I'm not 100% sure. We have a release team that works on the CI and release automation and I'd need to talk to them about it. If you re-file you can ask again there to help me remember to ask about it when I talk to them about package building in general. Thanks.
