### ISSUE TITLE
Vault section in config file being overwritten

### ISSUE THREAD

**Issue by ChrisAubuchon** [hashicorp/consul-template#271]
Using config:
```
consul = "127.0.0.1:8500"

vault {
        address = "https://localhost:8200"
        token = "<token>"
        ssl {
                enabled = true
                verify = false
        }
}

ssl {
        enabled = false
}
```

Running consul-template with:
```
consul-template -log-level=debug -config=<config_path>
```

Results in:
```
2015/04/30 18:58:28 [DEBUG] runner: final config (tokens suppressed):
{
  "path": "",
  "consul": "127.0.0.1:8500",
  "vault": {
    "address": "",
    "ssl": {
      "enabled": true,
      "verify": true,
      "cert": "",
      "ca_cert": ""
    }
  },
```

**Comment by ChrisAubuchon** [comment]
The merge at runner.go:392 seems to be where the Vault configuration is overwritten.

**Comment by mdelagralfo** [comment]
Yeah I think the problem is that anything defined in DefaultConfig() is overriding the contents of the config file.  For example I get the same result trying to set the SSL flag to true.  Using config:

```
ssl {
    enabled = true
}
```

Running consul-template with: 

```consul-template -config consul_template_config.hcl -log-level=debug -once```

Results in:

```
{
 ...
  "ssl": {
    "enabled": false,
    "verify": true,
    "cert": "",
    "ca_cert": ""
  },
  ...
```

To me, it looks like the defaults are treated as command-line arguments and take precedence over the config files.

**Comment by sethvargo** [comment]
The problem is that Go's default boolean value is `false`. So when creating a new config, we cannot differentiate between 'the user explicitly set this to false' and 'the user did not set this'. This makes default values effectively trinary. I have a good solution, I just haven't had time to implement it yet :smile:

**Comment by mdelagralfo** [comment]
Yeah I noticed the same challenges trying to get the CLI config right.  I may attempt a PR if I figure something out.  Right now it's impossible to get consul-template talking to Vault on another server without hacking the source.

**Comment by sethvargo** [comment]
@ChrisAubuchon @mdelagralfo ^

**Comment by kolis** [comment]
This is a pretty serious bug if I want to use the vault functionality, considering that the latest release version of consul-template does not include this fix. This means when I want to use consul-template I must build it myself, instead of just using the prebuild package.

When can we expect a new release package?
