### ISSUE TITLE
Question about haproxy support

### ISSUE THREAD

**Issue by looprock** [hashicorp/consul-template#277]
I'm looking for more information about consul-template and haproxy interaction. In your examples you have:

```text
$ consul-template \
  -consul my.consul.internal:6124 \
  -template "/tmp/nginx.ctmpl:/var/nginx/nginx.conf:service nginx restart" \
  -template "/tmp/redis.ctmpl:/var/redis/redis.conf:service redis restart" \
  -template "/tmp/haproxy.ctmpl:/var/haproxy/haproxy.conf"
```

You're restarting nginx and redis, but not haproxy; so it's great the new config is getting populated but how do you propose picking it up from the service side?  Thanks

**Comment by sethvargo** [comment]
Hi @looprock 

You can reload or restart haproxy depending on your needs. The reason there is no command there is because I don't feel like engaging the bikeshed of which reload command should be used. You can use whatever haproxy reload command best suits your needs. For complex setups, you can invoke a custom shell script.

**Comment by looprock** [comment]
Yep, makes sense, thanks for the input and help!
