### ISSUE TITLE
I don't understand how "wait" works.

### ISSUE THREAD

**Issue by darron** [hashicorp/consul-template#299]
It seems to me that if you have "wait" defined, that Consul Template should wait at least that long to write the template and run the command - but it doesn't seem that that's what's happening.

Using this configuration:

https://gist.github.com/darron/b8ab56f7e6adcbf95acb

And this template:

```
{{timestamp}}
{{range tree "octohost"}}
{{.Key}}{{end}}
```

I can trigger updates at will:

```
May 25 11:52:27 doctohost01 consul: consultemplate: I ran again
May 25 11:53:16 doctohost01 consul: consultemplate: I ran again
May 25 11:53:19 doctohost01 consul: consultemplate: I ran again
May 25 11:53:21 doctohost01 consul: consultemplate: I ran again
```

Consul Template logs: https://gist.github.com/darron/cc383bf41bf4c2a898fa

And it never "waits" at all.

Am I understanding that option incorrectly?

**Comment by sethvargo** [comment]
Hi @darron 

May I ask what version of Consul Template you are using? I just tried the master branch and I am seeing quiescence work as excepted.

In the logs, you should see a line like:

```text
[DEBUG] (runner) enabling quiescence for "example.ctmpl"
```

which indicates quiescence was activated. I tried both a config option as you provided and the CLI option.

Can you please try running master and let me know if the issue is still happening? If it is, can you please provide the complete debug log? It looks like some pieces are missing from the one linked above. Thanks!

**Comment by darron** [comment]
I was using 0.9. Will rerun it and show all logs.

**Comment by darron** [comment]
Here's the logs under 0.9.0 - I can see that wait is 0 in the output:

https://gist.github.com/darron/1592debd77598dd7041e

And here's the logs with master:

https://gist.github.com/darron/bf56fceab5c9968eddf5

Looks good under master.

Sorry about reporting something that's already fixed - I didn't see an obvious fix in the changesets - but looks good now.

**Comment by sethvargo** [comment]
Awesome. I'm glad it's working now. I'll try to get a new release out later this week.
