### ISSUE TITLE
Allow Consul K/V to be source of a template

### ISSUE THREAD

**Issue by seeder** [hashicorp/consul-template#303]
It would be super useful to be able to use consul k/v store to fetch templates instead of forcing us to have them as files only

**Comment by sethvargo** [comment]
Hi @seeder 

Thank you for opening an issue. This is not something I plan to support in Consul Template, but please allow me to explain further.

These templates are part of your configuration. As such, they should be versioned (using something like git) and reviewed by your team (using something like gerrit or GitHub pull requests). Blindly allowing anyone to update templates in Consul reduces the amount of version control over the file. It also causes problems with doubly-nested interpolation that is very difficult for humans to reason about. These templates can then be put on a system using something like Chef or Puppet or just a simple `scp`.

Secondly, putting templates in Consul poses a bit of a security risk. Since those templates are written to disk and then evaluated, anyone with access to Consul KV store has the ability to write data to any system running Consul Template. 

So while it may be "useful" to fetch templates from Consul's KV store, I do not want to encourage this behavior. What do you think?

**Comment by seeder** [comment]
@sethvargo let me address some of your concerns. 

 * Security issues inside Consul are just that. Consul, not consul-template issues. Consul security can be easily managed via ACLs and trying to solve that via not allowing sourcing in consul-template is backwards. When you treat Consul as a serious tool in your arsenal, you have it secured. Lack of security in consul, is your own organizational failure. 
Putting it a little bit different spin here, you already open the door of modifying files via Consul by just using templates and referencing Consul keys inside them.
At the end, when Consul is the single point of truth containing whole infrastructure information and gets compromised, consul-template is not the first thing which organization will be concerned about...  

 * Version control issues raised are again an attempt at internalize external problem. It is up to the organization to decide how to manage versions of the templates, the same way they manage contents of any other key inside Consul.
In the implementation I am currently working on, we use orchestration called ansible which uploads templates to consul. It's configuration is version controlled with git. I don't need more version control beyond that.

 * Double nested interpolation? it's so simple, I can only answer it with an example config file snippet: 


         template {
           source "consul:/application/templates/config.php"
           destination "/configs/appication/config.php"
         }
         template {
           source "file:/application/templates/config.php"
           destination "/configs/appication/config.php"
         }


  Hey, you know, this actually allows you to modularize template stores , maybe someone will find https or s3 more useful. 

* Use of Puppet / Chef to manage template files is not even old school, it's awkward. It adds to complexity. People go with consul and other latest tools to get out of these old ways of configuration management.

* Not allowing consul-template to fetch it's templates from consul k/v is equivalent of telling us to use ext2 filesystem and refusing to use a gfs because someone can modify the file somewhere else in a gfs cluster. 

@sethvargo , I believe that you mean well and I love consul-template, it allows us to deploy and configure so many things which puppet/chef where incapable of. Everything on the fly, no intervals. 
I just hope that you could make it applicable beyond the narrow path you've taken.

**Comment by sethvargo** [comment]
@seeder what do you propose this API looks like? Consul Template is very-much tied to the idea of taking a template to disk and rendering output to disk.

In fact, you could already achieve this if you wanted:

```javascript
// meta.ctmpl
{{ key "templates/example" }}
```

```shell
$ consul-template -template "meta.ctmpl:out.ctmpl:consul-template -template out.ctmpl:final.txt"
```

You start heading down a road where the user-experience is complicated to reason about. Here is what I'm thinking in terms of APIs:

```text
// template.ctmpl
{{ key "my/template" | parseTemplate }}
```

Thoughts?

**Comment by ryanuber** [comment]
@seeder thanks for the suggestions you've made. After speaking with @sethvargo a bit about this, we both agree that the feature could be useful, but is likely not something we will be able to prioritize in the near future. We would love to have first-class support for modular template sources, but unfortunately due to the additional complexity and refactoring which would need to happen internally, we simply can't focus on it at this time. We aren't saying "no", so if a pull request came in for such a feature we would definitely be open to reviewing and possibly merging it.

As @sethvargo mentioned above, it's possible that you can achieve the functionality you need, albeit with a few additional steps by taking the "template for a template" approach. I understand this isn't a forever solution, but should get you past this for now.

I'll leave this open for your thoughts and replies to the previous post.

**Comment by seeder** [comment]
@ryanuber lovely!

Unfortunately I am not fluent in Go, it will take me a while to have a go at modular template sources if I was the only one to do it.

When it comes to template for a template approach, I already hacked something what does about 3 step self-reference reconfiguration of consul-template. I believe I can lower it down to 2 steps, but it does remain a hack, until other template sources are available.

**Comment by phoewass** [comment]
I agree retrieving templates from KV would be a very useful feature.

**Comment by seeder** [comment]
Since you have introduced plugins I have been able to delegate the fetch of the template to an external process. 

We are running CT inside it's own docker container which is watched and always re-spawned if dead. CT watches for templates in consul and then fetches them and reconfigures itself to use them ( we point it to look at directory for config files in our case at /config/consultemplate/config ) 

the "seed" 0-config.conf is 

    template {
       source = "/config/consultemplate/template/1-services.tmpl"
       destination = "/config/consultemplate/config/1-services.conf"
      command = "/bin/kill 1"
    }




this is simplified  /config/consultemplate/template/1-services.tmpl

    {{range tree "/" }}{{ if .Key | regexMatch "/Templates/" }}
    {{  $tmpl_path := .Key}}{{  $tmpl_content := .Value}}{{  $service := .Key | regexReplaceAll  "/Templates/(.+)$" "" }}
    {{  $path := .Key | regexReplaceAll "^(.+)/Templates/" "" }}
    #{{  $tmpl_path | plugin "fetch-tmpl-content" }}
    template {
       source = "/config/consultemplate/template/{{$tmpl_path}}"
       destination = "/config/{{$service}}/{{$path}}"
    }
    {{ end}}{{end}}

 

as you can see, i had to do a lot of cheating with regex because you do not allow simple string manipulations, but it's getting there and works like a charm. Would be nice to replace the fetch with what i proposed in the original , also on the other hand allow string manipulation beyond regex

also the "fetch-tmpl-content" plugin after downloading template it outputs sha checksum so that when the template changes the contents of the file change ( hence the # )  and it reloads itself to use it.

**Comment by Kosta-Github** [comment]
@seeder thank you so much for your trick, I was exactly in need of this: I want to automatically create grafana metrics dashboards for the services deployed via mesos/marathon/consul and the cluster nodes registered with consul. I am already using the KV store for configuring logstash to produce statsd/graphite metrics from the service logs, docker metrics, consul metrics, (soon: marathon and mesos metrics/events) and now I want to create the corresponding metrics dashboards in grafana automatically. Each service should be able to define the metrics extract from the logstash events (already working) as well as being able to define its grafana dashboard combined with some generic parts common to all servcies.

**Comment by seeder** [comment]
@Kosta-Github fetch is at https://gist.github.com/seeder/021eac1ac8d4e5102161 

and yes, it is docker mapped volume

**Comment by sethvargo** [comment]
Hi @seeder and @Kosta-Github 

I am going to close this issue since it looks like there's a pretty solid solution for this at this time. If there's more traction in moving something like this into core, we can always revisit :smile:

**Comment by udondan** [comment]
I also created little bash plugin script which can be used to archive this: https://gist.github.com/udondan/58195fe5801287e6e5ed1a9505b0baa2

Can be used like this:

```hcl
template {
    contents = "{{ key \"some/key\" | plugin \"consul-render\" }}"
    destination = "/some/file"
}
```

This is extremely limited and only supports very simple templates and already a double quote in the template will break it for obvious reasons.

**Comment by pvandervelde** [comment]
Has anyone figured out how to handle vault related tokens in the original template? @udondan @seeder @ryanuber @sethvargo?
