### ISSUE TITLE
Exit when -once is specified and there is an error

### ISSUE THREAD

**Issue by sebastiang** [hashicorp/consul-template#319]
When `-once` is specified, an error (e.g. bad login token) should terminate the program. Instead it enters daemon mode and must be interrupted.

**Comment by sethvargo** [comment]
Hi @sebastiang 

This is the expected behavior. The API promise for `once` is that Consul Template will retrieve data for each dependency _exactly one time_ and then exit. Since it did not retrieve data once, it sits and waits for data.

This is important because users have requested that Consul Template _not_ exit when data is unavailable, because they may wish to watch a key that does not yet exist or only exists as a feature flag.

What do you think?

**Comment by sebastiang** [comment]
Running consul-template as a demon is a great use case, and it certainly makes sense to re-run and wait on error to accommodate race conditions in infrastructure setup. But running it once and exiting is a great tool for configuration debugging, or even local development use. It lets you isolate when things change and more rapidly debug or test configurations. A separate flag like `--exit-on-error` would accommodate the use case.

**Comment by sethvargo** [comment]
@sebastiang the problem is that "exit on error" means different things to different people. Consul Template already "exits on error" if the command execution fails. If you are doing local testing, you should run with `-log-level=debug` and you can see the output that is being generated (including the error) :smile:. It seems to me that would make more sense for configuration debugging or local development anyway, so I'm not sure I see the use case.

**Comment by sebastiang** [comment]
Sure. Could always use a `timeout` to stop the program if it doesn't complete in some reasonable time, and assume it's because of errors,

**Comment by sethvargo** [comment]
@sebastiang Consul Template 0.10+ has a command execution timeout, but there cannot be a timeout for dependency fetching because Consul does blocking queries until data changes. If we timed out, that would be bad :smile:.

I would suggest surrounding your script execution with a timeout. If you know the script should exit in < 15s, I would wrap that and then kill if it does not complete successfully. This will work in development, but I would highly encourage you to run Consul Template as a service in production. You run the risk of having stale data or of having bad data because of a flap during the execution. If there is a particular concern you have with running Consul Template in production, I would be happy to address it.

**Comment by sebastiang** [comment]
This is definitely a development vs. production issue. Nicer to iterate quickly if you know all services are up. In production, you'd certainly run a demon and restart your service or instance on change.

**Comment by sethvargo** [comment]
Hi @sebastiang 

I just wanted to revisit this - I've been thinking about this a bit more, and I think I want to leave the current behavior intact. Do you have any objections?

**Comment by sebastiang** [comment]
Interrupting manually while debugging and putting a timeout around intended one-shot uses are functioning workarounds, so no objections from me! Perhaps some more firm documentation around `-once` would help with anyone else who had my expectation.

**Comment by sethvargo** [comment]
@sebastiang sounds good - I will work on improving the docs!
