### ISSUE TITLE
Add validate command for templates

### ISSUE THREAD

**Issue by cbarbour** [hashicorp/consul-template#329]
It would be very useful if consul-template to provided a validation command that could be performed before writing a template to it's target location, similar to the [validate_cmd](https://docs.puppetlabs.com/references/latest/type.html#file-attribute-validate_cmd) parameter of the Puppet file resource.

There are situations where a broken, misconfigured, or compromised host could be used to push syntactically invalid or conflicting values into Consul that might prevent a managed service from starting. Although good input validation could prevent a lot of these problems, if such a case were to slip through the checks it could easily cause a site-wide outage.

The current solution is to include a validation check as part of the command field of the template declaration. E.g.

    template {
      source = "/etc/consul-template/httpd.conf.ctmpl"
      destination = "/etc/httpd/conf/httpd.conf"
      command = "service httpd configtest && service httpd reload"
    }

However, in these cases the test is performed after writing the config to disk. At best, the service would remain running in an inconstant state.

I'm proposing this solution:

    template {
      source = "/etc/consul-template/httpd.conf.ctmpl"
      destination = "/etc/httpd/conf/httpd.conf"
      validate_command = "apachectl configtest -f {}"
      command = "service httpd reload"
    }

Consul template would first render template to a temporary location, and run the validate_command, substituting `{}` with the path of the tempfile. If the validation returns 0, the file is coppied to destination, otherwise consul template handles it the same way it would any other command failure.

This could be used with the built-in syntax validation offered by many common services, by a custom validation script, or by Augeas to provide a sanity check before potentially bringing down a service.

**Comment by sethvargo** [comment]
Hi @cbarbour 

Thank you for opening an issue. I was very aware of this use case when I wrote the original version of Consul Template, and we had pretty extensive discussions about the best experience here.

In short, this is already possible and encouraged using the arbitrary `command` parameter. Since the command is executed as `sh`, you can do quite literally anything :smile:. You are correct that the command is executed after the file is written, however. 

My usual recommendation is to do something like this instead:

```
template {
  source = "/etc/consul-template/httpd.conf.ctmpl"
  destination = "/tmp/httpd.conf"
  command = "apachectl configtext -f /tmp/httpd.conf && mv /tmp/httpd.conf /etc/httpd/conf/httpd.conf"
}
````

This has two advantages:

1. It keeps the API simple and declarative - write this file to disk, then the command is responsible for verifying and putting it in the right place.
2. If the command fails, Consul Template will die. Your monitoring system/whatever can then alert you of the failure.

Does this make sense? I'm not sure I see the need to complicate with API with another configuration option when the command is incredibly flexible as-is :smile:.

**Comment by cbarbour** [comment]
Thanks for the quick reply, Seth.

Your answer does make a lot of sense. Although I feel that chaining together commands isn't terribly readable, it is perfectly functional.

Remaining thoughts:

* Having an explicit validation command field would encourage users to validate their output. This encourages good practices.
* Having the field eliminates the need to chain together a bunch of shell conditionals.

None of these are blockers for me.

**Comment by sethvargo** [comment]
Hi @cbarbour 

You do not have to chain commands together - I was just doing that for simplicity :smile:. You can extract that logic out into a script and include logging and share it with multiple templates, etc.

Template validation is a very service-specific detail, and we have done a great deal to try and steer users away from using Consul Template as a service manager. I think adding a validation command is not only too specific for the general use case of Consul Template, but I fear that it would encourage that bad behavior of using Consul Template as a service manager (https://github.com/hashicorp/consul-template/pull/320).

I understand your point - I think a happy compromise would be to update the documentation to encourage validation. I'll work on that.
