### ISSUE TITLE
Possibility to use K/V store as distributed and at the same time as differentiated? 

### ISSUE THREAD

**Issue by ashish235** [hashicorp/consul-template#337]
My scenario is where I 've 5-6 application servers with consul-template running, where the main configuration file is my Consul template. The template uses Consul's HTTP API and the Key-Value store to replace the values for the configuration items. There is also an arbitrary command in place to restart the application once the configuration is changed say in the K/V pair. Now Consul-template restarts all my applications at once resulting in a downtime. 

It would be an ideal case where I can select a group of applications to only restart when I change a value and restart the other group when I want so I can have a HA. 

One way is to have separate Key names for the K/V pair but then it's not an efficient way and it creates redundant configuration data and also prone to errors, which I would like to avoid. 

Is there any way I can achieve what I want? 

Thanks!

**Comment by sethvargo** [comment]
Hi @ashish235 

Thank you for opening an issue. Could you please share your configuration files so I have a better understanding of your setup?

We have made very intentional decisions to avoid turning Consul Template into a service monitor. There is also a general sentiment in the microservices world that each service has its own configuration and each consul template instance manages one service.

If your application does not depend on a value from Consul KV store, it should not be a dependency of the template (see single responsibility principle). If you take this approach, I think things will become much cleaner for you. If you have inter-dependent keys, it is difficult to reason about the effects of changing one key.

Finally, you can perform complex restarts and blocking using the arbitrary command. Since that can be any shell script, you have the ability to make intelligent decisions regarding the behavior of the restart/reload.

Does that answer your question?

**Comment by ashish235** [comment]
Hi @sethvargo, thanks for the reply. 

I could achieve what I wanted with some combination of shell script and Ansible. 

Thanks again!
