### ISSUE TITLE
Add splay option

### ISSUE THREAD

**Issue by mfischer-zd** [hashicorp/consul-template#347]
A `splay` option argument would be useful to complement the existing `wait` option argument. The value of the `splay` option would be a maximum time in seconds to wait before restarting the program under consul-template's control, from which a random value would be chosen. This would help prevent a thundering herd of synchronized application restarts that could take down a service entirely.

Example: `consul-template ... -splay 60 /path/to/program`

**Comment by TD-4242** [comment]
Not a go dev, so my quick look through the code didn't show me anything obvious, but isn't this covered by the -wait=min:max?

I couldn't tell if there was a random value/target between min:max that it was shooting for or if it was just based on when the next tick happens.

**Comment by mfischer-zd** [comment]
The `wait` option does not currently add any splay.  

One could calculate the splay ahead of time using configuration management, so that the application launcher passes different values to `wait` on each host in the group, but I believe it's better for consul-template to do this natively, because it would simplify deployments.

**Comment by TD-4242** [comment]
so what triggers the update between min:max on the wait?  if set to 5:300 and it's determined randomly then this would happen randomly over the next 5 minutes but not sooner than 5 seconds.  Like I said I couldn't really see off of a quick glance what the trigger between min:max was and if it would function like splay by randomly restarting between those two.

**Comment by mfischer-zd** [comment]
As I understand it (correct me if I'm wrong @sethvargo), the `wait` option controls how aggressive consul-template is at re-rendering templates as the underlying dependencies change in the data store.  This is to improve stability of the application that the templates are being rendered for.

For example, if the minimum wait time were 5 seconds, consul-template would not regenerate the file from the template until no changes were detected in the underlying data for at least 5 seconds.  And if the maximum wait time were 60 seconds, consul-template would regenerate the file, even if the data had changed 1 second ago, as long as it had been at least 60 seconds since the first triggering change occurred.

**Comment by TD-4242** [comment]
Ok, that makes sense then and why I couldn't find what I was looking for.

**Comment by sethvargo** [comment]
Hi @mfischer-zd 

Thank you for opening an issue. There's some good discussion here.

Implementing a `splay` option seems good on the surface, but it poses a few problems. First, there is not inter-process communication between CT instances. There is, therefore, no predicable way in which services will restart and there would be no guarantee that they still wouldn't all restart in the same small window. Furthermore, if that is the desired behavior, it can easily be accomplished with a `sleep $(( ( RANDOM % 30 )  + 1 )) && service foo restart` without the need to change Consul Template's API.

However, more importantly, adding a random sleep doesn't _actually_ solve the problem; it just masks it. In my opinion, adding a `splay` option would be the programming equivalent of adding a "sleep" to avoid a race condition. The proper fix is to add locking and mutexes to prevent parallel execution or create a pool to allow N to run in parallel. The recommended way to do this is via `consul lock`. In fact, CT works seemlessly with `consul lock` because it passes the Consul environment variables to the executed command environment. It looks like this:

```shell
$ consul-template "in.ctmpl:out:consul lock -n=5 service/foo service foo restart
```

This leverages Consul to restart at most 5 instances of "foo" at a time. You can further extend this logic with a custom bash script to restart a service, and if the restart fails, lock that key in Consul to prevent other restarts inheriting a bad config.

Does that make sense?

**Comment by mfischer-zd** [comment]
That's an excellent point, Seth.  I never thought to use a mutex to synchronize restarts, but it's a fantastic idea, far better than using splay.

**Comment by alicebob** [comment]
This use of `consul lock` is rather nice and could use a mention in the consul-template docs somewhere, imho. Now it's hidden in this old, closed ticket.

Do you have any ideas about this, @sethvargo ?

**Comment by grobinson-blockchain** [comment]
@sethvargo what do I need to do to make consul-template spawn a bash shell? The following doesn't work for me

    Aug 15 20:15:32 consul-template[6298]: 2017/08/15 20:15:32.442797 [ERR] (cli) 1 error occurred:
    Aug 15 20:15:32 consul-template[6298]: * failed to execute command "sleep $((RANDOM % 30)) && systemctl restart xyz || true" from "/etc/consul-template/xyz/tmpl-source/xyz.ctmpl" => "/var/xyz/xyz.json": child: command exited with a non-zero exit status:
