### ISSUE TITLE
Add option on HealthService to see if service is in maint mode

### ISSUE THREAD

**Issue by split3** [hashicorp/consul-template#350]
It would be helpful to determine if a service is currently in maint mode.  I wrote a quick approach to this (no tests yet but can add them if you think this is valuable) and not sure I like it inside the status function and might move it out but fits there quickly as we're already iteratoring over the checks.

split3/consul-template@c649c78b39b851085b3fea13be7e20d68c8fdbe9

The idea here is to try and leverage maint mode to test services prior to enabling them.

**Comment by sethvargo** [comment]
Hi @split3 

Thank you for opening an issue. I've been thinking about this over the past few days, and I think this is a bad idea. Let me explain.

- I think toggling status for maintenance mode opens up edge cases that make a template difficult to reason about.
- What would be the expected behavior when a service is in maintenance mode, but has other checks failing? That behavior would be undefined and each user's expectation would differ.

"Maintenance mode" is just a specific type of warning, so I would prefer to use "warning" in general to avoid weird edge cases :smile:.

I would recommend using Consul's KV store to AB test services like this. Does that make sense?

**Comment by split3** [comment]
@sethvargo Yea after a few days of looking at this we decided that the approach was too brittle and it was just easier to use the KV store (and more beneficial in a cases of a node failures) to determine which set of services should be the active ones.  Thanks for taking the time to think on it as well.  Sorry I should have closed it sooner myself, just forgot.

**Comment by sethvargo** [comment]
No problem :smile:
