### ISSUE TITLE
When using -once, consul-template should only attempt once

### ISSUE THREAD

**Issue by wwalker** [hashicorp/consul-template#361]
If the following is run, it will generate the template once and exit, as expected:

    consul-template -dry -once -config etc/consul-template.config -consul localhost:8500 -template input:output

However, if there is a runtime error, rather than running once, it will attempt to generate the file forever.

It should only run once, even if there are errors.

**Comment by sethvargo** [comment]
Hi @wwalker 

This is the expected behavior. The API promise of "once" is "the template will be rendered exactly once". It is not atypical for users to create templates that depend on keys that do not yet exist.

Can you please describe your use case a bit more?

**Comment by wwalker** [comment]
The use case it building new templates.  If the new template has a typo, the "test the new template" never exits.  Also with Vault, when the template is written, the secret may exist, but it will likely expire in the next 30 days.

Also, we're using mesos, and are considering running consultemplate with -once to build any templates that a developer includes in the build artifact.  Really don't want it to look forever if he has a typo in the template (or a secret is missing/expired in vault.

Maybe add -once-only?

**Comment by wwalker** [comment]
Maybe add --exit-on-error or --fail-on-error?  Not sure if that should only be allowed when the -once flag is present?

**Comment by 0rax** [comment]
Hi there,

I was wondering about the same thing today, and found this issue. I totally agree with you @wwalker about the fact that a specific switch to exit on first error should be available.

In our use case we would like to use `consul-template -once` to configure our docker containers. And having the templator exit after either x-retries or the first error will help us making our container exit on fail so that we have a direct return in case of typo in the configuration template or if the consul agent is not yet present.
Right now the container will hang if one of the templates has a typo in it or if one of our developers did not put the right consul-agent url to test its newly created container making debugging sometime pretty hard.

Thanks
