### ISSUE TITLE
Request - Add ServiceAddress to Service Fields

### ISSUE THREAD

**Issue by Telmo** [hashicorp/consul-template#370]
The ServiceAdress field and the Address field can be different, usually ServiceAddress is empty but when spawning container with [1]weave the ServiceAddress can be set to the weave IP while the Address usually references the Docker host IP. There is no current way to get the ServiceAddress

```json
[
{
      "Node": "docker-as-1p",
      "Address": "<ip>",
      "ServiceID": "0298be8b0db0:foreman:80",
      "ServiceName": "foreman",
      "ServiceTags": [
         "foreman",
         "1.3.8"
      ],
      "ServiceAddress": "10.128.0.2",
      "ServicePort": 80
   }
]
```

This is important when trying to route traffic to the weave IPs, instead of the Docker Host IPs

[1]http://weave.works/

**Comment by sethvargo** [comment]
Hi @Telmo 

The `Address` field is defined as follows:

```go
var address string
if entry.Service.Address != "" {
	address = entry.Service.Address
} else {
	address = entry.Node.Address
}
```

In other words, the `Address` corresponds to the service address if the service address is populated, otherwise the service address falls back to the node's address. You can always get the node's address via `NodeAddress`.

Does that answer your question? If not, can you please share your template?

**Comment by sethvargo** [comment]
Hi there,

I am going to close this due to inactivity. If you have additional questions, please feel free to post them here or open a new issue. Thanks! :smile:
