### ISSUE TITLE
arguments to user-supplied command?

### ISSUE THREAD

**Issue by davidbirdsong** [hashicorp/consul-template#377]
I searched around, but didn't find this request. Would it be possible to get the destination file passed into command's argv?

One of our use-cases is that we run a handful of nginx instance types, but the command we supply to consul_template could be generalized if it received the location of the config it is to act upon on update.

**Comment by sethvargo** [comment]
Hi @davidbirdsong 

Thank you for opening an issue. I do not think it makes sense to pass in things to ARGV since they can be completely arbitrary. Consul Template will execute any arbitrary script, and those scripts may be expecting arguments of their own.

I would recommend using your configuration management software (Chef, Puppet, Ansible, Salt, Bash, etc) to lay down the Consul Template configuration file like this:

```hcl
template {
  source = "<%= @source %>"
  destination = "<%= @destination %>"
  command = "my-script \"<%= @destination %>\""
}
```

This will allow you to de-duplicate the logic of where the destination is, still use `my-script` as a generic command, and pass in the final destination as a result.

Does that make sense?

**Comment by davidbirdsong** [comment]
Aye, this works and yes, I'm already templating that template file, so I'll just append the location to the command.

**Comment by sethvargo** [comment]
Internally we have a generic CM template that templates' a Consul Template template that intakes another template (also a CM template) that renders a destination template. :smile:

**Comment by davidbirdsong** [comment]
escaping hell?
