### ISSUE TITLE
Possible to override (or escape) the `{{ }}` delimiters?

### ISSUE THREAD

**Issue by polds** [hashicorp/consul-template#389]
I'm wondering if it's possible to change what the template delimiter is for Consul Template. We're working with some files that have some Jinja2 variables in them which are also represented as `{{ var }}` and Consul Template doesn't like it for obvious reasons. I'm wondering if it's possible to change what the delimiter is or to instruct Consul Template to skip failed items.

**Comment by polds** [comment]
Alright I figured out a hackish way around getting Jinja2 variables to work. Is there any better way than doing:

```
{{ `{{ var }}` }}
```

**Comment by sethvargo** [comment]
HI @polds 

Thank you for opening an issue. It is not possible to "escape" those values, but you can use strings (like you already discovered) or use the `printf` built-in template function.

Please note that Consul Template uses Go's templating language: http://golang.org/pkg/text/template/. Unfortunately we do not have a lot of control over that API :frowning: 

I hope that answers your question. I am going to close this issue since there are two provided workarounds, but I am definitely open to discussing more :smile:.

**Comment by alexzorin** [comment]
Any particular motivation to not expose https://golang.org/pkg/text/template/#Template.Delims as a config option? 

In our case we are conflicting with Ansible, and, well, the amount of work to annotate all our j2 templates for a different delimiter dwarfs our consul-template usage.

Would be very nice-to-have.

**Comment by slackpad** [comment]
Reopened to take a look at exposing the delimiter as a configurable.
