### ISSUE TITLE
Consul-template fails if vault token is not renewable

### ISSUE THREAD

**Issue by carlpett** [hashicorp/consul-template#436]
As of #367, CT will try to renew the given Vault token. However, if it fails to do so, it will exit. This will happen if using the root token, which while not a production scenario is something we do currently during development (local dev vault). 

Could a valid, but non-renewable, token be detected? That way the renew-check could be bypassed without setting `renew=False` as a configuration.

**Comment by sethvargo** [comment]
Hi @carlpett 

If a token is non-renewable, it will fail _eventually_. All tokens have a lease value, and once that lease value is up, the Vault request will fail and CT will exit with an error.

If you have a token that is truly unrenewable, you can tell CT to not renew the token via the configuration file, but this must be opt-in behavior because it requires the user to consciously understand the ramifications of not renewing the token.

Does that make sense?

**Comment by carlpett** [comment]
Maybe wasn't clear, but I'm using the root token, and I don't think that one expires, right? And it is non-renewable. 
I agree with `renew=False` being opt-in in the general case, but it would at least be helpful to detect the root token case and give a more specific error message.

**Comment by sethvargo** [comment]
Hi @carlpett 

Please please please please please do not use the root token. It is a really bad practice since it cannot easily be revoked and has full sudo access to anything in vault.

Sadly, there is no way in Vault to detect if you are using a root token or a generated token. CT does print a log message when the token is not renewable, but it will not error until the renewal fails. The reason for this behavior is that it is possible for an operator to renew a token using an out-of-band process like a cron job. :smile:

**Comment by carlpett** [comment]
Yeah, I'm aware that it is very much non-production. We ran into the issue when people had a local vault server for development/testing and used the root token there since "there was no point creating more tokens in local dev, right?".

But if there's no way to detect it, I guess we'll just have to do create a new token :)

**Comment by sethvargo** [comment]
FWIW, if you look at the vault_secret_test files, we create a new token for this very reason :smile:
