### ISSUE TITLE
Alternative templating engine?

### ISSUE THREAD

**Issue by saimonmoore** [hashicorp/consul-template#447]
Is there any chance of using an alternative templating engine e.g.https://github.com/benbjohnson/ego ?

**Comment by sethvargo** [comment]
Hi @saimonmoore 

Thank you for opening an issue. At this time, there are no plans to move to an alternative templating engine due to backwards compatibility. We evaluated a number of templating engines (albeit ego did not exist at the time) and decided that Go's templating language was the lowest barrier to entry with the most minimal number of dependencies.

I'll keep this open, since this is definitely something we want to do before moving to 1.0, but I don't know if "ego" is going to be the one we choose.

**Comment by sielaq** [comment]
+1

**Comment by cwarner-mdsol** [comment]
+1 new template engine please.

**Comment by saimonmoore** [comment]
thanks @sethvargo I'll keep an eye on the progress in this respect.

**Comment by grantr** [comment]
Lua might be a good template engine, see https://github.com/Shopify/go-lua

**Comment by sethvargo** [comment]
Hi everyone,

Go's templating language is improving with each release, so we are going to stick with it. Thanks!
