### ISSUE TITLE
No official docker image?

### ISSUE THREAD

**Issue by gionn** [hashicorp/consul-template#457]
It would be great to have a consul-template official image!

PR?

**Comment by sethvargo** [comment]
Hi @gionn 

We are focusing on improving the functionality of the project instead of maintaining an image. Consul Template is a static go binary with 0 dependencies, so the benefits of running inside a docker container are quite minimal as far as isolation goes. I understand the desire to be consistent, but we do not have a desire to maintain official Docker images for our projects at this time :smile:.

**Comment by gionn** [comment]
You are right, but I just find very useful to streamline deployments on dev and prod environments via docker:

docker run is the new curl && tar xf && make install :stuck_out_tongue_winking_eye:
