### ISSUE TITLE
Capturing of a Node's Datacenter within a template

### ISSUE THREAD

**Issue by atrbgithub** [hashicorp/consul-template#467]
Hi there, 
Would it be possible to capture a node's datacenter within a consul template file?

For example something along the lines of the following...

```
{{range service "apache" }}
{{.Address}} {{.Node}}.node.{{.DataCenter}}.consul {{end}}
```
This would give something like:
```
192.168.1.5  apache01.node.dc1.consul
```
This would resolve currently using consul to resolve dns lookups, but there doesn't appear to be a way to capture the datacenter within a template file, at the moment. Unless I am missing something?

Cheers

**Comment by sethvargo** [comment]
Hi @atrbgithub 

Thank you for opening an issue. Consul's API does not return the node/service data center because all queries are to a particular data center. By default, you are querying the default data center, so you should know the suffix. If you are querying a particular data center, you already have that suffix as well:

```liquid
{{ range service "apache }}
# ... here you know the data center is "dc1" or whatever you named the default dc
{{ end }}


{{ range service "apache@dc2" }}
# ... here you know the data center is "dc2"
{{ end }}
```

Does that make sense? You can also iterate over all data centers:

```liquid
{{ range datacenters }}

{{ end }}
```

Unfortunately Consul's data isn't structured in a way to query the data center for a particular logical service.
