### ISSUE TITLE
String array parsed from parseJSON plugin could not be joined by join plugin

### ISSUE THREAD

**Issue by tongda** [hashicorp/consul-template#474]
Hi, I have this kind of template:

```
{{with $ips := $tag | printf "%s/rules/accept_ips" | key | parseJSON}}
{{if $ips}}
if $remote_ip ~ {{$ips | join "||"}} {
    proxy_pass http://ip-presenter_{{$tag}};
}
{{end}}
{{end}}
```

I supposed to store IPs in the key in JSON type, `["127.0.0.1", "127.0.0.2"]`, for example. Then I want to join all these ip into one condition string, `if $remote_ip ~ 127.0.0.1||127.0.0.2`.

When running, I got error:
```
template: template: lb-tmpl:16:32: executing "lb-tmpl" at <"||">: wrong type for value; expected []string; got []interface {}
```

It seems that the parsed string array from `parseJSON` is not recognised by `join`.

**Comment by sethvargo** [comment]
Hi @tongda 

Unfortunately this is not possible because Go is a type-safe language. There is no guarantee that the resulting JSON will be a list of strings (it could be a deeply nested object), so it cannot accept an arbitrary json blob. Sadly this is a limitation of Go's templating language. You cannot "type" a string array, therefore the template parser cannot guarantee the result is JSON.

I would recommend restructuring your data to have each accept IP as a key under a common folder and then use the `tree` command combined with the `join` function, or just store the accept_ips in a simpler format like `1.2.3.4,5.6.7.8` and then use the `split` function and combine with `join`. Does that make sense? :smile:

**Comment by tongda** [comment]
Hi @sethvargo 

Thanks for your reply. It is very helpful. I like the idea of using folder and `tree`. I did not understand well about how to design the key/value in consul before.

I was thinking about creating a plugin that process the data in consul and directly generate the nginx config. This could make the template file cleaner.

Thank you very much.
