### ISSUE TITLE
why not read template file content when call Template.Execute?

### ISSUE THREAD

**Issue by gongaiguo** [hashicorp/consul-template#476]
Thus update template file would not need restart consul-template, I think.

thanks.

**Comment by sethvargo** [comment]
Hi @gongaiguo 

This is intentional. Because a template could reload and render at any time (since data changes in consul are unpredictable), an incorrect or partially complete template could be picked up. As such, we only load templates at boot and when the user explicitly reloads the process. This allows a user to iterate on a template as the process is running without worrying about rendering an invalid template.
