### ISSUE TITLE
Thoughts on randomized ranges?

### ISSUE THREAD

**Issue by jalaziz** [hashicorp/consul-template#481]
For some services (e.g. Nginx), the list of services should ideally be randomized if deployed across multiple machines. In Nginx's case, it will try upstream servers in order which could potentially result in many instances trying to reach the same upstream server initially.

This is a pretty pathological edge case for Nginx, but randomization of the services list (or other ranges) may help. I'm not suggesting this be the default behavior, but possibly introduce a `randomize` or `shuffle` helper function?

I know Consul DNS already does this already, but it doesn't appear to be the case for the Consul API.

**Comment by sethvargo** [comment]
Hi @jalaziz 

Thank you for opening an issue. There's another closed issue where I explain this in more detail, but adding "random" entropy to a template is not possible.

When Consul returns the results of the blocking query, Consul Template renders the template in-memory and compares that with the template on disk. If there are no changes, no action is taken. If there are any changes, the template is rendered and the command is executed.

In the case you've described, introducing randomness would likely cause a reload of nginx on each render. Even with no changes in Consul, the blocking queries still return at a regular interval, so nginx would reload every 15-30s.

So in order to introduce a random function, the function would have to be predictably random, always returning the same random set for a given input. If you're able to get something like that working with adequate test coverage, I'd definitely be willing to include it, but I don't think this is something we plan on adding to Consul Template ourselves. Thanks! :smile:

**Comment by jalaziz** [comment]
Well, we wouldn't necessarily need pure randomness. Some shuffling (can be stable per server) should suffice. For example, some shuffling based on a node ID may prove sufficient. That may be tricky to handle with de-dupe (although it could probably be treated like Vault tokens).

If that's something you think that may prove valuable, I wouldn't mind trying to setup a PR when I find some time.
