### ISSUE TITLE
partials/include support?

### ISSUE THREAD

**Issue by strarsis** [hashicorp/consul-template#500]
I cannot find a partial/include function that can include another config template.
This would be helpful, like adding a larger block of config in a loop.

Thank you and
with best regards

**Comment by sethvargo** [comment]
Hi @strarsis 

Thank you for opening an issue. This is not something that is currently possible due to Go's templating language. You can use the `file` option to bring in an external file, so I usually recommend you run multiple Consul Template processes and then have a meta process that uses the `file` function to put the pieces together. Thanks! :smile:
