### ISSUE TITLE
Add support for watching a specific item, and render a template on other values

### ISSUE THREAD

**Issue by awheeler** [hashicorp/consul-template#521]
In order to not watch hundreds of services, it's possible to just put a watch on the status of all checks, according to https://www.consul.io/docs/agent/watches.html , at the checks section.
As far as I can see, CT doesn't support this, but it would be great if it did, so that I could write a template that would get rendered if any checks change state, and specify the items to render in the template, but without watching them individually.

As an example:

```
{{range services}}{{range service .Name}}
{{.ID}}       0      IN      A       {{.Address}}{{end}}{{end}}
```

I have 200 services, so that tiny template creates 200 watches.
But, if we had something like this:

```
{{onlywatch checks "any"}}
{{range services}}{{range service .Name}}
{{.ID}}       0      IN      A       {{.Address}}{{end}}{{end}}
```

That would be just one watch, with the net effect being about the same in terms of updating.
Technically, this requires at least two different changes:
1. Adding something like onlywatch
2. Adding the ability to monitor all health checks as a single watch.

Additional background info: https://github.com/hashicorp/consul/issues/709

**Comment by slackpad** [comment]
Interesting - as an alternative I wonder if we could expose the checks endpoint in CT (https://www.consul.io/docs/agent/http/health.html#health_state) which would be one watch, though it might require some filtering/grouping to get one entry per service. I'll cc @sethvargo for thoughts on this one.

**Comment by jeffminard-ck** [comment]
Alternatively, a bit hacky, but you could run something like:

```
consul watch -type=checks run-at-change consul-template -once -c=config/path/etc
```

_(Syntax off the top of my head, so grains of salt, etc)_

Which would do much the same thing.

**Comment by sethvargo** [comment]
Hi all,

This is a fairly old issue that I wanted to revisit. While it's possible to [watch all checks](https://www.consul.io/docs/agent/watches.html#type-checks), we'd still have to then lookup the resulting service information (the check output doesn't include all the service information users typically need). 

For users who want to watch one service, this isn't really an issue, since watching all checks would like be a performance decrease for them, given a large number of services or checks. 

This would put a lot of load on Consul Template itself, since that endpoint tends to return quite frequently. Nodes in the cluster (which are not part of a service being monitored) would still cause the endpoint to render in the event of a state change. I think the majority of CTs processing time would be spent in a loop filtering these services.

I think deduplication mode is a much better solution, although it doesn't really help in situations where you are trying to build your own load balancer for all services. That being said, I think using stale queries and readonly standbys (non-voting members) will help reduce cluster pressure.
