### ISSUE TITLE
Allow command execution after N templates successfully render

### ISSUE THREAD

**Issue by bhourigan** [hashicorp/consul-template#533]
I'm building conf.d style configuration files (single flat file is not an option in my case) and I only want to run a command once all the templates have been rendered. Looking through the code it looks like if I set command to be the same, it'll wait until all templates are rendered and then run the command.

However, in practice, this doesn't seem to work. It runs through several cycles of attempting to start the service before it works.

I'm thinking I can run consul-template -once prior to starting my service, but I would also like the benefit of consul watching keys and bouncing services when values change.

Whats the right way to deal with this?

**Comment by sethvargo** [comment]
Hi @bhourigan 

This is not currently possible with Consul Template directly, because the commands are tied to the template itself. You could use a custom bash script that iterated over everything in the conf.d directory and ensured the resulting template was rendered before running the command, something like:

```
for f in /etc/mything.d; do
  d = $(cat "$f" | grep "destination" | cut -d'=' -f2)
  if [ ! -d "$d" ]; then
    echo "Missing $d!"
    exit 0
  fi
done

exec "service restart"
```

That's obviously some very quick psuedo-code, but I think you can see the idea.

Since this has not been a widely requested feature, I do not anticipate our core team implementing this. If you would like to take a stab, we would gladly review a PR.
