### ISSUE TITLE
Randomizing entries

### ISSUE THREAD

**Issue by jaxxstorm** [hashicorp/consul-template#552]
It would be really great if we could read the values into consul-template and randomize them when writing them out. For example, you have two servers, sensu1 and sensu2.

If you use the following template:

```
listen sensurmq
  bind 127.0.0.1:5677
  balance roundrobin
  mode tcp
  timeout client 100s
  timeout connect 5s
  timeout server 100s {{range service "rabbitmq"}}
  server {{.Node}} {{.Address}}:{{.Port}} check fall 3 inter 5s rise 2{{end}}
```

It will always render `server sensu1 <address:port>` first.
Ideally, it would be great if we could randomize the order which consul-template writes the file

**Comment by sethvargo** [comment]
Hi @jaxxstorm 

This is not possible because "random", by definition, is inherently non-deterministic. This would mean each iteration would render a new copy of the template and restart the service, even if nothing has changed in the list of dependencies. You can read more here: https://github.com/hashicorp/consul-template/issues/481
