### ISSUE TITLE
Even though there are no changes to service health, consul template is rendering template often

### ISSUE THREAD

**Issue by thedebugger** [hashicorp/consul-template#569]
In our prod cluster, we are seeing that consul-template is rendering haproxy configs (and hence causing haproxy reload which drops connections momentarily) though the services state doesn't change -- they are healthy. Consul could also be the culprit as it may be returning incorrect data to consul-template. We are running consul-template v0.7.0, consul service v0.5.0, consul client v0.3.0 in our cluster. It is possible that new version of consul and consul-template might fix the problem, but we don't want to update the prod cluster unless we track down the problem. In some cases, consul-template renders the template within 5-10 secs (perhaps some race condition?), and, AFAIT from logs, blocking calls to consul are returning in few ms(??). Here are the gist with consul, consul-template debug logs  -- https://gist.github.com/thedebugger/24d1256e43e6ee527028 
(I have replaced actual service names with dummy service names respectively)

I'm looking at the consul-template code base to see if I can figure out the problem, but any help would be appreciated. Let me know if more information is needed.

**Comment by sethvargo** [comment]
Hi @thedebugger 

Thank you for opening an issue. A lot has changed between Consul Template v0.7.0 and v0.14.0, and there are also significant stability improvements in Consul 0.6. While compatible, it is also generally recommended to run at least the same major version of the consul client as the consul servers.

You did not share your actual Consul Template template, but it looks like you may be trying to iterate over all services registered in Consul. This type of behavior is almost always going to result in this behavior, simply because any change in the system will result in a new subset of dependencies (N+1 query).

Consul and CT are backwards compatible, so my recommendation is to try and upgrade. Additionally, the logging output in newer versions is much better, so if there truly is an issue, I would expect it be easier to identify in later versions.

Unfortunately I cannot offer much insight beyond that. Please understand that our first debugging step is always "make sure you are running the latest version", so it's difficult to justify time identifying a bug that may have already been fixed. Sorry! :frowning:

**Comment by thedebugger** [comment]
yeah, I understand. re: iterating over services -- I saw GH-198, but no we don't iterate over service. Here is the template -- https://gist.github.com/thedebugger/a508916b39fbdf8cf4f8

**Comment by sethvargo** [comment]
Hey @thedebugger 

That template should work just fine, so I definitely think this is an issue that will be resolved with an ugprade.

**Comment by sethvargo** [comment]
Hi @thedebugger 

Did upgrading resolve the issue?

**Comment by thedebugger** [comment]
@sethvargo I didn't, but upgrading consul-template won't help after looking at the code base and doing more investigation. What I found is there are few nodes that are flapping continuously in our infrastructure. Not sure why as I can't make out anything from consul logs. But thank you for following up! Feel free to close this bug. I'll continue to do more investigation and if i find a something suspicious, i'll open an issue there. And thank you for the help!

**Comment by slackpad** [comment]
Hi @thedebugger if there are a few nodes consistently affected by flaps that usually is from network ACLs not allowing Consul's pings through (TCP and UDP should be open on port 8301).
