### ISSUE TITLE
ctmpl Template auto-discovery from a folder

### ISSUE THREAD

**Issue by samifruit514** [hashicorp/consul-template#574]
Hello,

I need consul-template to find recursively all the ctmpl files in a folder and render at a destination where the folder structure is the same.

**Context:**
I have a web application with several consul template files at different folder levels. Example:
./app-tmpl/conf/pluginA/configs.php.ctmpl
./app-tmpl/conf/pluginA/include/confA.php.ctmpl
./app-tmpl/conf/pluginB/configuration.php.ctmpl
./app-tmpl/conf/pluginB/configuration.php.ctmpl

Our development team can add any ctmpl files at any time in any sub folders and they don't have access to the initial configuration.hcl

**The requirements:**
We need to render all templates without having to put specific template paths in the initial configuration.hcl. The result expected would be something like:

./app/conf/pluginA/configs.php
./app/conf/pluginA/include/confA.php
./app/conf/pluginB/configuration.php
./app/conf/pluginB/configuration.php

**Suggestion**
We could render the files at the same directory levels where the templates are **OR** We could have a config like this:
```
template {
    source      = "./app-tmpl/"
    destination = "./app/"
}
```
where consul-template could detect if source and destination are folders and proceed with rendering instead of giving the following error: "read ./app-tmpl/: is a directory"

This way, our DEV team could add any templates without changing the initial configuration.hcl file.

Do you think it could be a good idea? If yes, I could proceed with a PR.

**Comment by samifruit514** [comment]
Ok I created a PR anyways: https://github.com/hashicorp/consul-template/pull/580

**Comment by sethvargo** [comment]
Hi @samifruit514 

Thank you for opening an issue (and a PR). I'll respond here to keep everything in one place. 

In short, I don't think this is a good idea for Consul Template because it only gets you "halfway" there. One of the primary use cases for Consul Template is the arbitrary "command" parameter that executes in the event that a template changes. Perhaps you are not using that functionality in your use case, but it's definitely the more common functionality. I think the UX around pulling from multiple templates as a directory could be very confusing:

- Does a command render if all the templates are changed?
- Does a command render if one of the templates are changed?
- Does a command render if a template is added or removed?

Additionally, it will become inevitable that someone wants to control the command on a per-template basis, which is exactly why the command parameter is specified at a per-template level.

That being said, it's still possible to get the development behavior. Consul Template's `config` option _can_ be the path to a directory, and each file in that directory is loaded and merged into a single config. In other words, you could do this:

```hcl
// /etc/consul-template.d/base.hcl
consul = "x.y.z.w:8500"
token = "abcd1234"
```

And then developers could just drop their configuration in that same directory when they add a new template:

```hcl
// /etc/consul-template.d/x.hcl
template {
  source = "..."
  destination = "..."
  command = "..."
}
```

This will give your developers more control over their templates as well, allowing them to render anywhere on the filesystem.

Please let me know if you have any questions. Thanks! :smile:

**Comment by samifruit514** [comment]
Hello Seth,

In our case, some of our services have a lot of config files so having one hcl per template is not really viable strategy. Plus we don't want our devs to maintain configurations on templates of configurations - they already have enough to do like this.

But I realized that having all those config files may be a bad smell. If we had only one config file per service, I would have never done this PR.

Anyways, we managed to work around our "issue" by calling a bash script that would do something like "find . | grep ctmpl" then generate a consul-template command line :\

Thanks for your feedback! :)

**Comment by deepakdeore2004** [comment]
@sethvargo consul-template doesn't read the changes from the directory provided with `config` option while it is running. It has to be restarted if new .hcl is added

Is there a way to consul-template will keep on reading the directory given in `config` option?
