### ISSUE TITLE
Template specific tokens for vault

### ISSUE THREAD

**Issue by grobinson-blockchain** [hashicorp/consul-template#583]
We're currently using Vault to store app specific secrets and would like to use consul-template to bridge the gap between Vault and our Docker containers without having to modify every app to become vault aware.

Each app has it's own app-id which makes to a read-only policy specific for that app. Our configuration management system acquires a token for the app-id policy via the Vault HTTP API and passes that token to consul-template.

However, we're currently seeing an issue whereby consul-template can't authenticate with vault. It appears that consul-template will only parse the first 'vault' block across all configuration files rather than use a different vault token for each template.

Is there a way to define a distinct vault token per template, if not, is this a feature that you might consider? We'd rather not have a single token with all of the above policies.

Cheers!

**Comment by sethvargo** [comment]
Hi @grobinson-blockchain 

Thank you for opening an issue. It is not currently possible to maintain a separate token for each template entry, since the Vault configuration is global. It would also require a re-architecting of the way CT handles dependencies to move them into the template layer. My recommendation here would be to run multiple consul-template processes, each with their own Vault token. The advantage there is that you can use the `VAULT_TOKEN` envvar (which is generally regarded as more secure than storing on disk), and you have finer-grained control over the restart and upgrade behavior for each template you're managing. Thanks! :smile: 

Consul Template is a very small process (in terms of memory), and we have a lot of users who run multiple CT processes per machine. In fact, some users run CT on a template that is then ingressed by another CT process :smile:.

Please let me know if you have any questions :smile:
