### ISSUE TITLE
New release based on Vault >=0.5.1 code to support VAULT_TLS_SERVER_NAME

### ISSUE THREAD

**Issue by rmt** [hashicorp/consul-template#586]
There was a patch that made it into Vault 0.5.1 to support the VAULT_TLS_SERVER_NAME environment variable (meaning that you can explicitly set the TLS server name to check for when connecting to the server).  If consul-template is compiled against a recent release of Vault, it should benefit from this patch.  This is useful for HA environments where you share a single server cert among all Vault servers, and want the Vault clients to work after they receive a redirect from a non-leader to the current leader.

**Comment by sethvargo** [comment]
Hi @rmt 

We generally do not publish new versions just due to upstream dependencies, but I will keep this issue open until the next release. Thanks!

**Comment by sethvargo** [comment]
We will update deps with the next release. Thanks!

**Comment by stevehorsfield** [comment]
Any news on this. This is a fundamental need to work with Vault. They are both products from your organisation, it seems crazy to allow them to drift??!

You could think of it as supporting SNI or a hostname to certificate name disconnect, equally applicable to Consul as to Vault.

**Comment by jefferai** [comment]
@stevehorsfield This has been in CT since at least version 0.14.0.

**Comment by stevehorsfield** [comment]
OK great. I couldn't see anything in the SSL config part???

**Comment by stevehorsfield** [comment]
This is not actually supported before CT 0.17.0. The Vault API does indeed have support but the issue is that the Vault API DefaultConfig does not read this environment variable and CT does not call the necessary ReadEnvironment function. Instead, CT populates the Vault configuration from the environment directly but only gets support for `VAULT_TLS_SERVER_NAME` in 0.17.0. See https://github.com/hashicorp/consul-template/blame/master/config/config.go#L731.

(based on testing in live environment using CT 0.14.0 and reviewing codebase).
