### ISSUE TITLE
NodeService does not contain service address

### ISSUE THREAD

**Issue by bmonkman** [hashicorp/consul-template#587]
Hey all. 
I noticed that the NodeService struct has only a subset of Service info that does not include the service address. I want to use this when routing from the local host to local containers identified by IP, rather than port. 
Since this is not available, instead of being able to use `index (node.services 0).Address` I will have to loop through the services to find the local node and get the address from there, which is quite a bit messier.
I can see why the need for address is a less useful case, but I think containerization will be making it more necessary.

**Comment by sethvargo** [comment]
Hi @bmonkman 

Thank you for opening an issue, and sorry this is causing problems. The `Address` field will contain the ServiceAddress if the service address is defined, otherwise it falls back to the NodeAddress. If no ServiceAddress is set, it's likely an issue with the way you're registering services in Consul. Can you issue a raw HTTP API query and take a look at the result?

**Comment by bmonkman** [comment]
The structure returned from the `service "myService"` has Address and NodeAddress in it, but the NodeService structure returned by `node.services` doesn't have any address information, it only has ID, Service, Tags and Port.

**Comment by sethvargo** [comment]
Hi @bmonkman 

That is expected because the catalog only returns a list of services like this: https://www.consul.io/docs/agent/http/catalog.html#catalog_node

**Comment by bmonkman** [comment]
Thanks @sethvargo 
Have you considered exposing the agent endpoints via consul-template?
The service data I'm looking for is there under agent/services, also a lot of useful stuff for templates in agent/self.

**Comment by sethvargo** [comment]
Hi @bmonkman 

It has not been a widely-requested feature, but I'm not against it. I suspect the difficult part is to distinguish between "health" services, catalog services, and agent services to be honest. I'd be curious to learn more about your use case.

**Comment by bmonkman** [comment]
Sure thing, so far I have 2 use cases where I would like data from the agent endpoints:

First, I have a nginx router on a mesos host that may have a few containers on it, the containers each have a distinct IP but their services use the same port. Consul is running on the host, and when the container comes up it registers a service with the IP of it's service which is accessible only to the host. In this case I would like to be able to get a list of all the IPs of the services on this host. I want them to have different IPs rather than different ports because I want to enforce some checking and do some routing based on the source IP.
Without a list of services from a node or agent function I have to do something like this:

```
{{with node}}{{range .Services}}

  {{ range service .Service }}{{ if eq node.Node.Node .Node }}
    server {{ .Address }}:{{ .Port }};
  {{ end }}{{ end }}

{{ end }}{{ end }}
```
 
Another use case is for agent/self when I want to find all services in other datacenters and route them differently than services in the current datacenter. 
At the moment, as far as I can tell there is no way to retrieve the name of the current DC, so I had to put an array of all the other DCs into the Consul KV store.

**Comment by sethvargo** [comment]
Ping @slackpad for ideas

**Comment by sethvargo** [comment]
Ping @slackpad

**Comment by slackpad** [comment]
Sorry I missed this one.

The response from the catalog does have the `Address` field, I think we'd just need to plumb it through to consul-template's `NodeService` structure. If the incoming one is blank, we can populate it with the node's address which is also part of the catalog response. That's how Consul's DNS resolves the address as well, and we intend to make Consul just fill in the service's address in the same way in a future release, but for now it seems reasonable for CT to do this (the logic will be safe in the future even if Consul starts filling them in). I think this'll fit your use case because you are probably setting the service address to your custom IP. Let me know if that's not the case.

We can probably expose a variable with the current DC as a new thing in CT. The agent endpoints don't support blocking query semantics so they aren't a good fit for CT, and they are _almost_ always not what people should be using :-) I'd hesitate adding them in general to avoid confusion.

**Comment by krishnabigdata** [comment]
I have Multiple host with Micro service in it, where all host have consul and nginx but the micro service instance is not present in all host which is the usual case. In this particular scenario , the consul template provide all IP’s associated to the service to nginx, since IP’s are local IP which will be present only in the particular host (accessiable to its own host). When load balancer sends request to NGINX, the nginx tries to load balance to ip's in the upstream which received from consul via consul template, but when the respective IP is not present in the same host. We get 502 Bad gateway error from NGINX, any thoughts or solutions on this.

Sample problem as mentioned by @bmonkman
