### ISSUE TITLE
range services in multiple datacenters in 1 go

### ISSUE THREAD

**Issue by rtoma** [hashicorp/consul-template#593]
Hi,

For a multi-dc application I am setting up a haproxy configured by CT.
I am using `{{ range services }}` to find the services that the haproxy should balance for (based on tags), but this will only list the services in the local datacenter. Since some services are only running in 'the other' datacenter they do not show up and the haproxy config is incomplete.

What I am looking for is a way to range services in multiple dcs - with a *single* range command, like:
```
{{ range services "@{dc1,dc2}" }}
  {{ range service (print .Name "@" .DC) }}
    {{ .Address }}:{{ .Port }}
  {{ end }}
{{ end }}
```

Of course this does not work (no support for `@{dc1,dc2}` and `.DC`) - but you will get the idea.

Please advice.

**Comment by sethvargo** [comment]
Hi @rtoma 

Thank you for opening an issue. This is not possible because each data center requires a separate query to Consul (there is no way to query all data centers in Consul, since they are logically separate entities). You can iterate over each data center like this:

```liquid
{{ range datacenters }}
  # ...
{{ end }}
```

If you look through the closed issues, there are some innovative solutions the community has come up with as well using nested templates, for example. Thanks! :smile:

**Comment by sean-** [comment]
Hello r. toma.

This isn't going to answer your question directly, but have you seen the
most recent webinar for consul? At minute 31 there is a section on multi-dc
failover that may be worth watching.

https://m.youtube.com/watch?v=FGbzS6ripXA

Does that indirectly help your situation out? -sc



-- 
Sean Chittenden
