### ISSUE TITLE
warnings generated when dynamically generating key names

### ISSUE THREAD

**Issue by szinck** [hashicorp/consul-template#606]
I have some consul keys that have names that could be variable.  When I try to render a template using those keys, I get warnings, however, it appears to successfully generate the template.

This issue is to remove the warning or resolve whatever condition may cause the warning.  Since it appears to work, it is confusing to have a warning message.

Below is an example:

```
consulate kv set test/a b
consulate kv set test/b success
```

with this template

```
{{ $some_var := key "test/a" }}

{{ key (print "test/" $some_var) }}
```

yields this

```
$ consul-template -consul=localhost:8500 -template=y.ctmpl:y -once
2016/04/07 20:50:10 [WARN] ("key(test/)") Consul returned no data (does the path exist?)

$ cat y

success
```

**Comment by sethvargo** [comment]
Hi @szinck 

This is the expected behavior, and you can safely ignore the warning. The reason is the n-pass evaluation, which is documented in the README: https://github.com/hashicorp/consul-template#multi-phase-execution.

In short, the first evaluation of the template will create a watch on "test/a", but that value won't immediately be available to the second dependency, which renders the key as "". The next pass, the data is present, which changes the key's value.

A way to suppress the warning is to use the `key_or_default` function, which will render a default value if that key does not exist on the first pass.

Please let me know if you have any questions.
