### ISSUE TITLE
Rebuilding old consul-template versions with newer Golang

### ISSUE THREAD

**Issue by Amit-PivotalLabs** [hashicorp/consul-template#614]
We're on an older version of `consul-template`, and would like to rebuild it against a newer version of Golang to deal with recent Golang CVEs.  It appears that dependencies are not vendored in the project, so it makes it fairly difficult.  Is there a simple way to figure out the versions of dependencies for an older tag of `consul-template`, and/or a plan to vendor dependencies going forward?

/cc @zankich

Thanks,
Amit

**Comment by slackpad** [comment]
Hi @Amit-PivotalLabs starting with v0.14.0 we've been adding the dependencies in the release branch in order to record them - https://github.com/hashicorp/consul-template/tree/v0.14.0/Godeps. For older releases I don't think there's a super good way to get the versions since they were not recorded and/or vendored.

**Comment by Amit-PivotalLabs** [comment]
Great, thanks!
