### ISSUE TITLE
Multiple consul addresses

### ISSUE THREAD

**Issue by chaen** [hashicorp/consul-template#619]
Hi,

apologies if this has already been asked, but I couldn't find anything about it.

As far as I understand, the consul parameter can only be a single address/host. However, if the local consul agent crashes, you are blind. Is there a plan to support several targets in this parameter to allow for failover solution ? 

Thanks
Chris

**Comment by slackpad** [comment]
Hi @chaen please take a look at https://github.com/hashicorp/consul-template/issues/486 for more context. When you talk to the local agent it manages communicating with the rest of the cluster, so we wouldn't want to expose that complexity by having the user configure multiple addresses (the local agent will track the Consul servers for you and mange connecting to a new one if there's a server failure). Since the local agent is in the same failure domain as the rest of the node, we don't support redundancy there. Most users run the local agent under a process supervisor that will restart it in the event of failure. Hope that helps!

**Comment by chaen** [comment]
Hi,
Fair point, thanks ! This however "prevents" from running consul-template on the same host than the consul server then. But okay, I have my answer, thanks !

**Comment by sethvargo** [comment]
Hi @chaen 

You can run Consul Template on the same host as the Consul server - you can bind to multiple addresses.

**Comment by chaen** [comment]
Thanks for your advices, and this nice tool :)
