### ISSUE TITLE
First boot gets stuck in unknown status if consul not in cluster yet

### ISSUE THREAD

**Issue by justicel** [hashicorp/consul-template#624]
We have discovered an issue with consul-template on the first boot of it after a new node is brought up.

If consul and consul-template are started within about a second of each other and consul has not yet joined the entire cluster consul-template becomes stuck in an unknown state.

There are no logs at all and even after waiting hours, consul-template never properly resolves itself to generate any templated files. If you restart consul-template and consul has been running correctly, it will then correctly generate the files. 

As I said unfortunately I don't have logs since none are being generated, but my guess is that consul-template is connecting to consul when it's not yet in the cluster and thinks there is nothing to update, rather than erroring out and trying again to connect to consul within the retry period specified.

**Comment by sethvargo** [comment]
Hi @justicel 

Can you please run Consul Template in debug mode and gist the logs for when this happens?

**Comment by sethvargo** [comment]
Hi there,

I just tried to reproduce this issue a number of ways and I have been unsuccessful. I tried starting CT at various points in Consul's init process (even adding arbitrary time.Sleep clauses to consul and re-compiling). I'm not sure why this might be happening, but without the debug logs it is hard to diagnose. 

I'm going to close this issue due to lack of response, but if this is still happening, please open a new issue and include the full log when running with `-log-level=debug`. Thanks! 😄
