### ISSUE TITLE
Run plugin only on change

### ISSUE THREAD

**Issue by madhurranjan** [hashicorp/consul-template#632]
Hi,

I'm running a plugin as part of my template and as of now it runs every single time even when there is no change.  How do I optimize it to run only when something changes? Apologies in advance, If this is the wrong place to ask this question.

**Comment by sethvargo** [comment]
Hi @madhurranjan 

Plugins are part of the template rendering process (they are a pre-processor). so there's no way to know if a template changes without running the plugin. It's a catch-22. Commands, however, are only run if a template changes. Perhaps you want to use a command instead of a plugin?

**Comment by madhurranjan** [comment]
Yes that works well.
