### ISSUE TITLE
Support to define the owner and the group of the destination file

### ISSUE THREAD

**Issue by luisbosque** [hashicorp/consul-template#639]
Currently consul-template supports setting the permissions of the destination file.
It would be great to be able to set the owner and group of it too. This would allow great flexibility without the need to run consul-template as the user that will be owner of the destination file.

Is this not implemented because any special reason or just because nobody needed in the past? I can try to send a PR with owner/group support if it's an acceptable feature.

**Comment by luisbosque** [comment]
Ok, I've found this issue where this feature is discarded:
https://github.com/hashicorp/consul-template/issues/461

**Comment by sethvargo** [comment]
@luisbosque 

Thank you for opening an issue. The problem is that there's really no cross-platform way to do this, and creating the file in advance will preserve the existing permissions so there's a good workaround. Keep in mind we support Windows, bsd, and more, so we need a fully-bc thing. If you can come up with a good PR for that, I'd be happy to review! Thanks! 😄

**Comment by njhartwell** [comment]
@sethvargo It looks like the current implementation does not preserve or copy the user/group attributes from an existing destination file. :+1: for built-in support for this (at least on *nix, if nothing else).

**Comment by ryancurrah** [comment]
Yes I was hoping it would preserve user/group when copying a file but it does not. Also running a command chown then restart doesnt work either it runs chown but fails to restart.
