### ISSUE TITLE
0.14.0 is broken on Amazon Linux 2016.03

### ISSUE THREAD

**Issue by marhel** [hashicorp/consul-template#642]
Consul-template 0.14.0 doesn't work on Amazon Linux 2016.03. It immediately exits printing only "Trace/breakpoint trap". This seems to be related to https://github.com/golang/go/issues/14795, basically that the go runtime uses a syscall that is disabled in Amazon Linux 2016.03.

**Comment by sethvargo** [comment]
Hi @marhel 

Thank you for opening an issue. Unfortunately I don't know what Consul Template can do here. This seems to be a bug in the programming language itself. Is there anything in particular you think we could do on the CT side?

**Comment by marhel** [comment]
Well, ideally there's already a fixed version of the go compiler/runtime and you could recompile CT against that version. If such a version isn't yet available, you could keep track of the release. I haven't understood if this issue is particular to the new Amazon Linux kernel, or just newer Linux kernels in general, but I expect more applications will be affected as adoption of newer version happens regardless.

**Comment by sethvargo** [comment]
It looks like this has been fixed though: https://github.com/golang/go/commit/0f86d1edfb87fddb2c7f50d177b67f48219151f3, although that doesn't say what release it's in. Since this is an upstream issue, unfortunately, I don't know of anything Consul Template can do other than "wait" and compile with the latest available version of Go 😦 . Do you think there are any other options?

**Comment by marhel** [comment]
Based on my very limited testing, other go-based applications seemed to work fine (eg Docker). I guess this means CT uses some particular go api that triggers this issue. Maybe that api is possible to use differently, or not at all to avoid the issue. 

Wait for the next go release is better unless its too far in the future.

**Comment by sethvargo** [comment]
Hi @marhel 

Did you install the 32-bit version of CT by chance? The thread I'm reading seems to indicate this is only affecting 32-bit compiled binaries. If possible, could you try the amd64 binaries?

**Comment by sethvargo** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/hashicorp/consul-template/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄
