### ISSUE TITLE
Cannot access multiple ports opened via nomad job

### ISSUE THREAD

**Issue by rajkashikar** [hashicorp/consul-template#661]
I am scheduling a job via nomad. The job is a web server with 2 ports (http and https). Nomad properly sees it as $NOMAD_PORT_http and $NOMAD_PORT_https. The consul-template on the other hand, just sees one port.

I am using consul-template to create haproxy config files. Here is 'backend' statement from haproxy.conf.
Is there a way to see it as Port0, Port1?

backend iceman-backend
        http-request set-header X-Forwarded-Port %[dst_port]
        server {{.Name}}  {{.Address}}:{{.Port}}  check {{end}}

Please let me know

**Comment by sethvargo** [comment]
Hi @rajkashikar 

Thank you for opening an issue. Unfortunately there is not enough information here to understand your question. How are you registering the service with Consul? Does the Consul API have both ports? I don't think it's possible to specify a service that runs on two ports in Consul /cc @slackpad

**Comment by sethvargo** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/hashicorp/consul-template/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄
