### ISSUE TITLE
Syntax highlighting for .ctmpl files?

### ISSUE THREAD

**Issue by mcandre** [hashicorp/consul-template#667]
Could we publish syntax highlighting packages for consul templates, so that GitHub, Emacs, Vim, and other popular editors make it easier to spot syntax errors?

**Comment by sethvargo** [comment]
Hi @mcandre 

Thank you for opening an issue. This is not possible because the underlying template syntax is whatever the result is. The templating language is Golang/liquid (they work pretty well), but if you are rendering an HTML file, the syntax is HTML. If you're rendering an nginx config, it's going to be that syntax highlighting.

**Comment by jippi** [comment]
what i've done is to name the ctmpl files in the format `${name}.${type}.ctmpl` and configured my editor to default syntax highlight based on `$type` - e.g. `default.nginx.ctmpl` opens in sublime with nginx syntax highlight :)

**Comment by mcandre** [comment]
@sethvargo there are workarounds

http://melpa.org/#/mmm-mode

https://github.com/vim-ruby/vim-ruby/blob/master/indent/eruby.vim

**Comment by jefferai** [comment]
Those are specific workarounds for specific file types and/or editors. CT is way too generic to support every single possible combination of editor/file type, of a workaround even exists for that combo.
