### ISSUE TITLE
Maintain template order

### ISSUE THREAD

**Issue by sethvargo** [hashicorp/consul-template#683]
We currently use a map, but that makes template order random. We should preserve template ordering.

**Comment by n2taylor** [comment]
Hi, can you explain the expected behavior here when we pass in a directory for config, containing a series of config files? I'm still seeing occasional instances where our templates are rendered out of order (based on filename). e.g. passing in a directory containing `a.cfg`, `b.cfg`, `c.cfg` leading to rendered files with timestamps suggesting they were rendered in the order "b", "a", "c".

**Comment by sethvargo** [comment]
Hi @n2taylor 

We generally do not triage old issues. If you think this is a bug, please open a new issue and supply your CT configuration and output please. Thanks! 😄
