### ISSUE TITLE
Consul template -once does not wait for missing keys.

### ISSUE THREAD

**Issue by dmikalova** [hashicorp/consul-template#714]
### Consul Template version
0.15.0

### Configuration
Any standard config will work.

### Command
consul-template -config="./consultemplate.hcl" -once

### Place your Consul Template command here
```{{key `missing_key`}}```

### Expected behavior
Consul template should wait for missing_key to be present before rendering.

### Actual behavior
Consul template renders a missing key as an empty string.

### References
- GH-188
- GH-319
- https://groups.google.com/forum/#!msg/consul-tool/Oh0bQQXvj9M/la2KtjRkFgAJ

**Comment by sethvargo** [comment]
For self ref: https://github.com/hashicorp/consul-template/blob/master/dependency/store_key.go#L83-L85

**Comment by slackpad** [comment]
Haven't worked through all the implications but I think that needs a `GOTO`
to keep waiting to fix this.

**Comment by sethvargo** [comment]
Hi @dmikalova 

Thank you for opening an issue. I was on my phone earlier, so I didn't have a chance to write a complete response. In short, this is behaving as expected. Whether that behavior is the desired behavior is unknown.

It has been a commonly-requested feature (and a common pattern in Consul) to use feature flags or keys that are set only in the event of flow. For example, maybe I have a key in my KV store that indicates if the beta group should be activated:

```
kv/features/beta
```

If that key exists in Consul, I want to activate the beta group. If they key does not exist, the beta group is inactive. Thus, the template would look something like this:

```
{{ if key "features/beta" -}}
beta_enabled: true
{{- else -}}
beta_enabled: false
{{- end }}
```

If we change `key` to block, that will break all existing templates which use this pattern. They will need to migrate to `key_or_default` to preserve the behavior.

I'm curious your thoughts on introducing this as a breaking change.

/cc @slackpad

**Comment by dmikalova** [comment]
Thanks, I was able to implement a wait logic and found that in my use case rendering things once doesn't really gel with how consul works. I am now making everything dynamic, so I don't actually need this anymore.

That being said, in the issues I referenced you've stated "if you give CT a dependency that does not exist in Consul, -once will hang until Consul returns data for that dependency" and "the API promise for once is that Consul Template will retrieve data for each dependency exactly one time and then exit. Since it did not retrieve data once, it sits and waits for data." I understand that to mean that if a key does not exist in Consul then it will wait for it. That is not how -once is behaving for me with nonexistent keys - instead it just renders the value as empty.

I think the best outcome would be to just document the behavior how you see it working - since once is a cli only option it's only documented in `consul-template -once`, which says "Do not run the process as a daemon". I think something in the repo readme that explains once and what counts as an existing dependency would help.

**Comment by sethvargo** [comment]
> Since it did not retrieve data once, it sits and waits for data.

That's where the confusion is... it did retrieve data, but the data was "there is no data here". It got a response from Consul and the response was empty. I think the behavior you really want is:

> Wait until the data is not empty

**Comment by dmikalova** [comment]
That makes sense, thanks. What would be an example of a dependency that does not exist, causing CT to wait?

**Comment by sethvargo** [comment]
The language here is confusing, because we are conflating "getting a response" with "getting a non-empty response". The best example of something that will block is a `file` query. If you query for a file that does not exist, it will block rendering until said file exists.

When you query for all healthy services named "foo" (`{{ service "foo" }}`), you're asking Consul - "give me all the healthy services named foo". If there are no services named foo, the response is the empty array. This is also the same response if there are no _healthy_ services named foo.

The comment you are quoting previously is in reference to Consul Template's multi-pass evaluation. CT processes the template multiple times, since the first result could impact later dependencies:

```
{{ range services }}
{{ range service .Name }}
{{ end }}
{{ end }}
```

We have to process the output of `services` before we can lookup each `service`, since the inner loops cannot be evaluated until the outer loop returns a response. CT waits until it gets a response from Consul for all dependencies before rendering a template. It does not wait until that response is non-empty though.

**Comment by dmikalova** [comment]
It all makes sense now, thanks for the information.
