### ISSUE TITLE
Validate Template Output

### ISSUE THREAD

**Issue by rossmcf** [hashicorp/consul-template#727]
I'd like a way to check that output from Consul Template is valid, or within certain limits.

The use case for this is in decoupling clients from a failed Consul cluster. Recently, we had an issue recently where Consul lost its state. Consequently, Consul Template wrote out empty files, causing services to fail. I'd like to be able to check, for example, that a minimum of two hosts were present in a service, or that a JSON file is non-empty before writing it to disk.

I think this could be achieved by having Consul template write out to a temporary location, and using the command to validate and move the file into its final location, but I'd like to see it as a feature of the tool.

Is this something you'd be open to?

Thanks,
Ross

**Comment by sethvargo** [comment]
Hi @rossmcf 

I would do two things here:

1. I would make sure you are using the `{{else}}` conditionals, even on range:

```
{{ range service "foo" }}

{{ else }}
  # no services
{{ end }}
```

This could help you write a fallback. Consider this - what would happen if Consul were still up, but all your service instances were unhealthy? This will help solve that.

2. I would _always_ _always_ _always_ run some kind of configtest or check before telling the associated service to restart, like:

```hcl
template {
  source = "config.ctmpl"
  destination = "/tmp/config.hcl"
  command = "my-service configtest /tmp/config.hcl && my-service reload"
```

I agree this is a somewhat common use case, and we've tried to tackle this before. The problem is that the surface area is just so large that it's impossible to provide a unified API that will work for all tools. This is why we ask folks to leverage the `command` option. Thanks! 😄

**Comment by rossmcf** [comment]
Thanks Seth,

Agreed. A brief look through the codebase has persuaded me not to attempt it! We'll stick to using `command`.
