### ISSUE TITLE
Template not obeying quiescence timer

### ISSUE THREAD

**Issue by maxar-ck** [hashicorp/consul-template#742]
### Consul Template version

Running consul-template 0.15 and consul 0.6.4
### Configuration

defaults:

``` javascript
consul = "127.0.0.1:8500"
max_stale = "1m"

deduplicate {
    enabled = true
}
```

template specific:

``` javascript
template {
    source      = "/var/www/source.php.ctmpl"
    destination = "/var/www/cfg/source.php"

    left_delimiter = "[["
    right_delimiter = "]]"
    wait = "30s:60s"
}
```
### Command

``` shell
consul-template -config=/etc/consul-template.d/
```

We're using a quiescence timer of 30s min and 60s max, and seeing consul-template apply changes to the templated files before the 30s timer is up. 

To test, we put a node included in source.php.ctmpl into consul maint and watched the template output for changes: 

```
[max.ar@serv1 ~]$ consul maint -enable && date
  Node maintenance is now enabled
  Tue Oct  4 16:27:32 PDT 2016
```

And observed changes:

```
[max.ar@serv2 ~]$ ls --time-style='full-iso' -l /var/www/cfg/source.php
  -rw-r--r-- 1 appuser appuser 75174 2016-10-04 16:27:39.936875946 -0700 /var/www/cfg/source.php
```

Also confirmed times are set correctly on both machines. Running with debug mode will output when the changes were rendered, but did not output a start time for the quiescence timer. Could this be due to the interaction between deduplication and the quiescence timer both being enabled?

**Comment by sethvargo** [comment]
I don't think the quiescence timers work with deduplication mode to be honest.

**Comment by masonoise** [comment]
With a large cluster, both deduplication and quiescence are pretty important. Is there any plan for a fix, or do people have a workaround?

**Comment by maxar-ck** [comment]
Is there any timeline for this issue being fixed? Or is there a known generally preferred workaround? This is blocking us from rolling out consul-template for the time being

**Comment by slackpad** [comment]
Hi @masonoise I tried to reproduce this with master but it looks like the quiescence timers are working properly. The timers are tied into the main loop that gets woken by the dependency manager, so they should be working together. I'm wondering if you were hitting https://github.com/hashicorp/consul-template/issues/677, in which case the dependency manager might have been spamming that loop and you were ultimately hitting the 60s max time. That 7 second diff between `consul maint` and the render seems pretty odd, so that's the only explanation I could think of there.

Could you try your test with v0.16.0? I verified that my test setup works with that release as well.

**Comment by maxar-ck** [comment]
After some extensive testing with v0.16, here's what Ive discovered:
- This occurs much much less on v0.16 than v0.15, to the point where it's tough to reproduce in even our prod environment, but we still have captured occurrences of it happening
- The issue is localized per dedup master, and hence each consul datacenter will exhibit or not exhibit this issue independently 
- When the issue occurs, all of the dedup followers will flip their templates earlier than the dedup master. Sometimes this results in the dedup master behaving correctly while all of its slaves do not
- During normal operation when a template flip correctly obeys the quiescence timer, all 20~ servers we have per consul datacenter will flip their templates within a 200ms time frame. When we see the quiescence issue, the template flips can be spread over a 10s~ window (we have a 30s minimum set)
- Even when the issue occurs and templates are flipped early, consul-template will still output the log line "[INFO] (runner) received template "/var/www/source.php.ctmpl" from quiescence" at the time of the template flip

Unfortunately I haven't found a reliable way of reproducing this issue, and digging through sourcecode has not yielded many hints. The information I have points to an issue with the way the dedup followers determine their timer, but the lack the of a setup to reliably reproduce this has been frustrating. 

Maybe someone from the team has some insight into known issues surrounding this area of the code?

**Comment by slackpad** [comment]
Hi @maxar-ck thanks for the update. I'll take another look through the code with you experience in mind to see if I can uncover anything.

**Comment by slackpad** [comment]
Hi @maxar-ck sorry for the delay on this one - I've been spending some time reading through the code and trying to build out a repro case. I'm starting to think that we might have an issue where an instance that wasn't a leader before but has later become a leader will have the dedup manager dependency as well as the actual dependencies for the template. When it tries to update that key it ends up snoozing its quiescence again, which would explain why usually the master seems to flip after the followers. I'll keep digging on this one and see if I can get things into that state to reproduce it, and then figure out how to cleanly set up the right dependencies for a leader and a follower.

**Comment by slackpad** [comment]
Ran into a few snags upstream while working on this but they look to be fixed now. Will pick this up again on Monday.

**Comment by slackpad** [comment]
Hi @maxar-ck spent some more time on this one and my initial hunch from https://github.com/hashicorp/consul-template/issues/742#issuecomment-259874034 was incorrect - this case is handled properly. I did a bunch of testing with instances that become leaders / lose leadership / and regain it and that's working as expected. Wasn't able to reproduce this in any way. Made another pass through the code as well.

At this point my only remaining theory is that this is a race condition between the independent q timers in the leader and the followers. The leader is watching all the real variables and is subject to the most load, so is snoozing its q timer often compared to the followers which are basically just watching the single key from the leader. The action of the followers should be very close in phase as well. It seems like you could get unlucky where the leader gets an update near its q timer expiring but before it can get the update out to its followers, which will flip. If the updates were very rapid, it seems like you could also see a case where the master goes all the way to its max time after the followers flip early, which could explain the 10s of seconds kind of thing.

I think the fix for the above would be to only have the leaders perform q timers for templates they are leading, and have the followers slave to the single key update from the leader. This would eliminate any chance for a race condition since there would be only one authoritative q timer.

This would be moderately complex change, but should simplify reasoning about q timers + dedup mode. Any thoughts on this approach? Also, if we get a patch together for this, do you have a good environment where we could stress test it?

**Comment by sethvargo** [comment]
Hey there @maxar-ck 

Did you see @slackpad's comment?

**Comment by sethvargo** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/hashicorp/consul-template/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄

**Comment by masonoise** [comment]
That's fine, thanks Seth. This has been a truly tough thing to test, as we've had no luck with a simpler test environment to reproduce it. At this point we've tweaked settings enough that it's almost never happening so it seems to be alright from our side for now. If it starts reoccurring more we'll open a new issue as you suggested. Thanks again.
