### ISSUE TITLE
Consul health api call for template engine

### ISSUE THREAD

**Issue by Salmondx** [hashicorp/consul-template#758]
Hello,
I have a problem with consul-template and have no answer how to solve it using existing template engine.
Currently, we are using consul-template + nginx and our template looks like this:

```
{% raw %}{{range services}}
upstream {{.Name}} {
  least_conn;

  keepalive 5;
  {{range service .Name}}
  server {{.Address}}:{{.Port}} max_fails=3 fail_timeout=60 weight=1;{{else}}server localhost:60000;{{end}}
}
{{end}}
```

This approach suffers a great performance issue when there are lots of services, registered in consul (cause `{{range service .Name}}` triggers a separate http call for every service from `{{range services}}`).

Is it possible to get a list of services through this call: /v1/health/state/passing, because this call returns all services in 1 call (not N calls for N services). Such approach is used in Fabio and it works great.

(Copy theme from mailing list: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/consul-tool/YW3_vQ5cGmk)

**Comment by slackpad** [comment]
HI @Salmondx thanks for opening an issue this is an interesting idea - will take a look and see how it could fit into the template implementation.

**Comment by sethvargo** [comment]
Hi @Salmondx 

I spent some time looking at this. While it's possible to monitor that endpoint for checks, that endpoint only returns _checks_ that pass a particular filter (like "passing"). In Consul, a service can have multiple checks associated with it; so even if you pull out all the services from that list, there could be other checks attached to that service which are not passing.

Additionally, that endpoint does not return any information about the nodes or addresses the server is running on. If you take a closer look at fabio, you'll notice they [still query the catalog](https://github.com/eBay/fabio/blob/90d0ca14e7b98e76cf60e848dba01f88c625adee/registry/consul/service.go#L74-L79) to get that information. So even fabio is using an N+1 query to get this data. The only difference between the fabio implementation and this one is that fabio is not _watching_ all of those services over time. This would place less pressure on the cluster (in theory) over time because of less blocking queries. However, if the cluster is in a lot of flux, you're still going to end up making a query for each service in the cluster.

**Comment by sethvargo** [comment]
Hi @Salmondx 

I talked with the team internally, and there are no benefits to inverting the query. However, there are some improvements in future versions of Consul that will make this easier. Thanks!
