### ISSUE TITLE
JSON Value possible typing issue

### ISSUE THREAD

**Issue by mross462** [hashicorp/consul-template#759]
Hi all,

Having an issue with consul template and vault:

```
~$ consul --version
Consul v0.7.0
~$ vault --version
Vault v0.6.1
```

I have the following stored in vault:

```
~$ vault read secret/staging/constants/v2/service/thing/elasticsearch
Key             	Value
---             	-----
refresh_interval	720h0m0s
JSON            	{"base_url":"a_url","external_base_url":"another_url"}
```

With the following consul-template:

```
---
{{key "services/common/environment"}}:{{with $secret := vault "secret/staging/constants/v2/service/thing/elasticsearch" }}
  base_uri: {{$secret.Data}}
{{end}}
```

I'm getting:

```
---
staging:
  base_uri: map[JSON:{"base_url":"a_url","external_base_url":"another_url"}]
```

But when using the dot notation in the template to access base_url:

```
---
{{key "services/common/environment"}}:{{with $secret := vault "secret/staging/constants/v2/service/thing/elasticsearch" }}
  base_uri: {{$secret.Data.base_url}}
{{end}}
```

I'm getting:

```
---
staging:
  base_uri: <no value>
```
  
My concern is that the typing of what is being read into consul is preventing this from occurring.

Any help or ideas would be appreciated.

**Comment by sethvargo** [comment]
Hi @mross462 

Thank you for opening an issue. This is behaving as expected. You inserted a key-value pair into Vault named JSON. The type of that value is a string, whose contents happen to be JSON. They are stored as a string though.

When you are reading in Consul Template, the response from Vault looks like this:

```json
{
  "Data": {
    "JSON": "{\"base_url\":\"a_ur\l",\"external_base_ur\l":\"another_url\"}"
  }
}
```

Notice that is a JSON payload which contains a JSON _string_ at `.Data.JSON`.

To parse this value out, you need to use `parseJSON` on `$secret.Data.JSON`:

```
---
{{key "services/common/environment"}}:{{with $secret := vault "secret/staging/constants/v2/service/thing/elasticsearch" }}
{{with $parsed := $secret.Data.JSON | parseJSON}}
  base_uri: {{$parsed.base_url}}
{{ end }
{{end}}
```

But this is really a hack in itself. I would discourage storing JSON blobs as data in the secret backend, since you're doubling the work. Instead of having a JSON key, you could just write the raw key-value pairs like this:

```
$ vault write secret/staging/constants/v2/service/thing/elasticsearch base_url=a_url external_base_url=other
```

Then your template is much simpler:

```
{{key "services/common/environment"}}:{{with $secret := vault "secret/staging/constants/v2/service/thing/elasticsearch" }}
  base_uri: {{$secret.Data.base_url}}
{{end}}
```
