### ISSUE TITLE
Add "secret_exists" function

### ISSUE THREAD

**Issue by bitsofinfo** [hashicorp/consul-template#776]
Similar to the behavior of `key_exists` it would be great to have `secret_exists`

**Comment by sethvargo** [comment]
Hi there,

Could you explain the use case a bit more? There's a difference between a secret and a Consul configuration. Consul flags can be used as booleans to control flow, but that's not as applicable to secrets. I cannot think of a scenario where you would want to check if a secret exists; it should just be there if you expect to authenticate. The `secret` functions behave differently than the Consul functions as well, in that they will exit if they cannot find a secret instead of just retrying.

**Comment by bitsofinfo** [comment]
> The secret functions behave differently than the Consul functions as well, in that they will exit if they cannot find a secret instead of just retrying

Hmm, the behavior I am seeing (with master) is that if a secret does not exist it keeps retrying forever and that template is not rendered. Hence why I need something that can just test for existence and exit, rather than halt the entire process.

My use case:

Vault structure

```
secret/parent-app1/path/to/secretkey = value
secret/derivative-app1/path/to/secretkey = value
```

I run my application that is driven by consul-template passing an argument that defines my "app-name"  and "parent-name"

```
docker run ....-e "app_name=derivative-app1" -e "parent_name=parent-app1"  ....
```

Template: (psuedo logic)
```
{{- $appName := env "app_name" -}}
{{- $parentName := env "parent_name" -}}

{{- $secretPath1 := printf "secret/%s/path/to/secretkey" $appName -}}
{{- $secretPath2 := printf "secret/%s/path/to/secretkey" $parentName -}}

{{- $hasSecret := secret_exists $secretPath1 -}}
{{- if $hasSecret -}}
     {{- with secret $secretPath1 -}}..do something.. {{end}}
{{end}}

{{- $hasSecret2 := secret_exists $secretPath2 -}}
{{- if $hasSecret2 -}}
     {{- with secret $secretPath2 -}}..do something.. {{end}}
{{end}}

....
```

Note the above is just psuedo of what I need to do in a basic form. The actual implementation traverses a tree of key/secret locations based on a configuration json variable that drives a set of key/secret paths to be checked" based on a concept of inherited configuration. Check your apps location... if not there check your parents location key path, etc... on so on. Permits us to define common configs at a high level and define ordered lists of key roots for resolution paths to permit overrides.

**Comment by sethvargo** [comment]
Hi @bitsofinfo 

Consul/Vault are not meant to behave like Chef Attributes or Puppet Hiera, and I would caution any architecture which tries to mimic such a setup using CT + Consul + Vault. I think you're going to have a sad time 😦 .

Vault is architected in such a way that `secret_exists` doesn't actually make sense. It may make sense for your particular use (using the generic secret backend), but it would not work for other secret backends like postgresql or aws, for example. There is no way to "check" if a secret exists at that path because the path is just an endpoint that generates a credential.

My recommendation would be to flatten configuration at the KV layer, doing replication via the API for common configuration, instead of trying to build inheritance into the templating language. 

Unfortunately this is not something we will be adding to Consul Template, since it architecturally does not fit in Vault's model.

**Comment by bitsofinfo** [comment]
@sethvargo 

v1/secret/.... returns a 404, simply don't get why this is not possible

**Comment by sethvargo** [comment]
@bitsofinfo because secret/* isn't the only path in Vault where secrets exist... You can read database creds from postgresql/creds/readonly, for example. Simply reading that path will generate a new postgres credential, so it's not safe to even attempt a read. You're only thinking about your particular use case of static secrets in the generic secret backend, but Vault's surface area is much larger than that. You can find more information here: https://www.vaultproject.io/docs/secrets/postgresql/index.html

**Comment by bitsofinfo** [comment]
I get that, but again, I ask you. What harm would having a `secret_exists` function that permits the test of a 404 on a secret URI endpoint if properly documented describing such scenarios as you laid out. This simply does not seem like some wildly unreasonable request.

**Comment by sethvargo** [comment]
Hi @bitsofinfo 

The issue is that the `secret` key can refer to any secret, so having a `secret_exists` key that only works on certain paths is a bad experience. Additionally, if the user happened to specify a non-secret/ path, it could potentially create a credential, which would leak over time. It's also fundamentally against the way we encourage users to structure configuration data.

**Comment by bitsofinfo** [comment]
Ok, thanks for the conversation on it at least. I'll let it lay and work towards another way of dealing w/ this.

**Comment by bitsofinfo** [comment]
For anyone else coming across this, you can do something like this to get the same effect

```
  {{ $secretKey := $fullpath | regexReplaceAll "^.+/(.+)" "$1"}}
  {{ $secretPath := $fullpath | regexReplaceAll "^(.+)/.+" "$1"}}

   {{range secrets $secretPath}}
       {{- if eq . $secretKey -}}
               {{/* DO SOMETHING */}}
       {{- end -}}
   {{end}}
```
