### ISSUE TITLE
Logging improvements

### ISSUE THREAD

**Issue by n2taylor** [hashicorp/consul-template#779]
Hi, I would like to propose a few small fixes for the INFO-level log messages in consul-template. Much of the INFO logging is not terribly useful in its current form and involves a lot of guesswork to figure out what's going on.

1. The logs never show which template is being rendered. This seems pretty essential to me.

2. The "received template $foo from quiescence" log is very repetitive and doesn't give any useful info. Probably better as a DEBUG message.

3. The general format of the dependency related log messages in the "(runner)" sections seem not to include much info about what's happening, seems like DEBUG output

4. The logs do not state which template initiated a command, even if it fails with an error.

**Comment by sethvargo** [comment]
Hi @n2taylor 

Thank you for opening an issue. I definitely sympathize with this feedback, and I'll try to address as much as possible.

> 1\. The logs never show which template is being rendered. This seems pretty essential to me.

I've made some improvements here, but unfortunately this can never be perfect. CT v0.17+ allows the user to specify raw template contents instead of the path to a file on disk, making it impossible to actually say _which_ template is being rendered. The new log will show "source => dest", but that may not be enough to uniquely identify a template in a large setup, since it's possible to have the same template output to different locations and it's possible to have different templates output to the same location. In those cases, the merge ordering determines which configurations take precedence.

The new logs will specifically separate the begin of the render event and the end. It will look like this:

```
[DEBUG] (runner) rendering "in.tpl" => "out.txt"
[INFO] (runner) rendered "in.tpl" => "out.txt"
```

> 2\. The "received template $foo from quiescence" log is very repetitive and doesn't give any useful info. Probably better as a DEBUG message.

Moved to debug.

> 3\. The general format of the dependency related log messages in the "(runner)" sections seem not to include much info about what's happening, seems like DEBUG output

I just looked, and all of the dependency log messages are currently [DEBUG]. If you see a specific one that isn't, please let me know. Note that there is no way we can associate a dependency with a template at that level; the deps have been aggregated and maybe exist in multiple templates.

> 4\. The logs do not state which template initiated a command, even if it fails with an error.

Unfortunately this is not possible, because commands are accumulated while templates are being processed, but then they are executed after all templates have been processed. Additionally, it's possible for multiple templates to specify the same command, and Consul Template will only run that command one time. For example, consider if you were dynamically writing out nginx configuration site files. Each of those templates may have an attached command of `service nginx reload`, but if some of those templates change simultaneously, you don't want to reload nginx for each template; instead, the commands are squashed. By the time we get to the process of running commands, we don't actually know which template the command came from, _and_ it could have come from more than one template. I've updated the logging output to show which template it's coming from, but that could be one of many templates that actually triggered the command.

```
* failed to execute command "sleep 40" from "in.tpl" => "out.txt": child: command did not exit within "30s":
```

**Comment by n2taylor** [comment]
Thanks, definitely an improvement.

> I just looked, and all of the dependency log messages are currently [DEBUG].

I'm seeing these two a lot in our logs:
https://github.com/hashicorp/consul-template/blob/aa39bf8ccf12ad2fbb51eae11f8d3e0fbacce198/manager/runner.go#L796
https://github.com/hashicorp/consul-template/blob/aa39bf8ccf12ad2fbb51eae11f8d3e0fbacce198/manager/runner.go#L202

**Comment by sethvargo** [comment]
Hi @n2taylor 

Do you have a lot of dependencies/templates?

**Comment by n2taylor** [comment]
Not too many, maybe 10 per server

**Comment by sethvargo** [comment]
Okay - Ill work on moving those to be less chatty
