### ISSUE TITLE
Request: Makefile target that doesn't use docker

### ISSUE THREAD

**Issue by ilovezfs** [hashicorp/consul-template#793]
Hi, I'm one of the Homebrew maintainers. While putting together a pull request for 0.18.0-rc1 as the development version of the consul-template formula, I noticed that the `make dev` target had been changed to use docker. As far as I can tell, the Makefile now has no target I can use that is free of docker use.

So for the time being, I intend to apply the following patch:
```
diff --git a/Makefile b/Makefile
index 4d5304c..917fb7b 100644
--- a/Makefile
+++ b/Makefile
@@ -35,19 +35,16 @@ GOFILES = $(shell go list $(TEST) | grep -v /vendor/)
 # environment variables.
 bin:
 	@echo "==> Building ${PROJECT}..."
-	@docker run \
-		--rm \
-		--env="VERSION=${VERSION}" \
-		--env="PROJECT=${PROJECT}" \
-		--env="OWNER=${OWNER}" \
-		--env="NAME=${NAME}" \
-		--env="XC_OS=${XC_OS}" \
-		--env="XC_ARCH=${XC_ARCH}" \
-		--env="XC_EXCLUDE=${XC_EXCLUDE}" \
-		--env="DIST=${DIST}" \
-		--workdir="/go/src/${PROJECT}" \
-		--volume="${CURRENT_DIR}:/go/src/${PROJECT}" \
-		"golang:${GOVERSION}" /bin/sh -c "scripts/compile.sh"
+	env \
+		VERSION="${VERSION}" \
+		PROJECT="${PROJECT}" \
+		OWNER="${OWNER}" \
+		NAME="${NAME}" \
+		XC_OS="${XC_OS}" \
+		XC_ARCH="${XC_ARCH}" \
+		XC_EXCLUDE="${XC_EXCLUDE}" \
+		DIST="${DIST}" \
+		sh -c "'${CURDIR}/scripts/compile.sh'"
 
 # bootstrap installs the necessary go tools for development or build
 bootstrap:
```

However, it would be very helpful to us downstream to have a target in the Makefile that does this so that we don't have to patch it.

Note that we cannot use docker in a macOS sandbox, so the consul-template build system is now basically out of commission for us without this patching. Hopefully, a docker-free target can be added before 0.18.0 goes from release candidate to actual release.

**Comment by ilovezfs** [comment]
The pull request referenced above is here: https://github.com/Homebrew/homebrew-core/pull/7049

**Comment by sethvargo** [comment]
Hi @ilovezfs 

Thank you for reaching out, and thank you for being a maintainer of homebrew 😄 . It's an amazing tool and I love it.

The reason we use (and moved to) Docker for the build process is to ensure that the binary is always 100% consistent. Docker provides an isolation layer. Without that, panics and stacktraces include personally identifiable information about the user who built the binary. Additionally, sometimes Go can do sad things if certain other packages are installed. By building in Docker, we remove all external dependencies except just those that are required to build the project. This has significantly cut down on build issues and is generally a better "build from source" experience for non-Go developers.

Is there a particular reason you need to build from source besides a master build? We release tgz and zip files for Consul Template on a CDN (fastly) that should be accessible from most anywhere. Since CT is a single static binary, it's a simple download + unarchive + move + chown.

My fear with adding a non-docker make target is the lack of control we have over the build. Docker allows us to control the complete environment, including the go version. Without a jank `if` statement, I can't enforce a go version or build. For example, Consul Template will totally compile on Go 1.6, but then very quickly panic when it receives a signal. Without the Docker workflow, there's not an easy way for me to enforce a go version.

**Comment by ilovezfs** [comment]
>Is there a particular reason you need to build from source besides a master build? We release tgz and zip files for Consul Template on a CDN (fastly) that should be accessible from most anywhere. Since CT is a single static binary, it's a simple download + unarchive + move + chown.

Everything in Homebrew is built from source. An alternative is for upstreams to distribute their own pre-built binaries via Homebrew Cask: https://github.com/caskroom/homebrew-cask/issues/25423.

So we could remove consul-template from Homebrew and move it over to Homebrew Cask. But if you want to continue distributing through Homebrew itself, we'll need to be able to build it from source. My personal recommendation would be that you stick with regular Homebrew.

Now, I could avoid your Makefile entirely and directly invoke `go build`, but it gives you more control, not less, if you can provide a make target for us to use directly, instead of leaving it to us to hack something together outside of your build system.

In terms of the build environment, it will be our latest version of go, which should always be the latest stable release of go, currently 1.7.3. And everything is isolated in a macOS sandbox during the build. The same is true for our users who choose to build from source. Their builds are also conducted in a sandbox, and use only our go.

If you're particularly worried about providing such a target, you could disable it unless a certain environment variable is set or put it in a different Homebrew-specific Makefile.

Here's how we currently build it: https://raw.githubusercontent.com/Homebrew/homebrew-core/7e5dc2dc5c185be48c2fdc892f8d78b310511230/Formula/consul-template.rb

**Comment by sethvargo** [comment]
Added a bin-local target

**Comment by sethvargo** [comment]
Also, you don't need to install gox anymore - we build natively with straight golang now. You can get rid of gox and iochan.

I think you'll need to change your make target to bin-local and then set the XC_OS and XC_ARCH env vars, since it looks like you're currently using the `dev` target and not the `bin` target.

**Comment by sethvargo** [comment]
Please let me know if you have any questions.

**Comment by ilovezfs** [comment]
@sethvargo it looks like 0.19.1 removed the `bin-local` target so the Homebrew formula is broken again :(
