### ISSUE TITLE
Exec mode without any reload signal kills the process

### ISSUE THREAD

**Issue by Ozonni** [hashicorp/consul-template#808]
Hi there,

I have asp.net core application which is running with consul template in exec mode.
The file which is rendered is automatically reloaded by the app, so there is no need to send any signal to the process to trigger the reload. So if i don't specify the reload signal then consul template restarts the process, at the the time if i specify reload signal like SIGHUP or SIGUSR1 then it kills the process.

Would be nice to configure consul template that it just doesn't send any signal and doesn't restart the process.

Thank you.

**Comment by sethvargo** [comment]
Hi @Ozonni 

Thank you for opening an issue. Adding such an option somewhat defeats the purpose of Consul Template, since it's actual design goal is to "watch for changes and notify the process when it changes". Adding such an option really defeats the latter point. Is there a reason you have to use exec mode and cannot use the default template option? You could also invoke "once" mode, but that is not going to watch for changes. I understand your use case, but I think it's antipathetical to CT's design and goals.

**Comment by Ozonni** [comment]
it's possible to run CT in default mode but then i need to introduce script in docker container where app starts in background and CT holds the process. But it looks nasty. Also there is problem that .net core doesn't have a way to handle Unix signals so almost any signal kills the process. I think it's rly specific case so we can close the issue.

**Comment by sethvargo** [comment]
Hi @Ozonni 

From your use case, I think the best approach is to not use exec mode and just use the arbitrary command argument to the template, like this:

```
template {
  source = "..."
  destination = "..."
  command = "service start"
}
```

As I said before, I totally understand this is a real problem you are facing, but it's outside of CT's exec mode design. Thanks and have a great day!
