### ISSUE TITLE
unable to pipe values from vault into base64Encode

### ISSUE THREAD

**Issue by cblecker** [hashicorp/consul-template#853]
### Consul Template version
`consul-template v0.18.0-rc3`

### Configuration
When attempting to use the new base64Encode function, I don't seem to be able to pass a string from vault into it for encoding.

```liquid
--- {{with secret "secret/certs/example.com" }}
apiVersion: v1
kind: Secret
metadata:
  name: example-com
type: Opaque
data:
  certificate: {{.Data.certificate | base64Encode}}
  key: {{.Data.privatekey | base64Encode}}
{{end}}
```

### Expected behavior
The variables from vault would be base64 encoded.

### Actual behavior
`secrets.yaml.ctmpl: execute: template: :13:37: executing "" at <base64Encode>: wrong number of args for base64Encode: want 1 got 0`

### References
Are there any other GitHub issues (open or closed) that should
be linked here? For example:
- GH-824
- GH-837

**Comment by sethvargo** [comment]
Hmmm... this is very interesting, and I'm not sure why this is happening. This does _not_ happen when using a non-vault dep:

```liquid
{{ with key "foo" }}
{{ . | base64Encode }}
{{ end }}
```

That error isn't actually coming from CT - it's much higher up the stack when Go is actually parsing the template. I wonder if this is a typed nil thing, since the resulting interface from vault is untyped... I'm going to explore more, but this has me a bit baffled. I can 100% reproduce it, but I have no idea why.

**Comment by cblecker** [comment]
Thanks for looking into it! I'm glad it's not me being stupid and using it wrong.

If there is anything I can do to help, please let me know!

**Comment by sethvargo** [comment]
I reported this upstream. I can reproduce this entirely without CT: https://github.com/golang/go/issues/18716, https://play.golang.org/p/R3CMVl_nmx
