### ISSUE TITLE
README on release tag contains master branch caveat

### ISSUE THREAD

**Issue by blalor** [hashicorp/consul-template#872]
https://github.com/hashicorp/consul-template/blob/v0.18.0/README.md

> **The documentation in this README corresponds to the master branch of Consul Template. It may contain unreleased features or different APIs than the most recently released version.**

Since the README is _the_ documentation source for this project, released versions should not contain this master branch caveat.

**Comment by sethvargo** [comment]
Hi @blalor 

Thanks for opening an issue. Unfortunately we have rather limited resources (working on improving that), but this isn't something we'll fix in the short term. The tradeoff of manually remembering to update that section of the README on each release is not worth it due to the limited resources we have. I understand this might not be perfect, but that warning is designed to inform people who come to the main README page expecting all the commands to work, but they've installed an older version. In the future, CT will have its own website, but, as I said, resource constraints. Thanks for understanding! 😄
