### ISSUE TITLE
Enhancement: consul-template attribute to ignore errors

### ISSUE THREAD

**Issue by rszabo50** [hashicorp/consul-template#905]
I am currently using consul-template v0.16.0

I was wondering if it was possible to add another key value to the template so that consul-template does not die when a single registered template fails. 

The workaround using the "|| true" works but is not the most convenient (quoting issues).  It also does cater for write errors on the filesystem for which that particular template is used.

If we demonize consul-template via systemd and we have several templates being handled by the one daemon , then we do not one template stopping all templates from being processed.

Suggestion:

```hcl
template {
    source: "some template"
    destination: " some destination"
    command: "some command"
    on_errror: "fail"   ## default is fail, other options would be ignore 
 }
```

Regardless of error condition logging is important.

This would make it very robust and avoid some of the issues people are seeing with nested quotes on the command definition whilst catering for other possible error conditions.

**Comment by sethvargo** [comment]
Hey @rszabo50 

Thank you for the suggestion. I can see how this would be useful, but I don't think this is something we will implement ourselves. If you'd like to take a stab at it, I'd gladly review a pull request though! Since we don't plan on implementing this ourselves, I'm going to close out this issue. Have a great day! 😄
