### ISSUE TITLE
scratch.MapValues "not a map" error

### ISSUE THREAD

**Issue by pkrolikowski** [hashicorp/consul-template#906]
Hello, 
I have a problem witch `scratch.MapValues` function returning `not a map` error.

### Consul Template version

`consul-template v0.18.1`

### Configuration

Consul foo/bar:

```
[
  {
    "name": "first",
    "dc": "us-west"
  },
  {
    "name": "second",
    "dc": "us-east"
  }
]
```
Template file (ct_test.ctmpl):

```
{{- $services := key "foo/bar" | parseJSON -}}
{{- range $services -}}
{{- scratch.MapSet "vars" .name .dc -}}
{{- end -}}
{{ scratch.MapValues "vars" }}
```

### Command

```
consul-template -once -dry -consul-token=xxx -template=ct_test.ctmpl
```

### Expected behavior

Sorted list of values should be returned: `[us-east us-west]`

### Actual behavior
I'm getting the following error message
```
ct_test.ctmpl: execute: template: :5:10: executing "" at <scratch.MapValues>: error calling MapValues: "vars" is not a map
```

I made a second test replacing ` scratch.MapValues` with `scratch.Get` and it works fine:

```
consul-template -once -dry  -consul-token=xxx -template=ct_test.ctmpl
> 
map[first:us-west second:us-east]
```

**Comment by LinusU** [comment]
I have this problem as well, I did notice that it works if something writes to the map outside of the loop, e.g.

```text
{{- scratch.MapSet "vars" "foo" "bar" -}}
{{- $services := key "foo/bar" | parseJSON -}}
{{- range $services -}}
{{- scratch.MapSet "vars" .name .dc -}}
{{- end -}}
{{ scratch.MapValues "vars" }}
```

**Comment by sethvargo** [comment]
Hi there,

The return value is not a map, but a list of _values_ (https://github.com/hashicorp/consul-template#scratchmapvalues). See my response [here](https://github.com/hashicorp/consul-template/issues/910#issuecomment-288922122), but since Go's maps are unordered, returning a map would result in a different template being rendered each time.

Second, the reason you are getting that error is due to CT's multi-pass evaluation. The first time the template renders, that key is empty, so the parseJSON is empty, so `services` is an empty list, meaning that `range` doesn't run. So your code is basically compiled into this:

```liquid
{{ scratch.MapValues "vars" }}
```

You asked for a map that does not exist, so the error is correct. Whether that's the correct behavior is up for debate, but that's what's happening. I _think_ Consul Template should probably just return an empty slice in this case instead of returning an error.
