### ISSUE TITLE
how does consul-template detect when to overwrite or not?

### ISSUE THREAD

**Issue by skygragon** [hashicorp/consul-template#911]
let's say I have a source template and it will be filled with some attrs from consul kv store. Will consul-template be triggered to generate new output if source template changed, but attrs not changed? I guess it will compare the digest of the existing output and the new output, and only overwrite if mismatch, is it correct?

**Comment by sethvargo** [comment]
Hi @skygragon 

Input templates are read at boot time. So if you have 10 templates on disk, they are all read into memory on start and processed. From there, any change in Consul/Vault renders the template in-memory with the new values. That new template is then compared to the template on disk, and, if there is a difference, a new version if rendered.

If the input template is modified while Consul Template is running, that change is not detected. This is an intentional design decision, and you can read more in some of the closed issues. To detect changes, send the `HUP` signal to the Consul Template process after modifying the template.

Please let me know if you have any questions!

**Comment by skygragon** [comment]
Thanks. Then can I configure consul-template to regularly always overwrite the output and trigger the action? Even if there is no difference from last output?

**Comment by sethvargo** [comment]
Hi @skygragon 

That is not possible, but you can watch a key (and trigger that key). It will only render on file change.
