### ISSUE TITLE
Top-level "env" section fails to parse

### ISSUE THREAD

**Issue by lambdaknight** [hashicorp/consul-template#915]
### Configuration

```hcl
env {
    custom = ["STAGE=development"]
}

template {
    source = "foo.conf.ctmpl"
    destination = “foo.conf”
}
```

### Command

```shell
bin/consul-template -config foo.consul-template.conf -once -log-level=trace
```

### Debug output

```shell
Consul Template returned errors:
from file: foo.consul-template.conf: mapstructure decode failed: 1 error(s) decoding:

* '' has invalid keys: env
```

### Expected behavior

According to the [Configuration File Format](https://github.com/hashicorp/consul-template#configuration-file-format) documentation, a top-level "env" section is supported and has the following comment:
```hcl
# This is customization around the environment in which template commands are
# executed. See the "exec" block for more information on the specific
# configuration options.
env {
  # ...
}
```

### Actual behavior

The config file fails to parse and complains about an invalid key "env".

### Steps to reproduce

1. Using the provided configuration file, try running consul-template.
2. Watch it fail.

### Additional Notes
The documentation is a bit unclear about how this is supposed to work. Is the environment defined in this block available to the template file when it is rendered or only to what is run by the "command" key in the "template" section?

**Comment by sethvargo** [comment]
Hi @lambdaknight 

Sorry about that. That section actually belongs under `exec`, as it's comment implies. Having a top-level env would not make much sense, since you can just pass envs directly to the `consul-template` binary. I've pushed up 47fe457, but I want to make sure I'm not missing a use case before closing.

**Comment by lambdaknight** [comment]
It would be nice to be able to supply different variables to different sets of templates since environment variables are the only way of passing in parameters to the template rendering.

**Comment by sethvargo** [comment]
Okay, I think we have all the plumbing to make that possible. Just need to hook up the configs

**Comment by sethvargo** [comment]
Ah, okay. I remember why this isn't possible. For performance reasons, multiple input templates are condensed into a single template render event. This is important for a number of internal reasons, but is also required by external libraries. We render that template once, and then go back to the configuration and "copy out to disk" for any of the templates that used that template as an input. Because of this, we can't pass a custom environment to the template render, since we don't want to render the same template multiple times, and it creates a catch-22 where we won't know which templates to lookup prior to rendering. So, unfortunately this simply isn't possible with Consul Template's current architecture. Sorry for the configuration. Have a great day! 😄
