### ISSUE TITLE
Restarts exec child on reload

### ISSUE THREAD

**Issue by tino** [hashicorp/consul-template#945]
### Consul Template version
0.18.5

### Configuration

```hcl
reload_signal = "SIGUSR1"
exec {
  command = "/usr/sbin/nginx -g \"daemon off;\""
  reload_signal = "SIGHUP"
}
template {
  source = "/etc/nginx/templates/general.ctmpl"
  destination = "/etc/nginx/conf.d/general.conf"
}
```

### Command

```shell
consul-template -config=/etc/consul-template/consul-template.hcl
```

### Debug output
```
 2017/05/27 09:07:02.252726 [INFO] consul-template v0.18.5 (9902dd5)
 2017/05/27 09:07:02.252756 [INFO] (runner) creating new runner (dry: false, once: false)
 2017/05/27 09:07:02.254008 [INFO] (runner) creating watcher
 2017/05/27 09:07:02.256939 [INFO] (runner) starting
 2017/05/27 09:07:02.257082 [INFO] (runner) initiating run
 2017/05/27 09:07:02.332140 [INFO] (runner) initiating run
 2017/05/27 09:07:02.340574 [INFO] (runner) initiating run
 2017/05/27 09:07:02.351247 [INFO] (child) spawning: /usr/sbin/nginx -g daemon off;
 Reloading configuration...
 2017/05/27 09:07:11.685124 [INFO] (runner) stopping  
 2017/05/27 09:07:11.685223 [INFO] (child) stopping process <== why?
 2017/05/27 09:07:11.789284 [INFO] (runner) received finish
 2017/05/27 09:07:11.790750 [INFO] (runner) creating new runner (dry: false, once: false)
 2017/05/27 09:07:11.790899 [INFO] (runner) creating watcher
 2017/05/27 09:07:11.794581 [INFO] (runner) starting
 2017/05/27 09:07:11.794625 [INFO] (runner) initiating run
 2017/05/27 09:07:11.848229 [INFO] (runner) initiating run
 2017/05/27 09:07:11.861533 [INFO] (runner) initiating run
```

### Expected behavior
Nginx should not be restarted, but reloaded

Because then I can make template changes without going offline, as is possible with nginx without consul-template.

### Actual behavior
Nginx was stopped and started

### Steps to reproduce
1. Run with this config (in a Docker container)
2. Send `kill -USR1` to consul-template

**Comment by sethvargo** [comment]
Hi @tino 

This is behaving as intended, and I think you might be conflating "reload nginx" with "reload consul template".

The top-level `reload_signal` is the signal that Consul Template responds to to reload its own configuration. For example, if you change a configuration option or template, you need to tell Consul Template to reload it's configuration. This signal is given manually by an operator or another process.

The exec-level `reload_signal` is the signal Consul Template sends to the underlying child process to tell it to reload its configuration due to a template change. This signal is given to the child by Consul Template when a template changes. Consul Template will do this automatically if one of the underlying templates under management changes.

During a full configuration reload, there's no way to intelligently determine if the resulting template changes or config changes would impact the child process, so we are forced to kill the running process and spawn a new instance. This is why you are seeing that log output in your sample; you are restarting Consul Template, which causes its underlying process to stop and spawn again.
