### ISSUE TITLE
Target file permission denied error log not written to syslog

### ISSUE THREAD

**Issue by f-ld** [hashicorp/consul-template#947]
### Consul Template version

0.18.3 (but same issue with latest)

### Expected behavior

Error prevent service to start are logged in syslog (once it is started)

### Actual behavior

Somes logs are written to syslog, but not the error when target file is not writable by user running consul-template: that error is only written on stdout

### Steps to reproduce

1. Create a conf with template T converted to target file F and logs pushed to syslog
2. Make file F unwritable to user running consul-template
3. Run consul-template
4. on stdout, there is a log like:
```
Consul Template returned errors:
error rendering "/some/path/T" => "/path/to/F": failed writing file: open /path/to/230244764: permission denied
```
5. in syslog, no error written

**Comment by sethvargo** [comment]
Hi @f-ld 

Could you please share your complete Consul Template configuration, template, and commands?

**Comment by f-ld** [comment]
I cannot share my configuration for confidentiality matters, but can give you an example:
```
mkdir issue947
pushd issue947
echo "Some content" > template
consul-template -log-level=info -template template:result -once -log-level=info
# See output 1 below: result file generated as expected
rm result
chmod u-w .
consul-template -log-level=info -template template:result -once -log-level=info
# See output 1 below: result file is not generated as expected
```

And now the outputs:
- output1:
```
2017/06/02 06:38:26.130825 [INFO] consul-template v0.18.5 (9902dd5)
2017/06/02 06:38:26.130848 [INFO] (runner) creating new runner (dry: false, once: true)
2017/06/02 06:38:26.131168 [INFO] (runner) creating watcher
2017/06/02 06:38:26.131395 [INFO] (runner) starting
2017/06/02 06:38:26.131436 [INFO] (runner) initiating run
2017/06/02 06:38:26.134547 [INFO] (runner) rendered "template" => "result"
2017/06/02 06:38:26.134569 [INFO] (runner) once mode and all templates rendered
2017/06/02 06:38:26.134575 [INFO] (runner) stopping
```
- output2:
```
2017/06/02 06:39:31.578706 [INFO] consul-template v0.18.5 (9902dd5)
2017/06/02 06:39:31.578729 [INFO] (runner) creating new runner (dry: false, once: true)
2017/06/02 06:39:31.579047 [INFO] (runner) creating watcher
2017/06/02 06:39:31.579145 [INFO] (runner) starting
2017/06/02 06:39:31.579182 [INFO] (runner) initiating run
Consul Template returned errors:
error rendering "template" => "result": failed writing file: open 178012670: permission denied
```

The last 2 lines of output2 are not logs but pure stdout prints. They are not logged to syslog if this is used for logging (and if stdout is ignored)

**Comment by sethvargo** [comment]
I see. This is a tricky one. Consul Template has actually terminated at that point, so we write to the errorstream (stderr). We could try and write to the logger, but it's not a "log" message per-sae, it's a message for the user.

That's the same error handler that runs when logging fails to setup, which is why we fallback to stderr. Even if we tackled that problem, using a logger to write those errors would make it more challenging as a user to pull these out (a lot of people just look at stderr for output and ignore stdout). Additionally the human-friendly output would contain the timestamps and go information that isn't relevant to regular use. But if we double-log (print to stderr and use the logger), 95% of users would see two log messages, since the default logger is stdout. 

There are a few places where the output is not necessarily log messages, and those are:

- The version output
- The output of the template in `dry` mode (prints to stdout)
- An error exiting text
- A message when CT reloads its configuration
- A message when CT is exiting gracefully
- Flag usage output (help)
