### ISSUE TITLE
passing if conditions to consul templates

### ISSUE THREAD

**Issue by ezlee** [hashicorp/consul-template#951]
My nginx configuration files have conditions, how do I pass the variables into the nginx config file by consul-template command line? But not being processed by consul-template.

For example, I want my nginx.conf file have the $geoip_country_code variable. 

```
if ($geoip_country_code ~ (BR|CN|KR|RU|UA) ) {
    # Do something
}
```

**Comment by sethvargo** [comment]
Hi @ezlee 

Thank you for opening an issue. Unfortunately I'm not sure what you are asking. When you open an issue on Consul Template, we pre-fill a series of questions that are very helpful in getting questions like these answered.

It sounds like you are asking how to use `$geoip_country_code` in your template, and since it starts with a dollar sign, it might be interpreted as a variable. The templating language only processes things between `{{`, so using `$var` outside of `{{ }}` will render as the literal value.

If this does not answer your question, please open a new issue and complete the questions that pop up in the issue template.

**Comment by ezlee** [comment]
Thank you, Seth!
Yes, it is outside of {{ }}, and can be passed to the result file.
