### ISSUE TITLE
Add a "hasField" function

### ISSUE THREAD

**Issue by nugend** [hashicorp/consul-template#954]
https://stackoverflow.com/questions/34703133/field-detection-in-go-html-template

Would be helpful when working with non-regular trees.

Another possibility would be this functionality plus a "OrDefault". As in, "fieldOrDefault".

**Comment by sethvargo** [comment]
Hi @nugend 

Thank you for opening an issue. I'd like to learn a bit more about the use case here. What are you trying to achieve? What does your object look like? What is your expected API/result?

**Comment by nugend** [comment]
So we have a set of service instances that are moderately customized for special users. Many of these are identical to existing service instances, so in our config generator, we insert a "cloned" reference and in the template that generates the job file, simply iterate over the instances (using explode). Some of these instances need a special setting that's easiest to handle in the configs by adding an additional leaf node into the kv tree on that specific instance. In the template, the slight difference in generated file would be more easily handled by checking "Hey, does this field exist in this struct?"

It's possible to work around, but since "keyOrDefault" is a function, "hasOrDefault" also seems to make sense.

**Comment by sethvargo** [comment]
Hmm... So it sounds like you might be trying to mirror something like Chef's Ohai or Puppet's Hiera with Consul KV data. In general, we strongly recommend against this for a few reasons. First, when you do this type of client-side key merging, it puts additional load on the cluster, since each client has to watch every key for changes as opposed to watching one folder. Second, it makes scalability with deduplication mode more challenging due to the number of dependencies. We usually recommend users build these configurations with a tool external to Consul Template that queries the Consul API directly and builds a flat/folder structure for each service so that `tree "services/my-service" has all the configuration data for that service with few exceptions. This also has the added benefit that anyone who wants to view the configuration for `my-service` can just read that folder and not have to apply client-side template filtering in their head. It's kinda like "build time vs run time", where the Consul KV is the runtime and your external script is build time.

That being said, I'm not _opposed_ to adding this, but we need to thing about the API a bit more. Is there a reason Golang's builtin `{{ if ... }}` pipeline does not work? It will return false if the value is the empty string, 0, or nil (which should encapsulate most of Consul Template's map types):

```golang
{{ with $value := index $m "my-key" }}
{{ $value }}
{{ else }}
no key
{{ end }}
```

**Comment by nugend** [comment]
I actually do have each service in a folder and I am using tree to access them (I explode the tree for each service). The problem comes with these special client specific services that have varying options that we need to turn on and off with flags to the command line while using the exploded tree.

Rather than checking if a key exists or has a default, I just want to check if the exploded struct has a field (or otherwise provide a default)

I was able to work around it, but I just thought a fieldOrDefault or hasField (mirroring the keyOrDefualt and hasKey template functions), would be a nice interface.  I mean, as is, if I wanted to put a crap ton of extra watches in place, I could construct the path to the key at runtime using printf and then use keyOrDefault to replicate the behavior. But that would be very inefficient.

**Comment by sethvargo** [comment]
Could you share how you would use `fieldOrDefault` and `hasField` in a template? Sorry, but I'm really not following the structure of your KV data enough to see how this would be used ☹️

**Comment by nugend** [comment]
Let me check what I used as a workaround. This was a few days ago and I am not at my terminal. I might have used something similar to what you're suggesting. If that's the case, I guess we can close it.

**Comment by nugend** [comment]
Yeah. I ended up using "with" clauses. I wouldn't call myself an expert with go templates, unfortunately. Some things that seem obvious are a bit confusing.
