### ISSUE TITLE
breaks when there is a character in a services tag outside of [A-Za-z0-9_-]

### ISSUE THREAD

**Issue by dansteen** [hashicorp/consul-template#958]
### Consul Template version
0.18.5
( and whatever version is currently in nomad)

### Configuration

```hcl
instances:
{{ range service (printf "host:%s.org-api-jmx.service.consul|any" ( env "node.unique.name" ) ( env "APP_NAME" ) ) }}
    -   host: {{ .Address }}
        port: {{ .Port }}
{{ end }}
```

### Command

```shell
consul-template -once -template=/tmp/generate_config_26788.tmpl:/tmp/generate_config_26788.conf
```

### Debug output
https://gist.github.com/dansteen/cba36a5119a04b6038347c4c84791492

### Expected behavior

It should have searched consul for a service containing the tag "host:\<name\>"

### Actual behavior
consul-template complains about "invalid format".

Consul does not place any restrictions on the content of service tags.   (It actually says they are supposed to be "opaque" to consul here:  https://www.consul.io/docs/agent/services.html).   However, it looks like consul-template does not support tags that contain characters outside of `[A-Za-z0-9_-]` (and gets confused by tags that contain a period due to the DNS nature of the request).
 
Thanks!

**Comment by sethvargo** [comment]
Hi @dansteen 

This is behaving as intended. `:` is not a valid character in a DNS address, therefore we do not permit it in Consul Template. I understand that it may work when using the API, but future versions of Consul may be more restrictive about the characters which are permitted in service names because it causes errors at the discovery layer.

I definitely understand how this can be a sad answer, but it's something we are particularly steadfast on in Consul Template. You'll have a much better overall Consul experience if you avoid these types of special characters in your service names. Thanks! 😄

**Comment by dansteen** [comment]
ok thanks.
