### ISSUE TITLE
Absent Vault fields render as "<no value>"

### ISSUE THREAD

**Issue by pschultz** [hashicorp/consul-template#972]
### Consul Template version

```
$ ./consul-template -v
consul-template v0.19.0 (33b34b3)
```

### Configuration

No config required. Template:

```liquid
{{ with secret "secret/my-secret" }}
password = "{{ .Data.b }}"
{{ end }}
```

### Command

```shell
vault server -dev -dev-root-token-id=root
```

```shell
export VAULT_TOKEN=root
export VAULT_ADDR=http://localhost:8200

vault write secret/my-secret a=a

./consul-template -once -dry \
    -vault-renew-token=false \
    -template test.tpl
```

### Debug output

https://gist.github.com/pschultz/62e2ce8bba3cc4b872e6e582f4aae97a

### Expected behavior

consul-template should fail or render `password = ""`, since the field `b` doesn't exist. This is what happens if secret/my-secret itself doesn't exist.

### Actual behavior

consul-template renders `password = "<no value>"`. This seems quite dangerous to me. It makes it very easy to setup predictable passwords, encryption keys, etc. by accident.

**Comment by sethvargo** [comment]
Hi @pschultz 

Thank you for opening an issue. This is definitely an interesting one... I spent some time tracking this down. We use [Go's text/template](https://golang.org/pkg/text/template) implementation for template parsing. The templating language does support an [Option](https://golang.org/pkg/text/template/#Template.Option) to print out the zero value instead of "<no value>" (which is coming from Go's templating language, not Consul Template directly). However, I tried to switch to `missingkey=zero` and it doesn't work.

Vault's `Secret` struct returns a `Data` object of type `map[string]interface{}`, basically this:

```golang
type Secret struct {
  Data map[string]interface{}
  // other fields
}
```

Since this data is type `map[string]interface{}`, the keys have to be strings, but the values could be anything, including deeply nested types like other maps, lists, ints, floats, etc. Go's templating language relies on the type to figure out what the "zero" value is, but since `interface{}` has no zero value, the templating engine falls back to "<no value>". There's no way for it to know that it should return `""` vs `0` vs `0.0` vs `nil`, since the type `interface{}` satisfies all of those zero types.

The only other option is to use `missingkey=error`. This correctly errors, but it would introduce a breaking change for folks who are relying on the pass-through behavior as-is. As a work-around for now, you can guard against the empty value using another `with` clause:

```liquid
{{ with secret "secret/my-secret" }}{{ with .Data.b }}
password = "{{ . }}"
{{ end }}{{ end }}
```

I'm going to investigate adding "error on zero" as a configuration option.

**Comment by maxb** [comment]
For people reading this ... Each time in @sethvargo 's long explanatory comment where they have written "&lt;no value>", GitHub is really confusingly rendering it as "", as the &lt;no value> is being treated as an HTML tag, and being hidden!

(I escaped mine so they show up in this comment.)
