### ISSUE TITLE
Unexpected retry intervals

### ISSUE THREAD

**Issue by phaer** [hashicorp/consul-template#982]
### Consul Template version

````
consul-template v0.19.0 (33b34b3)
````

### Configuration

```hcl
consul {
  address = "localhost:8500"
  token = ""
  retry = {
    enabled = true
    attempts = 5
    backoff = "10s"
  }
}

log_level = "trace"
kill_signal = "SIGTERM"

vault {
  address = "https://active.vault.service.consul:8200"
  ssl {
    enabled = true
    verify = true
    cert = "/etc/ssl/certs/xdb-a01.pem"
    key = "/etc/ssl/private/xdb-a01.pem"
    ca_cert = ""
  }
  grace = "5m"
  retry {
    attempts = 3
    backoff = "250ms"
    max_backoff = "1m"
  }
}
  syslog {
    enabled = true
}
template {
  source = "/etc/consul-template/mysql-monitor.ctmpl"
  destination = "/etc/mysql/monitor.cnf"
  command = "true"
  perms = 0600
}
```

```liquid
{{ with secret "mysql/creds/monitor" }}
[mysql]
user={{ .Data.username }}
password='{{ .Data.password }}'
{{ end }}
```

### Command

```shell
/usr/local/bin/consul-template -config /etc/consul-template/config
```

### Debug output

https://gist.github.com/phaer/0b9eaaf0503b54b0a8106c122c6c3a41

### Expected behavior

I would have expected consul-template to retry after 250ms, 500ms and 1s.

### Actual behavior

consul-template retries to read mysql/creds/monitor after 3250ms, 3500ms, and 4000ms, always 3s more than I would have expected according to the following excerpt of README.md:

```
    # This is the base amount of time to sleep between retry attempts. Each
    # retry sleeps for an exponent of 2 longer than this base. For 5 retries,
    # the sleep times would be: 250ms, 500ms, 1s, 2s, then 4s.
    backoff = "250ms"
```
Am I missing anything?

### Steps to reproduce

1. run consul-template with the config above.
2. check timestamps in your log

**Comment by sethvargo** [comment]
Hi @phaer 

Thank you for opening an issue. The retry configuration is how long to sleep _after_ something fails. My _guess_ would be that you have 3s of network latency before receiving a response or some kind of dial timeout. Another guess would be DNS resolution - it's possible that your local resolver is taking 3s to resolve or route to active.vault.service.consul. Or, since it's Consul, during that time, a new leader election is taking place in Vault.

When I run this locally, I get really close to 250ms, 500ms, 1s, etc. It's always going to be off by a few ms because you have to account for the actual time to try and make the request as well.

I hope that helps! Please let me know if you have any additional questions.
