### ISSUE TITLE
Certs from vault pki backend with a 1m ttl get renewed after 2m:30s

### ISSUE THREAD

**Issue by alvaroaleman** [hashicorp/consul-template#985]
### Consul Template version

`consul-template v0.19.0 (33b34b3)`

### Expected behavior

1. Create a vault pki role with `max_ttl=1m`
2. Use that role in a consul-template template to issue a certificate
3. Certificate gets renewed after 30s

### Actual behavior

1. Create a vault pki role with `max_ttl=1m`
2. Use that role in a consul-template template to issue a certificate
3. Certificate gets renewed after 2m30s

### Steps to reproduce

1. Create a vault pki role with `max_ttl=1m`
2. Use that role in a consul-template template to issue a certificate
3. Wait

**Comment by sethvargo** [comment]
Hi @alvaroaleman 

Thank you for opening an issue. This is already fixed in master (unreleased). The challenge is that we needed a "sane" default minimum, which was 5m before. It's still 5m, but you can configure the grace period in master, which you would need to tune to something less than 1m (like 5s).
